### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by eugeneloza** [troop/FreeDcam#100]
> FreeDcam is a CameraApp for Android >4.0(ics) wich trys to enable stuff that is forgotten by the manufacturs (in project description)

I think it's better to rephrase to: FreeDcam is a CameraApp for Android >4.0(ics) wich **_tries_** to enable stuff that **_was_** forgotten by the manufacturs

**Comment by troop** [comment]
im not a english teacher^^
but it is forgotten. if manufacturs would fix it, it was forgotten.

and cause of tries/trys
it took me alot tries.
Try it out.

**Comment by KaelWD** [comment]
> but it is forgotten. if manufacturs would fix it, it was forgotten.

The problem is awkward tenses; if you want to keep the meaning I think you're going for it would be "stuff that has been forgotten". 

Also 
wich -> which 
manufacturs -> manufacturers
CameraApp -> camera app

Maybe leave the english to people that speak it every day.

**Comment by troop** [comment]
Ist​ ok dann schreib ich jetzt nur noch deutsch.

**Comment by KaelWD** [comment]
Sicher, Google Translate macht eine ziemlich anständige Arbeit von Deutsch auf Englisch. Viel Spaß mit dem anderen Weg aber.
