### ISSUE TITLE
Prestigio Multipad Color 7.0 3G black screen

### ISSUE THREAD

**Issue by eugeneloza** [troop/FreeDcam#101]
Hi all!
FreeDCam works fine for my Prestigio Multipad Color 7.0 3G taking jpg and bayer images.
But I came across a bug - If i put the tablet to suspended mode while the camera is running, the screen won't light up when tablet turned back on and only a hard-reboot helps.

**Comment by troop** [comment]
thats something new. normaly the camera gets paused when screen turns off and started when its back/resumed. does that happen with other camera apps too?

**Comment by troop** [comment]
can you pls attach the camera parameters and the bayer file?
you can save the parameters inside freedcam settings. on left tap scroll to bottom and click there save cameraparameters. it gets then saved to internalSD/DCIM/FreeDcam/YourDevice_CameraParameters.txt

**Comment by eugeneloza** [comment]
@troop thanks a lot for your reply!
No, I've been using google camera and opencamera and they both don't black the screen out. Neither any other app I've been using thus far.
I'll send the camera parameters tomorrow (the tablet is at home) and the bayer file is attached.
[mtk1468487618079__1584x1188_10_0.bayer.zip](https://github.com/troop/FreeDcam/files/395477/mtk1468487618079__1584x1188_10_0.bayer.zip)

**Comment by eugeneloza** [comment]
I'm afraid I could not find the camerasettings in the freedcam settings/left panel. That's how my freedcam settings look:
![dscf9059](https://cloud.githubusercontent.com/assets/10726162/17358950/2615d720-596d-11e6-8523-dca663292895.JPG)

**Comment by troop** [comment]
It is there. Its direct under storage location.

**Comment by eugeneloza** [comment]
Yes... looks like exactly the case. However, navkeys are hidden in the freedcam main screen (where I take the photos). But not in settings screen. And the 'upper' bar is always hidden in all modes.
Releasing 'locked orientation' for the device also didn't help, the freedcam orientation is always landscape.

**Comment by troop** [comment]
Hm thats confusing. Its set for the app not only the cameraui. Solution is to create a DEBUG folder inside Dcim/freedcam. Then next start saves a log into that folder. When done delete that folder. Else it creates on each start a new log

**Comment by eugeneloza** [comment]
[PMT5777_3G_2016_08_04_01_32_41.txt](https://github.com/troop/FreeDcam/files/401410/PMT5777_3G_2016_08_04_01_32_41.txt)
Done.
