### ISSUE TITLE
Avast Security Issue

### ISSUE THREAD

**Issue by PwnArt1st** [troop/FreeDcam#105]
freedcam is tagged as a security risk by avast

**Comment by defcomk** [comment]
Funny i don't ever take andoid security apps seriously freedcam is open source so you can have a look at it nothing risky about it

**Comment by PwnArt1st** [comment]
Got it just in case, i get apps from all over and Avast had good reviews

**Comment by PwnArt1st** [comment]
has any action on this occurred?

**Comment by troop** [comment]
No there is nothing inside. Else google would have noticed me already. Freedcam is save. If you dont trust opensource stuff dont use it!
