### ISSUE TITLE
Missing EXIF data in DNG

### ISSUE THREAD

**Issue by fingli** [troop/FreeDcam#106]
I'm using FreeDcam in Lenovo Vibeshot Z90a40
In Jpeg files EXIF presents with all parameters available from the build-in camera, but in DNG there are only: manufacturer, model and program. Other technical details about the cam are missing. 

I can provide more details if needed.

**Comment by troop** [comment]
thats correct. 
newer devices like yours have that stuff inside the parameters. 
```
cur-exposure-time=50.000902
cur-focus-diopter=0
cur-focus-scale=100
cur-iso=497
```
but older devices dont have it. was to lazy to add it as workaround.
exif is nice to have. but its not needed for postprocessing.

**Comment by Llusato** [comment]
I'm using FreeDcam in **LG G3 D855 (International Model)**
In Jpeg files EXIF presents with all parameters available from the build-in camera, but in DNG there are only: manufacturer, model and program. Other technical details about the cam are missing.

I can provide more details if needed.

**Comment by troop** [comment]
Parameters on g3 does not return exif information.

**Comment by Llusato** [comment]
Thanks troop for your quick replay, so I suppose that it is impossible to get the exposure time from DNG pictures in LG G3. To get these parameters, then the only option is to take jpeg pictures, isn't it?

**Comment by troop** [comment]
yes thats correct. 
we had it once that it takes two pictures, first as bayer and second as jpeg and extracted it from the jpeg.

but that need two full captures to get them and got dropped due a rework and some other reasons like, when longer exposures is used upto 30sec it would finaly take 1min to complete it, just to get the exif data.

its already bad with 1 sec wich is possible on the g3 with iso800 and expo compensation slider pushed to max.
