### ISSUE TITLE
Crash Log files (for reference only)

### ISSUE THREAD

**Issue by fingli** [troop/FreeDcam#107]
Phone: Lenovo Vibe Shot Z90a40
OS: Android 6.0.1

I'm adding these logs just for diagnosing problems. FreeDcam works perfectly with JPEGs but with DNGs sometimes crashes. Also it crashes at the first launch after installing, I think it is some conflict with the permissions asked by Android, once you give the access permissions it works well.

[Lenovo Z90a40_2016-08-17_02.57.02.txt](https://github.com/troop/FreeDcam/files/422398/Lenovo.Z90a40_2016-08-17_02.57.02.txt)
[Lenovo Z90a40_2016-08-17_03.01.08.txt](https://github.com/troop/FreeDcam/files/422395/Lenovo.Z90a40_2016-08-17_03.01.08.txt)
[Lenovo Z90a40_2016-08-17_12.36.24.txt](https://github.com/troop/FreeDcam/files/422397/Lenovo.Z90a40_2016-08-17_12.36.24.txt)
[Lenovo Z90a40_2016-08-17_12.37.13.txt](https://github.com/troop/FreeDcam/files/422396/Lenovo.Z90a40_2016-08-17_12.37.13.txt)

**Comment by troop** [comment]
are you buidling from source or are that logs from latest release?

**Comment by fingli** [comment]
They are from the latest official release 3.3.140 in Google play

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by troop** [comment]
most of them should be gone with 3.3.141

**Comment by fingli** [comment]
Yes. After the last update there are no new.

Sent with AquaMail for Android
http://www.aqua-mail.com
