### ISSUE TITLE
Give option to split videos after 2 or 4 gb

### ISSUE THREAD

**Issue by gerrickw** [troop/FreeDcam#112]
Summary:
Currently on my Nexus 6P if the video file becomes ~5 gb freeDcam will show it is still recording, although when stopped and viewing the file it is unreadable by the video player.  It'd be nice to have a GoPro like feature which splits the file at a certain size so it can continue recording as expected.

Thanks for the nice camera app.

**Comment by troop** [comment]
i never tryed to record such a big file. but it should be possbile to add. 
thx for feedback

**Comment by gerrickw** [comment]
Sure.  Let me know if you need help testing the changes.  A friend races his car with a phone mount and I gave him the idea to try using freedcam, but it ends up creating a corrupt file when recording too long.  Assuming corruption happens due to the filesystem limits, so splitting I believe will help.

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/3.3.144beta2
should splitt it at 2,8gig or 2hours recording time reached

**Comment by gerrickw** [comment]
It now splits, thanks again.  I do randomly get small 300kb video files near the end when stopping recording, but doesn't bother me.
