### ISSUE TITLE
DNG for Xiaomi Redmi 3S (Pro/Prime)

### ISSUE THREAD

**Issue by liqpap** [troop/FreeDcam#113]
Only options are jpg and bayer. I think the camera is similar to the one in the Redmi 3.

Attached: 
.bayer of a random picture
camera settings file

[Xiaomi Redmi 3s.zip](https://github.com/troop/FreeDcam/files/498195/Xiaomi.Redmi.3s.zip)

**Comment by troop** [comment]
i look into it in the next 12 hours ^^

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/3.3.144beta3

**Comment by liqpap** [comment]
Still no option for DNG - anything else I can provide to help with the issue?

**Comment by troop** [comment]
pls make sure to clear the app cache. the device gets detected only once on first appstart.

**Comment by liqpap** [comment]
Cleared everything in the app settings, restarted: App asked for permissions again, showed tutorial, .settings were back to default values. No DNG option.

for good measure cleaned everything again, uninstalled app, reinstalled apk - no difference.

**Comment by troop** [comment]
hm thx, will look what i missed

**Comment by liqpap** [comment]
Newest Play Store release works for some reason - I don't see why, I guess there's some app cache that the miui interface did not clear properly for some reason... FIXED, thank you!

**Comment by troop** [comment]
no the problem was how i set the <string-array>**<item></item>**</string-array>
the item tag was missing. that caused it to fail. stupid copy paste fail^^
