### ISSUE TITLE
MyPhone Infinity 2S magenta tint

### ISSUE THREAD

**Issue by LosTigeros** [troop/FreeDcam#114]
Hello!

My DNG and BAYER file has magenta tint on all picture.
https://drive.google.com/open?id=0B5IKSY3sCuE9dUZDY1RUTjA1bVE

It looks -> https://drive.google.com/open?id=0B5IKSY3sCuE9Zl9XMDhSc2tBUDQ

**Comment by troop** [comment]
hi looks like the black level ist to low. its set to 16 but seems it need 64

**Comment by LosTigeros** [comment]
And its crashing on latest beta version:
https://drive.google.com/open?id=0B5IKSY3sCuE9M3o1SHpBRlpmOFk

**Comment by troop** [comment]
each time? or only when its not present in memory?

**Comment by LosTigeros** [comment]
Each time I open the app. It crashes instantly

**Comment by troop** [comment]
check pls this https://github.com/troop/FreeDcam/releases/tag/3.3.144beta5

**Comment by LosTigeros** [comment]
Its not crashing.

There is other problem now.
When I click shutter to take a picture it crashing (its not creating a crash log).
I must select "External memory" and select there path to internal memory. Then Its not crashing.

**Comment by troop** [comment]
dont no whats wrong. works on all my devices

**Comment by LosTigeros** [comment]
There is bad colors on DNG image.

I mean that YELLOW is BLUE and other colors are incorrect.

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/3.3.144beta6

new try.

**Comment by LosTigeros** [comment]
Now DNG is working perfectly!

https://drive.google.com/open?id=0B5IKSY3sCuE9M2NxSjF3NkcwS2s

Thanks!

**Comment by troop** [comment]
no problem hf with it it,closing issue
