### ISSUE TITLE
Black image with shutter time higher than 1/2000

### ISSUE THREAD

**Issue by LosTigeros** [troop/FreeDcam#115]
When shutter time is higher than 1/2000 the JPG file is black.
In DNG file it looks normal so is it bug?

The Phone is Infinity II S

https://drive.google.com/open?id=0B5IKSY3sCuE9cmpjb3pReVl3S1E

Latest camera parameters: https://drive.google.com/open?id=0B5IKSY3sCuE9aE1zS2Q4VzR5NjQ

**Comment by troop** [comment]
Could be a bug from oems camera driver/hal implementation. Freedcam itself handels raw and jpeg capture the same way. The only thing i can do is to remove all values that are faster then 1/2000.

**Comment by LosTigeros** [comment]
No, dont remove it. It works in faster shutter times but only in DNG format.

So maybe you could add a boolean setting to enable/disable shutter times which works only in raw format?

**Comment by troop** [comment]
hm that makes me not happy. for that the code is not designed.
pls try to turn off zsl/zsd in settings and look if that affects the jpeg with manual shutter

**Comment by LosTigeros** [comment]
With disabled zero shutter lag and ISO higher than 400 after taking a few pictures app crashes, dont create crash log and there is nothing in logcat.

**Comment by troop** [comment]
> Maybe it will show the error with "handleUncaughtException"?

then the crash stacktrace gets saved into dcim/freedcam/crash folder.
but not always. when you have access to a pc try to get it with adb

**Comment by LosTigeros** [comment]
I tried and there is nothing in logcat

**Comment by troop** [comment]
dont know. i dont think that including arca for logging will print the crash. it could be also a problem from the [Logger](https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/utils/Logger.java) that it gets killed bevor the log get written and avoid that the log gets printed

**Comment by LosTigeros** [comment]
Cant You just flush the log before closing the app?

**Comment by troop** [comment]
When android decide to destroy the context, it destroy it. No matter if you want to block it. Tryed also to start a new activity and pass the logcat to it.
But the passed log is cut off depending how long it took to destroy the context. 
I gave up on it and removed that stuff from source. Only true solution is to grab it with adb on non rooted devices.
