### ISSUE TITLE
HFR Video Recording isn't working in Redmi 3S

### ISSUE THREAD

**Issue by mohdmujahidansari526** [troop/FreeDcam#116]
Any type of video recording isn't working in Redmi 3S, neither HFR nor normal video  is being recorded.
Log Here: 
[Redmi 3S_2016-11-02_03.46.49.txt](https://github.com/troop/FreeDcam/files/566514/Redmi.3S_2016-11-02_03.46.49.txt)

**Comment by troop** [comment]
log?

**Comment by mohdmujahidansari526** [comment]
Here's the Crash Log.
[Redmi 3S_2016-11-02_03.46.49.txt](https://github.com/troop/FreeDcam/files/566513/Redmi.3S_2016-11-02_03.46.49.txt)

**Comment by troop** [comment]
that happens only when you did not grant permission for audiorecording or your device dont have a mic

**Comment by mohdmujahidansari526** [comment]
Granted the audio permissions, now recording working but HFR recording isn't working neither for 720p nor for 480p. its only recording upto 20-30 Fps.

**Comment by troop** [comment]
have you activated camera2 in build.prop?

**Comment by mohdmujahidansari526** [comment]
Nope. not enabled camera2Api in build.prop

**Comment by troop** [comment]
does it work in any other app?

**Comment by mohdmujahidansari526** [comment]
yeah. works in Snapdragon camera it records upto 120fps in 480p and 60fps in 720p
but only in Good Light Conditions.

**Comment by troop** [comment]
hm that explain alot. pls check the mediaprofiles if 720phfr contains 60fps and not 120.
if the profiles are correct the problem has something todo with the preview format.
legacy devices use nv12-venus as preview format.
on redmi3s you can enable camera2 so its in theory a full camera2 device wich dont work with nv12

**Comment by mohdmujahidansari526** [comment]
well, 720p 60 FPS is available in media profiles of my device.
You can check here : 
[media_profiles.zip](https://github.com/troop/FreeDcam/files/566699/media_profiles.zip)
 PS: attached media profiles.xlm in a zip archive cuz cant attach the file here directly.
PSS: I would like you to add slow-motion video support if possible.
I can help alot with testing.

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/3.3.147beta3
pls try that it use now normal yuv420sp for hfr

**Comment by mohdmujahidansari526** [comment]
Full log? from logcat?

**Comment by troop** [comment]
yes pls normaly it tells where it fails

**Comment by mohdmujahidansari526** [comment]
Only this 480p available.
and videos being recorded at 19 fps only.

**Comment by troop** [comment]
camera2 gets detected only on first app start. after that the appsettings are used.
so you had that build.prop camera2 enabled when you installed freedcam the first time.
that forced freedcam not to use nv12 on camera1 for highspeed recording.
my changes does now the same thing it avoids that nv12 gets used.
im going to revert it

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/3.3.147beta4

**Comment by troop** [comment]
you have to create a custom mediaprofile inside freedcam. choose the videoprofile editor inside freedcam settings.
there select the 480p profile.
rename it to 480phfr
change framerate to 120
and set highspeed.
then click save.
inside freedcam settings choose the 480phfr

**Comment by mohdmujahidansari526** [comment]
let me try it.

**Comment by mohdmujahidansari526** [comment]
Getting "Start Recording Failed" error.

**Comment by troop** [comment]
you changed  the record mode to highspeed? without log no idea

**Comment by mohdmujahidansari526** [comment]
yup changed the record mode to high-speed
and here's the full log.

[logcat.txt](https://github.com/troop/FreeDcam/files/568016/logcat.txt)

**Comment by troop** [comment]
`I/CameraSource( 4859): Use default 30fps for HighSpeed 30fps
E/QCameraParameters( 4859): int32_t qcamera::QCameraParameters::setMorphoHDR(const qcamera::QCameraParameters&), ++
E/QCameraParameters( 4859): int32_t qcamera::QCameraParameters::setMorphoHHT(const qcamera::QCameraParameters&), ++
E/QCameraParameters( 4859): str_val (null)
D/QCameraParameters( 4859): int32_t qcamera::QCameraParameters::setNumOfSnapshot():   nBurstNum = 1, nExpnum = 1
E/QCamera2HWI( 4859): int qcamera::QCamera2HardwareInterface::commitParameterChanges(), mParameters.isMorphoHDREnabled() 0
D/QCameraMorphoPostProc( 4859): Enable++, enable 0
E/QCameraMorphoPostProc( 4859): Enable: nothing to changed!
D/QCameraMorphoPostProc( 4859): Enable++, enable 0
E/QCameraMorphoPostProc( 4859): Enable: nothing to changed!
E/QCamera2HWI( 4859): int qcamera::QCamera2HardwareInterface::commitParameterChanges(), mParameters.isMorphoHHTEnabled() 0
D/QCameraMorphoPostProc( 4859): Enable++, enable 0
E/QCameraMorphoPostProc( 4859): Enable: nothing to changed!
E/CameraSource( 4859): Failed to set preview frame rate to 30 fps. The actual frame rate is 120
W/CameraClient( 4859): attempt to use a locked camera from a different process (old pid 0, new pid 4859)
E/ExtendedUtils( 4859): Failed to set parameter - cache-video-buffers
E/MediaRecorder(29049): start failed: -19`

**Comment by mohdmujahidansari526** [comment]
What does this means?

**Comment by troop** [comment]
Added it only for me that i dont have to crawl the log again.
It set first preview to 30fps. Setting hfr to 120 seems to force that the preview gets set too to 120fps wich fails because it expect or need 30 fps for it. How or why that happen i dont know. Need to think about

**Comment by mohdmujahidansari526** [comment]
okay here are the screenshots of 120fps 480p videos recorded from Snapdragon camera in Redmi 3S
![scr2](https://cloud.githubusercontent.com/assets/23211447/19964432/a0d4fb0e-a1e7-11e6-93a4-8d72479ed103.png)
![scr1](https://cloud.githubusercontent.com/assets/23211447/19964455/c11e0874-a1e7-11e6-9c41-8f525a318d0e.JPG)

**Comment by mohdmujahidansari526** [comment]
Any ray of hope??

**Comment by troop** [comment]
try latest alpha maybe it fix it. hardcoded the fps ranges

**Comment by mohdmujahidansari526** [comment]
Same "Video recording failed" error even with the latest alpha build.

**Comment by mohdmujahidansari526** [comment]
Still getting "Start Recording Failed" error when recording HFR video.

**Comment by troop** [comment]
yes i expected it because nothing was changed on that issue

**Comment by mohdmujahidansari526** [comment]
So will u work on the same in near future?

**Comment by defcomk** [comment]
[Uploading app-debu
[app-debug.zip](https://github.com/troop/FreeDcam/files/586682/app-debug.zip)
g.apk…]()
@mohdmujahidansari526 try this apk see if it records

**Comment by mohdmujahidansari526** [comment]
getting the same error. "Start Recording Failed"

**Comment by mohdmujahidansari526** [comment]
Still not being able to record a slo-mo video.
hoping to get it work someday.
