### ISSUE TITLE
S7 edge front camera RAW capture issue

### ISSUE THREAD

**Issue by 1400700226** [troop/FreeDcam#117]
I tested this version on my S7 edge phone, when capturing with front camera using RAW, the captured DNG is in deep green.

Hope solve this soon.

**Comment by troop** [comment]
when you select raw_sensor the android dngwriter gets used. in that case its not a problem from freedcam.
more a problem from s7 that it pass the wrong matrix to the dng writer.

**Comment by defcomk** [comment]
Attach a sample dng from the front sensor

**Comment by 1400700226** [comment]
I am selecting RAW10 format.

Here is a sample selfie DNG.

Hope you see soon.
[2016_11_01_22_11_43.zip](https://github.com/troop/FreeDcam/files/568695/2016_11_01_22_11_43.zip)

**Comment by troop** [comment]
hm looks like black lvl 64 is not enough, but thats also returned from the captureresult

**Comment by 1400700226** [comment]
Er... I am newbie, and how can I solve it? Does it can be solved by using exiftool? But I don't know how to use it. Please help me, thanks a lot!

**Comment by defcomk** [comment]
in the menu scroll to api selection select camera then scroll down to save camera parameters go back to api selection switch back to camera2

in DCIM/FreeDcam/ you will find a .text file attach that here we will try to fix the  black level

**Comment by 1400700226** [comment]
I have tried:
1.Select camera api to camera1, then scroll back, then goto camera menu again, and select back to camera2, then scroll bvack and exit camera.
But after that there is no .txt file in DCIM/FreeDCam. What wrong?

And I found in latest version the front camera view is not full on screen, it's only display in half of screen in under.

The screenshot is atteched.
![259511cab0fd0ebbdccc8bb73c02c164](https://cloud.githubusercontent.com/assets/23212351/20036442/8573ec0e-a443-11e6-8c2c-3067c0311ce8.jpg)

**Comment by troop** [comment]
try to hold the device landscape when starting freedcam or switching picformat/camera.

**Comment by 1400700226** [comment]
"Hold the device landscape"? I can't understand what you means, sorry

**Comment by troop** [comment]
```
---------------
|  landscape  |
---------------
```

```
-----
|   | Protrait
|   |
|   |
-----
```

**Comment by 1400700226** [comment]
Thanks, I've tried, no effect. 
Please fix dng capture problem, thanks!

Though the view problem not effect a lot, but fix it is good.

Thanks! Sorry for bad English
