### ISSUE TITLE
Crash after 10-15 minutes in interval mode (200-300 images)

### ISSUE THREAD

**Issue by demoded** [troop/FreeDcam#118]
looks like memory leak.
Previous versions worked fine.
[MX5_2016-11-05_05.43.58.txt](https://github.com/troop/FreeDcam/files/572695/MX5_2016-11-05_05.43.58.txt)
[MX5_2016-11-05_05.51.20.txt](https://github.com/troop/FreeDcam/files/572696/MX5_2016-11-05_05.51.20.txt)
[MX5_2016-11-05_05.59.45.txt](https://github.com/troop/FreeDcam/files/572698/MX5_2016-11-05_05.59.45.txt)
[MX5_2016-11-05_06.12.28.txt](https://github.com/troop/FreeDcam/files/572697/MX5_2016-11-05_06.12.28.txt)
[MX5_2016-11-05_06.28.26.txt](https://github.com/troop/FreeDcam/files/572699/MX5_2016-11-05_06.28.26.txt)
[MX5_2016-11-05_07.29.05.txt](https://github.com/troop/FreeDcam/files/572700/MX5_2016-11-05_07.29.05.txt)

**Comment by demoded** [comment]
the issue got on v3.3.146
rolled back to 3.3.143 - all OK

**Comment by troop** [comment]
cant reproduce it. tryed it yesterday to shoot 1 hour at 1 sec and it finished successfull
