### ISSUE TITLE
Redmi note 3 pro has only 4k video profile

### ISSUE THREAD

**Issue by semenovnick** [troop/FreeDcam#119]
Hi, my redmi note 3 pro has only 2160p profile. How can i change it to full hd, for example? And when i choose manual wbalance, there is no "thermometre" adjustment bar available on screen. And is it possible to make iso and shutterspeed manual in videomode? Thanks

**Comment by troop** [comment]
about video profiles:
try to clear appsettings. then the profiles gets reloaded. 
that profile loading happens only on first start, after that it gets loaded from appsettings.

about white balance:
its disabled for it. but dont ask why i forgot it. maybe cause it was not working.

about iso and shutter in video:
when iso and shutter affect the preview it gets normaly applied to the recorded movie too.
when you lower shutterspeed preview should get brighter and laggier.
the redmi note 3 pro is a bit special.
see here
https://github.com/troop/FreeDcam/issues/61

**Comment by semenovnick** [comment]
Thanks, video profiles became normal. White balance - it enough whith existing presets. 

About explosure in preview in menu there is no "user-setting". And cahnge of iso or stutterspeed affects on  result image but not on preview.

**Comment by troop** [comment]
>  And cahnge of iso or stutterspeed affects on result image but not on preview.
then it will not affect videorecording. but thats a problem from the manufactur.
