### ISSUE TITLE
Oneplus X dng raw requested

### ISSUE THREAD

**Issue by ghost** [troop/FreeDcam#122]
Here are my log files and bayer raw files 
I am able to take bayer raws with front and back cameras. Hoping to get dng support

I'm linking the raws and the log
https://drive.google.com/folderview?id=0B43XyPSOcfEHTG9LZnUzanJUSEE

**Comment by defcomk** [comment]
[app-debug.zip](https://github.com/troop/FreeDcam/files/629208/app-debug.zip)
here is a apk with one plus x added

**Comment by DebangshuK** [comment]
Thanks.. Works flawlessly now

**Comment by DebangshuK** [comment]
The front camera takes dng but fails to show or open. The back camera does it perfectly

**Comment by DebangshuK** [comment]
Files from front cam. Interestingly the histogram still shows well https://drive.google.com/folderview?id=0B43XyPSOcfEHeHBtczVrVUVsWlU

**Comment by DebangshuK** [comment]
Also, while trying to use raw2dng for the bayer files of back camera,  the gallery crashes everytime

**Comment by defcomk** [comment]
Not sure why but the front seems to switch between mipi and qcom so i added both 


[app-debug2.zip](https://github.com/troop/FreeDcam/files/629754/app-debug2.zip)

**Comment by DebangshuK** [comment]
Hey! Thanks. Dng from front camera now works too. 
I can capture bayer with front camera too but it never seems to bring a preview in the gallery and shows black.  The files here:
https://drive.google.com/folderview?id=0B43XyPSOcfEHZmN3eGY5YzU2LU0


Also, the raw2dng from the gallery always crashes the app

And thanks again for this magical app

**Comment by DebangshuK** [comment]
Seems like changing shutter speed leads to app crash too
https://drive.google.com/file/d/0B43XyPSOcfEHZW1qSm56OFZqMXM/view?usp=drivesdk

Stock camera supports 1/64000 to 15s shutter speed

**Comment by defcomk** [comment]
hmm add me on telegram @defcomk to debug the shutter

**Comment by troop** [comment]
> Also, the raw2dng from the gallery always crashes the app

when you apply wrong dngsettings an invalid dng file gets created.
when libraw now read that, it could happen that it crash.

> Seems like changing shutter speed leads to app crash too
> https://drive.google.com/file/d/0B43XyPSOcfEHZW1qSm56OFZqMXM/view?usp=drivesdk
> 
> Stock camera supports 1/64000 to 15s shutter speed

dont see that this crash has todo with shutter.

**Comment by DebangshuK** [comment]
Well okay
