### ISSUE TITLE
ASUS_Z00VD (zenfone go) dng request

### ISSUE THREAD

**Issue by age1988** [troop/FreeDcam#123]
Hi,
is it possible to add support for ASUS_Z00VD?
camera parameters :
https://drive.google.com/open?id=0BySknOWR1tKjdGpVVlVPU0t4bWs

and .bayer file :
https://drive.google.com/open?id=0BySknOWR1tKjTkNIUUdhMGdUT1E

**Comment by troop** [comment]
yes looks good

**Comment by age1988** [comment]
Thanks
