### ISSUE TITLE
[FEATURE REQUEST] Manual Focus Peaking Feature

### ISSUE THREAD

**Issue by mohdmujahidansari526** [troop/FreeDcam#124]
Can you enable manual focus peaking feature on your app. As seen in MIUI Default Camera's Manual Mode.

**Comment by troop** [comment]
its added for all 3 apis. over the shutter button you should see 
![quck_set_zebra](https://cloud.githubusercontent.com/assets/377693/21285200/6546dd6a-c432-11e6-9ae9-f439c76e9e5b.png)

if not your device has broken renderscript support

**Comment by mohdmujahidansari526** [comment]
actually this is for exposure peaking not focus peaking.

**Comment by troop** [comment]
Its also for focuspeak. The object gets a yelloow line at sharp edges. If you dont see it increase sharpness

**Comment by mohdmujahidansari526** [comment]
okay i got it, thanks/
