### ISSUE TITLE
Picture Taking failed, What a Terrible Failure!!

### ISSUE THREAD

**Issue by sridher** [troop/FreeDcam#128]
On Redmi note3 changing from **bayer-mipi-10gbrg** to **bayer-mipi-12gbrg** failing to take picture.
![screenshot_2017-01-21-02-04-05-031_troop com freedcam](https://cloud.githubusercontent.com/assets/311444/22164866/133a0d22-df7f-11e6-81ae-ccf21927f722.jpg)

**Comment by troop** [comment]
The sensor is able to capture 12bit raw but the raw stream for it is not active in hal. There is nothing i can do on freedcam side.
