### ISSUE TITLE
Xiaomi MI4 - Magenta tint

### ISSUE THREAD

**Issue by Gresebc** [troop/FreeDcam#129]
When I capture dng is tinted with magenta color.
App version: 3.3.147
Phone: Mi4 with a Samsung S5k3M2 sensor.
For reference: http://en.miui.com/thread-283368-1-1.html
![screenshot_20170121-014347](https://cloud.githubusercontent.com/assets/17913893/22173022/f01c7418-df7b-11e6-895e-98b1b9212e11.png)
[MI 4_CameraParameters.txt](https://github.com/troop/FreeDcam/files/721001/MI.4_CameraParameters.txt)

[2017_01_21_01_42_39.bayer.zip](https://github.com/troop/FreeDcam/files/721002/2017_01_21_01_42_39.bayer.zip)

Thanks and sorry for my english.

**Comment by aggere1** [comment]
Have you tried changing CustomMatrix in settings?  You can try random values, or google or troop might be able to tell you which is specific to Xiaomi M4....

**Comment by Gresebc** [comment]
Seems that is the similar as [issue 71](https://github.com/troop/FreeDcam/issues/71).
Converting the bayer file to dng using GBRG color pattern show right colors.
![2017_01_21_17_28_36](https://cloud.githubusercontent.com/assets/17913893/22178955/941bfe9c-e00a-11e6-9ab0-0b80db03da15.jpg)
https://drive.google.com/file/d/0Bykf1pJ6bW8USUk5MGpPdWIxeEE/view?usp=sharing

**Comment by troop** [comment]
thats a problem from the colorpattern. it looks like that there are two mi4 are out with different sensors, one use a imx135? other the samsung?
the problem is that both use the same model. so when i change it to gbrg others have that problem.

**Comment by Gresebc** [comment]
Then I'm out of luck?
Is possible to add a setting to select the color pattern? Thanks.

**Comment by troop** [comment]
for now, yes you are out of luck. its planned that you can add your own dng profiles like it is for the custom matrixes. but im in the middle of a rework so that has less pritority for me.

**Comment by Gresebc** [comment]
Well, in the mean time I have modified these two files:
[Xiaomi_Mi3_4](https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/cam/apis/camera1/parameters/device/qualcomm/XIAOMI/Xiaomi_Mi3_4.java#L83)
[DngSupportedDevices](https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/dng/DngSupportedDevices.java#L109)
Changing the color pattern, and seems that is working, Did I forget to modify some other file?.
I know that this is a hackish way (I'm not a programmer).

Also, on the front camera when selecting DNG as output file produces a empty file.
Thanks.

**Comment by troop** [comment]
that two files are correct.
that Xiaomi_Mi3_4 contains the dng profiles for freedcam.
DngSupportedDevices is used for the converter inside freedviewer.

to add support for the front cam take a bayer. check the filesize and add it like that:

```
case 16424960:
return new DngProfile(64, 4208, 3120, DngProfile.Mipi, DngProfile.RGGB, DngProfile.ROWSIZE, matrixChooserParameter.GetCustomMatrix(MatrixChooserParameter.IMX135));
```

case 16424960: is the filesize in bytes.
you have to change 4208 and 3120 too to a size that match the front cam.

**Comment by Gresebc** [comment]
Many thanks, now both cameras are working.

Front camera (Sony IMX219):
```
case 9990144:
  switch (device) {
    case XiaomiMI4W:
      return new DngProfile(64, 3264, 2448, DngProfile.Mipi, DngProfile.RGGB, DngProfile.ROWSIZE,matrixChooser.GetCustomMatrix(MatrixChooserParameter.IMX220));
...
```

Rear camera (Samsung S5k3M2):
```
case XiaomiMI4W:
  return new DngProfile(0, 4208, 3120, DngProfile.Mipi, DngProfile.GBRG, DngProfile.ROWSIZE,matrixChooser.GetCustomMatrix(MatrixChooserParameter.OV5648));
...
```

**Comment by troop** [comment]
well its a bayerpattern binary. the decoder does not know how to interpret the colors. for that the dng container is made.
it contains the needed matrixes to tell the decoder how to shift the colors.
libraw identfiy raws like freedcam does, depending on filesize.

**Comment by chinhvinh11** [comment]
same problem. tell me how to fix that
