### ISSUE TITLE
Support exposing device models to an android app resource

### ISSUE THREAD

**Issue by bmintz** [troop/FreeDcam#13]
Currently the supported DNG models are hardcoded in [com.troop.freedcam.DeviceUtils](/troop/FreeDcam/blob/ded0832f0f1688763c4b93d2f627ee48a9512b3c/abstractcamera/src/main/java/com/troop/freedcam/utils/DeviceUtils.java#L9). Please consider supporting an XML resource containing the supported device models. That way, adding supported device model numbers and device models could be done without recompiling.
Furthermore, testing a new device could be done by merely modding an apk _on device_.

Just an idea.

**Comment by troop** [comment]
that wont help much moving hardcoded strings out. it would only help if a device is already added when that model is missing for it. the true detection happens here [troop/androiddng/DngSupportedDevices](https://github.com/troop/FreeDcam/blob/master/androiddng/src/main/java/com/troop/androiddng/DngSupportedDevices.java)

another problem is that some manufactures(LG special) returns not the correct rawsize in the parameters. so it can bigger or smaller. that breaks then the default raw detection added in dcraw. my workaround was to use a custom rowsize in that case.

the current approach seems to me the bestway. each new device is able to capture raw files if its possible on that device. so user can capture raw and save cameraparameters. with that stuff it takes less then 5min to add a new device.

for the colormatrixes it would make sense.
