### ISSUE TITLE
Too warm (yellow) DNG photos on LG G3 D856

### ISSUE THREAD

**Issue by LowSkillGamer** [troop/FreeDcam#130]
I tried to put Custom Matrix: IMX135, No change.

This is usually solved by the white balance. But on some photos I had problems with white balance correction, in photoshop.

![img_2017_01_22_21_30_02](https://cloud.githubusercontent.com/assets/25121341/22185568/ff993478-e0f0-11e6-84a3-89b22c987d12.jpg)
![img_2017_01_22_22_29_29](https://cloud.githubusercontent.com/assets/25121341/22185750/d314dc60-e0f3-11e6-8d10-e6e3e48c48f2.jpg)
![img_2017_01_22_22_30_17](https://cloud.githubusercontent.com/assets/25121341/22185751/d3152b02-e0f3-11e6-87a1-1b6ad65ec39c.jpg)

**Comment by troop** [comment]
you can create custom matrix set.
https://github.com/troop/FreeDcam#how-to-create-a-custom-matrix
then you can adjust the wb as you want

**Comment by LowSkillGamer** [comment]
I do not have the possibility to print or buy Colorchecker Passport.
Use the monitor is a bad idea?

**Comment by troop** [comment]
Colorsmatrixes are ok. You dont need the passport. Just load your dng into the dngprofileeditor adjust wb and apply it to the dng. Then you can use that neutral matrix

**Comment by LowSkillGamer** [comment]
Thank you.
