### ISSUE TITLE
Crashes on exit, Nexus 6p

### ISSUE THREAD

**Issue by teeramusic** [troop/FreeDcam#131]
Crashes on exit, Nexus 6p

**Comment by teeramusic** [comment]
Here are the logs...

[Nexus 6P_2016-12-17_10.12.00.txt](https://github.com/troop/FreeDcam/files/729562/Nexus.6P_2016-12-17_10.12.00.txt)
[Nexus 6P_2016-12-17_10.12.31.txt](https://github.com/troop/FreeDcam/files/729563/Nexus.6P_2016-12-17_10.12.31.txt)
[Nexus 6P_2016-12-17_11.12.16.txt](https://github.com/troop/FreeDcam/files/729565/Nexus.6P_2016-12-17_11.12.16.txt)
[Nexus 6P_2016-12-10_10.44.13.txt](https://github.com/troop/FreeDcam/files/729564/Nexus.6P_2016-12-10_10.44.13.txt)
[Nexus 6P_2016-12-14_09.14.12.txt](https://github.com/troop/FreeDcam/files/729566/Nexus.6P_2016-12-14_09.14.12.txt)

**Comment by teeramusic** [comment]
Oh, also sometimes it crashes after I leave the custom profile page.

**Comment by troop** [comment]
im in the middle of a rework for some parts. maybe its gone when im done with it.
