### ISSUE TITLE
Videos don't have correct frame rates

### ISSUE THREAD

**Issue by teeramusic** [troop/FreeDcam#132]
When I play back the videos, the frame rate is not what I set ( 30 ) in VLC media information it shows something different. In Davinci Resolve 12, it doesn't play back properly at all (probably becuase of the frame rate problem?)

**Comment by mohdmujahidansari526** [comment]
Agreed. M also facing the same issue.

**Comment by troop** [comment]
dont know my g4 and nexus5 does what they should. 30fps is the default and should work.
in what conditions was it recorded? lowlight, sun? on lowlight frames can drop.
would be good to have that file you are talking about. 15sec are enough

**Comment by teeramusic** [comment]
https://drive.google.com/open?id=0B8aHBxJ1KixnTWs1cGQzV18tYW8

They should both be 30.

I set the shutter speed manually on both to 1/100.

**Comment by troop** [comment]
Video: MPEG4 Video (H264) 3840x2160 25.88fps [VideoHandle]
Audio: AAC 48000Hz mono 156Kbps [SoundHandle]
video itself plays smooth. but the sound does not match.
so you used the manuals while recording. pls try same without manuals and use ae.
g4 drops frames too with manual. but with ae it can record up to 60fps.
normal the framerate gets set to 1/30 when recording with ae. it could be that internal something goes wrong when using faster shutter speed then 1/30 and the best matching fps to record gets set.

**Comment by teeramusic** [comment]
To be fair, the video trans-codes perfectly when I handbrake it, but the sound comes out choppy (which is mostly fine for me because I use a separate recorder)

I've tried AE lock with the same results. I also tried changing to HE_AAC, changing audio bit-rate, changing audio sampling rate, and disabling audio recording all together... all with the same results.

I tried opening the same files with MPC-HC, the same files show up as 30fps.

**Comment by defcomk** [comment]
Which Device are you using?

**Comment by teeramusic** [comment]
Nexus 6P, Android 7.1.1

**Comment by teeramusic** [comment]
If I open it up in MPC-HC, it shows the correct frame rate.

**Comment by arifn82** [comment]
hello  freedcam dev.
please, help me to record  60fps videos perfectly on my msm8916 chipset's device. previously i contacted with you, but, still facing the same problem. the app showing that its recording 60fps videos while on recording screen live, but, after recording, when i play the video, its frame rate is only 30fps. plz, how to fix  this?

**Comment by troop** [comment]
Check it with mpc. Some phones dont recognize recorded 60fps movies and tell its 30fps.
Other dont record 30fps but add to metadata 60fps.

**Comment by arifn82** [comment]
@troop , i already checked with MPC x64 . but NO.  the video's  Frame rate mode                : Variable
Frame rate                     : 29.643 FPS
Minimum frame rate             : 10.074 FPS
Maximum frame rate             : 31.447 FPS  please please,  fow to fix this ?
