### ISSUE TITLE
Crashes on startup (git build)

### ISSUE THREAD

**Issue by Bitti09** [troop/FreeDcam#135]
Freedcam build from commit 49e912f267601db17f8d09e26ac413169248370c crashes on startup in api1 mode and shows no pic  on api2 mode

Device : Xiaomi Redmi Note 3 SD
Miui 7.1.19
Log
02-05 15:22:50.552   481 23302 I QCameraParameters: Requested picture size 4608 x 3456
02-05 15:22:50.552   481 23302 I QCameraParameters: int32_t qcamera::QCameraParameters::setZslMode(const qcamera::QCameraParameters&): enabled: 0
02-05 15:22:50.552   481 23302 E QCameraParameters: int32_t qcamera::QCameraParameters::setMorphoHDR(const qcamera::QCameraParameters&), ++
02-05 15:22:50.552   481 23302 E QCameraParameters: int32_t qcamera::QCameraParameters::setMorphoHHT(const qcamera::QCameraParameters&), ++
02-05 15:22:50.552   481 23302 D QCameraParameters: int32_t qcamera::QCameraParameters::setReFocus(const qcamera::QCameraParameters&): AF Bracketing is not supported
02-05 15:22:50.552   481 23302 E QCameraParameters: str_val (null)
02-05 15:22:50.553 23262 23262 D AndroidRuntime: Shutting down VM
02-05 15:22:50.553 23262 23262 E AndroidRuntime: FATAL EXCEPTION: main
02-05 15:22:50.553 23262 23262 E AndroidRuntime: Process: troop.com.freedcam, PID: 23262
02-05 15:22:50.553 23262 23262 E AndroidRuntime: java.lang.RuntimeException: setParameters failed
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.hardware.Camera.native_setParameters(Native Method)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.hardware.Camera.setParameters(Camera.java:1972)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.camera1.CameraHolder.SetCameraParameters(CameraHolder.java:140)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.camera1.parameters.ParametersHandler.SetParametersToCamera(ParametersHandler.java:115)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.camera1.parameters.modes.PreviewSizeParameter.SetValue(PreviewSizeParameter.java:53)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.camera1.Camera1Fragment$1.onParameterValueChanged(Camera1Fragment.java:250)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.camera1.Camera1Fragment.onModuleChanged(Camera1Fragment.java:381)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at freed.cam.apis.basecamera.modules.ModuleHandlerAbstract$2.run(ModuleHandlerAbstract.java:207)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5441)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
02-05 15:22:50.553 23262 23262 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by troop** [comment]
did the feature detector run the first time?looks like a cmd. if not clear the appcache and start freedcam again.
