### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by toutoumu** [troop/FreeDcam#136]
02-07 11:38:10.287 11736-11736/troop.com.freedcam I/Timeline: Timeline: Activity_launch_request id:troop.com.freedcam time:31616963
02-07 11:38:10.567 11736-11750/troop.com.freedcam W/art: Suspending all threads took: 43.761ms
02-07 11:38:10.567 11736-11755/troop.com.freedcam I/art: Background sticky concurrent mark sweep GC freed 7188(366KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 3MB/3MB, paused 1.511ms total 106.155ms
02-07 11:38:10.567 11736-11736/troop.com.freedcam D/ActivityAbstract: createHandlers()
02-07 11:38:10.757 11736-11736/troop.com.freedcam D/ActivityFreeDcamMain: createHandlers()
02-07 11:38:10.767 11736-11736/troop.com.freedcam D/ActivityFreeDcamMain: onResume()
02-07 11:38:10.767 11736-11736/troop.com.freedcam D/ActivityFreeDcamMain: onResumeTasks()
02-07 11:38:10.767 11736-11736/troop.com.freedcam D/ActivityFreeDcamMain: loading cameraWrapper
02-07 11:38:10.767 11736-11736/troop.com.freedcam D/ActivityFreeDcamMain: loaded cameraWrapper
02-07 11:38:10.837 11736-11736/troop.com.freedcam D/FocuspeakProcessorApi2: Ctor
02-07 11:38:10.847 11736-11736/troop.com.freedcam D/Camera2Fragment: Constructor done
02-07 11:38:10.917 11736-11736/troop.com.freedcam D/CameraUiFragment: failed to set cameraUiWrapper
02-07 11:38:10.917 11736-11736/troop.com.freedcam D/CameraUiFragment: ####################ONCREATEDVIEW####################
02-07 11:38:11.117 11736-11736/troop.com.freedcam D/ShutterButton: Module Changed
02-07 11:38:11.117 11736-11736/troop.com.freedcam D/ShutterButton: Set cameraUiWrapper to ShutterButton
02-07 11:38:11.117 11736-11736/troop.com.freedcam D/GuideHandler: setCameraUiWrapper SetViewG()
02-07 11:38:11.217 11736-11736/troop.com.freedcam D/RotatingSeekbar: setprogres3
02-07 11:38:11.547 11736-11736/troop.com.freedcam D/Camera2Fragment: SurfaceTextureAvailable
02-07 11:38:11.547 11736-11736/troop.com.freedcam D/CameraHolderApi2: Open Camera
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual-cct
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value emboss
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value sketch
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value neon
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value asd
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value backlight
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value flowers
02-07 11:38:11.567 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value AR
02-07 11:38:11.577 11736-11736/troop.com.freedcam I/CameraManager: Using legacy camera HAL.
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual-cct
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value emboss
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value sketch
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value neon
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value asd
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value backlight
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value flowers
02-07 11:38:11.847 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value AR
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value manual-cct
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value emboss
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value sketch
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value neon
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value asd
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value backlight
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value flowers
02-07 11:38:11.867 11736-11736/troop.com.freedcam W/ArrayUtils: Ignoring invalid value AR
02-07 11:38:12.007 11736-11736/troop.com.freedcam D/CameraHolderApi2: Camera open
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.colorCorrection.aberrationMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeAntibandingMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeExposureCompensation
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeLock
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeRegions
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.aeTargetFpsRange
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.afMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.afRegions
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.afTrigger
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.awbLock
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.awbMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.captureIntent
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.effectMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.mode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.sceneMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.control.videoStabilizationMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.flash.mode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.jpeg.gpsLocation
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.jpeg.orientation
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.jpeg.quality
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.jpeg.thumbnailQuality
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.jpeg.thumbnailSize
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.lens.focalLength
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.noiseReduction.mode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.scaler.cropRegion
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.statistics.faceDetectMode
02-07 11:38:12.057 11736-11736/troop.com.freedcam D/ParameterHandlerApi2: android.tonemap.curve
**_02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.parameters.WbHandler$ColorCorrectionModeApi2.GetValue(WbHandler.java:342)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.parameters.WbHandler$WhiteBalanceApi2.<init>(WbHandler.java:123)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.parameters.WbHandler.<init>(WbHandler.java:52)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.parameters.ParameterHandlerApi2.Init(ParameterHandlerApi2.java:103)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.Camera2Fragment.onCameraOpen(Camera2Fragment.java:130)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at freed.cam.apis.camera2.CameraHolderApi2$2$1.run(CameraHolderApi2.java:415)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at android.os.Looper.loop(Looper.java:135)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-07 11:38:12.067 11736-11736/troop.com.freedcam W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
02-07 11:38:12.077 11736-11736/troop.com.freedcam D/AndroidRuntime: Shutting down VM
02-07 11:38:12.077 11736-11736/troop.com.freedcam E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: troop.com.freedcam, PID: 11736_**
                                                                   ```
 **java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                        at freed.utils.StringFloatArray.<init>(StringFloatArray.java:28)
                                                                        at freed.cam.apis.camera2.parameters.AeHandler$ManualExposureApi2.<init>(AeHandler.java:133)
                                                                        at freed.cam.apis.camera2.parameters.AeHandler.<init>(AeHandler.java:59)
                                                                        at freed.cam.apis.camera2.parameters.ParameterHandlerApi2.Init(ParameterHandlerApi2.java:110)
                                                                        at freed.cam.apis.camera2.Camera2Fragment.onCameraOpen(Camera2Fragment.java:130)
                                                                        at freed.cam.apis.camera2.CameraHolderApi2$2$1.run(CameraHolderApi2.java:415)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)**
```

**Comment by troop** [comment]
is that from 3.3.147? or build from latest changes?

**Comment by RixSka** [comment]
Got same error from latest changes. 3.3.147 works fine. Moto G 2015 (osprey).

**Comment by defcomk** [comment]
Seems to open Camera 2 AFAIK Moto G3 is a HAL1 only device

**Comment by RixSka** [comment]
I replaced the content of the onTaskEnd method (CameraFeatureDetectorActivity.java
) with just "startFreedcam();" (a little dirty I guess), and it works fine. So, I guess the problem is that during features detection it try to load camera2 api anyway even if it's a camera1 api only device (after properly load camera1 features).

**Comment by troop** [comment]
depending on [that](https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/cam/featuredetector/Camera2FeatureDetectorTask.java#L61) line its a limited device.
so some stuff should work with camera2.
can you attach the logoutput from the feature detector?

**Comment by ilmich** [comment]
Same on my oneplus one (that is camera 1 hal but with legacy camera 2).
Maybe the problem is that on https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/cam/featuredetector/Camera2FeatureDetectorTask.java#L116 code set ManualExposure but only if device is not legacy.
Then when this code is executed https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/cam/apis/camera2/parameters/AeHandler.java#L132 this line trows an exception.

**Comment by troop** [comment]
that referenced commit should fix it
 cf2dfda

**Comment by troop** [comment]
makes not much sense that it jumps through the check.

> 02-13 21:47:51.882 15771 15771 D CameraFeatureDetectorActivity: Check camera features:0
> 02-13 21:47:51.899 15771 15771 D CameraFeatureDetectorActivity: IsCamera2 Full Device:false isFront:false
> 02-13 21:47:51.910 15771 15771 D CameraFeatureDetectorActivity: ###################
> 02-13 21:47:51.922 15771 15771 D CameraFeatureDetectorActivity: #####CameraID:1####
> 02-13 21:47:51.933 15771 15771 D CameraFeatureDetectorActivity: ###################
> 02-13 21:47:51.949 15771 15771 D CameraFeatureDetectorActivity: Check camera features:1
> 02-13 21:47:51.961 15771 15771 D CameraFeatureDetectorActivity: IsCamera2 Full Device:false isFront:true

as fact it gets detected as legacy device and should not step into camera2 featuredetection

**Comment by toutoumu** [comment]
之前使用的 huawei p9 会出现上面这个bug, 今天更新了最新版本后,没有这个异常了
