### ISSUE TITLE
Xiaomi mi 4s shutter grayed out

### ISSUE THREAD

**Issue by rahimbekzoda97** [troop/FreeDcam#138]
Hello, can you please add that device also?
And is it possible to adjust exposure time?

**Comment by troop** [comment]
in theory yes. attach pls the camera parameters and a bayersample file

**Comment by rahimbekzoda97** [comment]
[MI 4S_CameraParameters.txt](https://github.com/troop/FreeDcam/files/772783/MI.4S_CameraParameters.txt)

**Comment by troop** [comment]
more than 0,6sec seems not possible by default with that device, without modding the libs.
but thats nothing i will do.

**Comment by rahimbekzoda97** [comment]
Thank you very much.

**Comment by rahimbekzoda97** [comment]
So what I will do, install new app?

**Comment by troop** [comment]
Latest release should work for your device in case of exposuretime. You did not attach a bayersample, so i expect you dont want dng support.

**Comment by rahimbekzoda97** [comment]
No no, I just don't know how to get Bayer samples

**Comment by troop** [comment]
in camerui select the picture format and choose bayer instead of jpeg. file gets then save in the freedcam folder

**Comment by rahimbekzoda97** [comment]
OK. I'll send it now

**Comment by rahimbekzoda97** [comment]
Bayer samples: https://yadi.sk/d/osR93Ban3E6zPx

**Comment by rahimbekzoda97** [comment]
When there will be an update?

**Comment by troop** [comment]
im in the middle of a rework. its done when its done

**Comment by rahimbekzoda97** [comment]
Troop, when update will be ready, where we can get it?

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases

**Comment by rahimbekzoda97** [comment]
Bro, is it ready?

**Comment by rahimbekzoda97** [comment]
Thanks man

**Comment by rahimbekzoda97** [comment]
Troop, in new update, is there will be shutter speed control?

**Comment by troop** [comment]
for jpeg it should work, and for dng we will see. but i expect that it get ignored on raw capture. qcom made some changes to the new hal that avoid it.

**Comment by rahimbekzoda97** [comment]
Hope it works

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/releases/tag/4.1_alpha5

**Comment by rahimbekzoda97** [comment]
Troop, app is not opening

**Comment by troop** [comment]
Clear appdata and cache from freedcam

**Comment by rahimbekzoda97** [comment]
I did, I cleared app data, cash - there wasn't any cash. Nothing changed

**Comment by rahimbekzoda97** [comment]
Reinstallation also didn't solved the problem

**Comment by rahimbekzoda97** [comment]
Troop, what to do? It's not opening

**Comment by troop** [comment]
dont know dont have that device. on all my devices freedcam starts

**Comment by rahimbekzoda97** [comment]
You said, to clean cash and app data. Maybe I did something wrong? From where I must clean them?

**Comment by troop** [comment]
Open settings from your phone. Click on apps. Select freedcam. Click on data. Clear cache.

Now go to permissions and grant all bevor you start it

**Comment by rahimbekzoda97** [comment]
Did that, nothing changed

**Comment by rahimbekzoda97** [comment]
Man, maybe you can change some logs? I want use that app

**Comment by troop** [comment]
maybe you provide logs?

**Comment by rahimbekzoda97** [comment]
How?

**Comment by troop** [comment]
Look into dcim/freedcam/log.txt

**Comment by rahimbekzoda97** [comment]
[log.txt](https://github.com/troop/FreeDcam/files/841756/log.txt)

**Comment by rahimbekzoda97** [comment]
Troop, anything wrong with logs?

**Comment by rahimbekzoda97** [comment]
Troop, I just installed beta version 16. Its working but I cannot control shutter speed anymore. It's written: auto

**Comment by rahimbekzoda97** [comment]
I'll send you log file.

**Comment by rahimbekzoda97** [comment]
[log.txt](https://github.com/troop/FreeDcam/files/846585/log.txt)

**Comment by AnEx0777** [comment]
What should I do with redmi 3s??? Should I send log???

**Comment by AnEx0777** [comment]
[log.txt](https://github.com/troop/FreeDcam/files/857501/log.txt)

**Comment by troop** [comment]
Alpha 17 should fix it. If not i dont know whats going wrong

**Comment by rahimbekzoda97** [comment]
Hello troop. Now I can set maximum on 0.6 seconds. Again

**Comment by rahimbekzoda97** [comment]
[log.txt](https://github.com/troop/FreeDcam/files/858028/log.txt)

**Comment by troop** [comment]
so problem is fixed and this can get closed. bevor you ask, no your device dont support more then 0,6sec

**Comment by rahimbekzoda97** [comment]
Ok. Thanks

**Comment by rahimbekzoda97** [comment]
But why on the begining you said that it is possible?

**Comment by troop** [comment]
I wrote that:

more than 0,6sec seems not possible by default with that device, without modding the libs.
but thats nothing i will do.

I wrote that i dont do it. Thats nothing i will do.
