### ISSUE TITLE
Video Recording isn't working on LG G3 D856

### ISSUE THREAD

**Issue by LowSkillGamer** [troop/FreeDcam#139]
Не работает видеозапись на LG G3 D856. Не 720p, не 1080p, вообще не в каком формате не работает.
При нажатии на кнопку записи пишет "Start recording failed".
P.S
Стоит google play версия, удалял данные и даже переустанавливал. Запись видео не работает.

Es funktioniert nicht das Video auf dem LG G3 D856. Nicht 720p nicht 1080p, gar nicht in welchem Format funktioniert nicht.
Wenn Sie die Aufnahmetaste drücken, sagt "Aufnahme starten fehlgeschlagen".
P.S
Worth-Play-Version von Google, Daten löschen und sogar neu installiert. Video-Aufnahme funktioniert nicht.

**Comment by rahimbekzoda97** [comment]
Пишите на английском. Разработчик не поймет русский

**Comment by LowSkillGamer** [comment]
Okay. Before running, i put manually memory access, etc. 
And i put recording to external, video recording is working, but only in 1080 and below. LG G3 support record in 4K. I put 2160p, but video recording in 1080p.

**Comment by troop** [comment]
my g3(d855) runs on stock mm and 4k works with latest release.

**Comment by LowSkillGamer** [comment]
[https://youtu.be/KJmloqtZDzg](url)


![232](https://cloud.githubusercontent.com/assets/25121341/24253348/c444df5e-0fe8-11e7-8564-0c7d9167aadd.png)

**Comment by LowSkillGamer** [comment]
And if i enable "Digital image stabilization". The recording does not work AT ALL.

**Comment by troop** [comment]
Digital IMAGE stablization... The key is image.

**Comment by LowSkillGamer** [comment]
Hmmmm... https://youtu.be/JmEQ0N8oTrI
Can the problem in the firmware? I have Fulmics ROM 6.9
