### ISSUE TITLE
Broken Camera2Api support and Manual Shutter speed on Redmi 3S Prime

### ISSUE THREAD

**Issue by mohdmujahidansari526** [troop/FreeDcam#141]
Hello on the latest alpha build the manual shutter speed and Camera2API support is broken, there's no option to enable camera2api even if it's enabled via Build.prop.
Kindly look into the matter.

**Comment by troop** [comment]
you rested appdata from freedcam and the featuredetctor did run?

**Comment by mohdmujahidansari526** [comment]
Yeah tried resetting the app data after enabling Camera2Api

**Comment by troop** [comment]
cam2 get correct detected on my p9 and nex5. dont see that there is a problem

**Comment by mohdmujahidansari526** [comment]
Then maybe this problem must b device or cam sensor specific.

**Comment by mohdmujahidansari526** [comment]
On the latest Alpha17.
Manual Shutter speed option is now unlocked and working but manual ISO isn't working properly. Its getting to some random value irrespective to the value I select.

**Comment by troop** [comment]
Check if left iso is set to auto. Could also be that its not supported by your device also when the parameters says its supported.

**Comment by mohdmujahidansari526** [comment]
Manual ISO is working when selecting Manual ISO from left panel.
By the way, still camera2api support is broken on Redmi 3S/Prime

**Comment by troop** [comment]
That left iso is to limit ae. Looks like it is not supported. Going to disable it. 

About camera2 i have feedback that it works. 

About hfr no more have a qcom based device. Last time i had access to a lg g3 it worked and i made no changes to it. Feel free to fix it. I cant and wont do it.

**Comment by mohdmujahidansari526** [comment]
alright... thanks.
