### ISSUE TITLE
Support for Xiaomi Redmi 4 Pro

### ISSUE THREAD

**Issue by mrzorgman** [troop/FreeDcam#143]
Hello. 
Can you add support of DNG for Xiaomi redmi 4 pro? 
Camera parameters, bayer sample and *.so lib file (if you need it) uploaded here: https://drive.google.com/open?id=0B1BXfreSlpoRb0dFWV96WW5EQzA
Thank you!

**Comment by troop** [comment]
I Look into it the next days.
