### ISSUE TITLE
No manual iso and shutter speed support on Xperia Z3

### ISSUE THREAD

**Issue by dslul** [troop/FreeDcam#144]
These two settings are definitely supported (I can set them using a modified sony stock camera app).
These are more or less the same strings found in the decompiled apk of the aformentioned app:
https://github.com/troop/FreeDcam/blob/6d26bc3bf00b87237846fb61dca45a5fbdb8b107/Camera1Parameters/sony%20cam%20extension.txt

**Comment by troop** [comment]
When the parameters does not contain  
 if (parameters.get("sony-max-shutter-speed") != null) { 
Then it gets set as not supported.
Best is to attach the cameraparameters from your phone.
 It could also be that this key is hidden then stuff must get hardcoded.

**Comment by dslul** [comment]
I attached the camera parameters from your app
[D6603_CameraParameters.txt](https://github.com/troop/FreeDcam/files/840698/D6603_CameraParameters.txt)

Tell me if there is something more specific that I can do

**Comment by troop** [comment]
No thx params are enough. That parameter for shutter and iso are not listed and the device must get hardcoded to use them. Will add it the next days

**Comment by dslul** [comment]
@troop the correct iso values (from what I see from the stock app modified) are 50 -> 3200 and the value doubles (50-100-200-400-800-1600-3200). Is it possible to set in the xml a x2 multiplier?

**Comment by troop** [comment]
Looks like it use fix values.
I mean with it, that in case of exposuretime, it must get set as string like 1/1000. And for iso the same.
That explains why shutter not works because the wrongvalues get set and dont match with the lookuptable

**Comment by alvarorc97** [comment]
Hello, shutter speed doesn't work on my Xperia M5. On my old xperia m4 it worked well, will you fix it?

**Comment by troop** [comment]
@alvarorc97 open a new issue that two devices use different socs

**Comment by dslul** [comment]
I tested it, but the iso selector still doesn't show up. As a result, when I select the shutter speed the app crashes because it can't find the current iso value set.
I also tried to do this, just to see if shutter speed is working:
```
parameters.set("sony-ae-mode", "manual");
parameters.set(cameraUiWrapper.GetAppSettingsManager().manualIso.getKEY(), stringvalues[currentInt]);
```
But nothing changes in the pictures when I select different shutter speeds, so maybe the values to set are different, for example those huge numbers instead of 0,1, 2 etc..
I'm going to try something and see if it works.

**Comment by troop** [comment]
hm iso could be a problem from the featuredector.
that line checks if its presetted. that means if its not hardcoded due the xml.
https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/cam/featuredetector/Camera1FeatureDetectorTask.java#L305

and that loads the hardcoded stuff from the xml.
https://github.com/troop/FreeDcam/blob/master/app/src/main/java/freed/utils/AppSettingsManager.java#L854

maybe shutter must get set as 1-13. wich is a bit odd.
but try to change these values to 1-13
https://github.com/troop/FreeDcam/blob/master/app/src/main/res/values/shutter_values.xml#L581

**Comment by dslul** [comment]
I inspected the stock code, the values are set from 0 to 13. I tried then to manually set two values from the shutter settings (iso still doesn't show up after data reset):

```
public void SetValue(int valueToSet)
    {
        currentInt = valueToSet;

        parameters.set("sony-ae-mode", "manual");
        parameters.set("sony-iso", "100");
            parameters.set("sony-shutter-speed", "12");

        ((ParametersHandler) cameraUiWrapper.GetParameterHandler()).SetParametersToCamera(parameters);
    }
```

This should give me a very low light picture (as I tried on the stock app), but instead it still automatically sets the values. Is it possible that these values are overwritten?

**Comment by troop** [comment]
iso gets also set from 1-xxx

```
public void SetValue(int valueToSet)
    {
        currentInt = valueToSet;

        parameters.set("sony-ae-mode", "manual");
        parameters.set("sony-iso",  cameraUiWrapper.GetParameterHandler().manualIso.GetValue()+1;
            parameters.set("sony-shutter-speed", valueToSet +1);

        ((ParametersHandler) cameraUiWrapper.GetParameterHandler()).SetParametersToCamera(parameters);
    }
```
that +1 is needed because 0 = auto.
it could also be that first the sony-ae-mode must get applied bevor it accept shutter and iso

```
 parameters.set("sony-ae-mode", "manual");
 ((ParametersHandler) cameraUiWrapper.GetParameterHandler()).SetParametersToCamera(parameters);
```
and then set 
```
parameters.set("sony-shutter-speed", "12");
((ParametersHandler) cameraUiWrapper.GetParameterHandler()).SetParametersToCamera(parameters);
```

**Comment by dslul** [comment]
Still nothing. Maybe their HAL makes additional checks to make sure that only their app uses these parameters...

**Comment by troop** [comment]
That could be too. Moto use a framework flag and mtk too. That happens normaly bevor opening the camera or use a custom constructor. Everything could be so easy when oems dont make such things.

**Comment by troop** [comment]
When you want send me the stock app.
Troop@email.de

**Comment by dslul** [comment]
Both are working good now, thank you!

**Comment by AnEx0777** [comment]
What can i do for redmi 3s
