### ISSUE TITLE
Xiaomi Redmi Pro & FreeDCam

### ISSUE THREAD

**Issue by stah007** [troop/FreeDcam#145]
Very much the program was pleasant! Phone Xiaomi Redmi Pro,will be realized in the program FreeDcam compatibility of the Xiaomi Redmi Pro model, at installation a half of settings doesn't work for Xiaomi Redmi Pro. Video doesn't work, at inclusion the black screen and after a while the inscription "FreeDcam Error"
Xiaomi Redmi Pro camera Sony IMX258 Exmor R 13MP http://phonexpert.ru/413/sony-imx258-exmor-r-13mp.html 
firmware Miuisu v6.0 omega 7.3.9.

VIDEO ERROR
![screenshot_2017-03-13-20-24-12-688_com miui bugreport](https://cloud.githubusercontent.com/assets/26393498/23877232/ff850ba8-0849-11e7-9f8b-274640bba748.png)
![screenshot_2017-03-13-20-24-32-392_com miui bugreport](https://cloud.githubusercontent.com/assets/26393498/23877237/04f8153a-084a-11e7-94f7-2f60969ab47b.png)

**Comment by troop** [comment]
Thats new that it crash when audiosource gets set.
Need full log to figure out what fails. Dont have such a device

**Comment by stah007** [comment]
From where to take the full log? Where he is stored?

**Comment by stah007** [comment]
log FreeDCam+3.3.147 
[log.txt](https://github.com/troop/FreeDcam/files/841630/log.txt)
[Redmi Pro_CameraParameters.txt](https://github.com/troop/FreeDcam/files/841631/Redmi.Pro_CameraParameters.txt)

**Comment by vbf999** [comment]
Dear, troop, I have same device and same problems. Please add support for our device to this programm. 
Now I use version FreeDCam 4.1_alpha12
For this version was installed 3.3.147
In bought versions are problems:
-cant save photo in dng .Can only bayer and jpeg
-cant record video whith any parametrs
-very slaw picture on display, when iso is 100
-not support api2 camera (but, i think, it no important)

It is very good for really working manual focus and exposition, but , really it will best whith DNG, and working Vide

**Comment by vbf999** [comment]
Soory, cant upload file.bayer its to large
There is file from this devece https://yadi.sk/d/_JzbguZt3FuHP9
 p.s. sorry for my english, hope you all understand

**Comment by vbf999** [comment]
Troop, thank you for release, dng works whith out any problems. But still dont work video. Can you help whith it? After I try to record video, app crashed and I must to reboot device, becourse camera dont works in any application

**Comment by stah007** [comment]
Whether will be realized compatibility of Xiaomi Redmi Pro phone in the program FreeDcam?
