### ISSUE TITLE
Xperia M5 Shutter Speed Not Working

### ISSUE THREAD

**Issue by alvarorc97** [troop/FreeDcam#147]
Hello, the shutter speed is not working on Xperia m5. Is it possible to fix it?

**Comment by troop** [comment]
with that less informations no

**Comment by alvarorc97** [comment]
What do you need?

**Comment by troop** [comment]
a good point to start are the cameraparameters.

**Comment by alvarorc97** [comment]
What parameters?
ISO goes from 100 to 3200 but i don't know anything abut shutter speed. Manual focus works on the app.

**Comment by troop** [comment]
Pls Check your system libs if it contains lib_cameraextension.so

**Comment by alvarorc97** [comment]
I can't find this file.

**Comment by alvarorc97** [comment]
[E5603_CameraParameters.txt](https://github.com/troop/FreeDcam/files/887581/E5603_CameraParameters.txt)
Finally found it!
