### ISSUE TITLE
OnePlus One broken raw capture

### ISSUE THREAD

**Issue by ilmich** [troop/FreeDcam#155]
Hi Troop,

finally I've some time to build dng_sdk on linux in order to test why dng capture is broken on FreeDcam for my phone.
I'm using OnePlusOne + LineageOs + Freedcam alpha16.
Raw format is bayer-mipi-10rggb and the dng_validate output is the following
`
*** Warning: IFD 0 DateTime is not a valid date/time ***
*** Warning: Chained IFD is not valid ***
*** Error: Matrix math error ***
*** Error: CameraCalibration1 is not invertable ***
Validating "IMG_2017_03_21_07_50_31.dng"...

Uses little-endian byte order
Magic number = 42

IFD 0: Offset = 16424860, Entries = 36

NewSubFileType: Main Image
ImageWidth: 4212
ImageLength: 3120
BitsPerSample: 10
Compression: Uncompressed
PhotometricInterpretation: CFA
ImageDescription: ""
Make: "OnePlus"
Model: "A0001"
StripOffsets: Offset = 1180
Orientation: 1 - 0th row is top, 0th column is left
SamplesPerPixel: 1
StripByteCounts: Count = 16423680
PlanarConfiguration: 1
Software: "FreeDcam 2016"
*DateTime: "2017_03_21_07_50_31"
CFARepeatPatternDim: Rows = 2, Cols = 2
CFAPattern:
    Red      Green
    Green    Blue
ExifIFD: 1070
DNGVersion: 1.3.0.0
DNGBackwardVersion: 1.1.0.0
UniqueCameraModel: "FREEDCAM"
BlackLevelRepeatDim: Rows = 2, Cols = 2
BlackLevel:
       64.00    64.00
       64.00    64.00
WhiteLevel: 1023
ColorMatrix1:
      1.1407  -0.4022  -0.2340
     -0.4314   1.4040   0.0146
     -0.0439   0.2047   0.5704
ColorMatrix2:
      0.7228  -0.0893  -0.0975
     -0.4792   1.3481   0.1381
     -0.1137   0.2680   0.5604
CameraCalibration1:
      1.0000  -1.0000  -1.0000
     -1.0000   1.0000   1.0000
     -1.0000   1.0000   1.0000
CameraCalibration2:
      1.0000  -1.0000  -1.0000
     -1.0000   1.0000   1.0000
     -1.0000   1.0000   1.0000
AsShotNeutral: 0.5391 1.0000 0.6641
CalibrationIlluminant1: Standard light A
CalibrationIlluminant2: D65
ForwardMatrix1:
      0.6328   0.0469   0.2813
      0.1641   0.7578   0.0781
     -0.0469  -0.6406   1.5078
ForwardMatrix2:
      0.7578   0.0859   0.1172
      0.2734   0.8281  -0.1016
      0.0156  -0.2813   1.0859
OpcodeList2: count = 96372, offset = 16425892
NoiseProfile:
  Planes: 3
  Noise function for plane 0: scale = 0.00051471, offset = 0.00000000
  Noise function for plane 1: scale = 0.00051471, offset = 0.00000000
  Noise function for plane 2: scale = 0.00051471, offset = 0.00000000
NextIFD = 924

Exif IFD: Offset = 1070, Entries = 6

ExposureTime: 491.00 sec
FNumber: f/2.00
ISOSpeedRatings: 0
ApertureValue: f/2.00
Flash: 0
    Flash did not fire
FocalLength: 3.8 mm
NextIFD = 0
`
My knowledge of raw format is very limited, I've tryed to build some modification on my device profile, but without success.
How can I help you to try to fix my issue?!

Thanks
Michele

**Comment by troop** [comment]
The problem is the camercalibration matrix with that -1 1 -1 etc. Try to use a custom matrix wich dont have it. I know the g4 matrix dont use it.

The fix is to remove that invalid matrixes

**Comment by ilmich** [comment]
Thanks Troop, now the situation is the following

1) shoot with bayer-mipi-10rggb works well in freedcam viewer but not in android gallery or snapseed
2) shoot with bayer-ideal-qcom-10rggb I think is broken on my phone due to artifacts
3) shoot with bayer-qcom-10rggb works well in freedcam viewer and android gallery and snapseed

for bayer-mipi-10rggb I send dng_validate output as soon as possible.
Another thing.. can you please set default matrix for oneplus one to imx214!? Analyzing raw capture from stockcamera is the best matching matrix (or if you want I can share this matrix in order to add as default)

Thanks
Michele

**Comment by troop** [comment]
that are the added profiles for the opo
https://github.com/troop/FreeDcam/blob/master/app/src/main/res/raw/supported_devices.xml#L1700-L1726
```
<filesize size= "16424960">
            <blacklvl>64</blacklvl>
            <width>4212</width>
            <height>3120</height>
            <rawtype>0</rawtype> // 0 = Mipi = output 10bitdng, 1 = qcom, 2 = Plain = used by mtk, 3 = mipi16 =output 16bit dng, 4 = mipi12
            <colorpattern>rggb</colorpattern>
            <rowsize>5246</rowsize>
            <matrixset>Imx214</matrixset>
        </filesize>
        <filesize size= "16473600">
            <blacklvl>64</blacklvl>
            <width>4224</width>
            <height>3120</height>
            <rawtype>0</rawtype>
            <colorpattern>rggb</colorpattern>
            <rowsize>5280</rowsize>
            <matrixset>Imx214</matrixset>
        </filesize>
        <filesize size= "17522688">
            <blacklvl>64</blacklvl>
            <width>4212</width>
            <height>3120</height>
            <rawtype>1</rawtype>
            <colorpattern>rggb</colorpattern>
            <rowsize>0</rowsize>
            <matrixset>Imx214</matrixset>
</filesize>
```
feel free to make your changes, also you can add the stock matrix to:
https://github.com/troop/FreeDcam/blob/master/app/src/main/res/raw/matrixes.xml
