### ISSUE TITLE
No spot metering

### ISSUE THREAD

**Issue by AnEx0777** [troop/FreeDcam#156]
I cant see any sport metering pointer. And brust mode icon and hdr icon are removed. In latest alfa version.

**Comment by AnEx0777** [comment]
And can i request auto select option  for  stacking photos it take too long to sellect all those pictures.

**Comment by mohdmujahidansari526** [comment]
Confirmed.

**Comment by AnEx0777** [comment]
What?

**Comment by mohdmujahidansari526** [comment]
The bugs you mentioned. I'm confirming them.

**Comment by AnEx0777** [comment]
Ok.
