### ISSUE TITLE
Manual focus is not working for Red mi 2 prime!

### ISSUE THREAD

**Issue by praticks** [troop/FreeDcam#161]
I am using Red mi 2 prime, which featuring a rich 4.7″ 720p IPS display with a modest 312 PPI, a quad-core Qualcomm Snapdragon 410 64-bit processor clocked at 1.4ghz and  8 mega pixel camera.
Every thing works excep manual focus. What can i do so that manual focus works.
Thanks.

**Comment by praticks** [comment]
https://drive.google.com/file/d/0B222EQRs_hWrcFpEc2l5YXl2M1k/view?usp=drivesdk
Here is necessary files related to app and device thanks.

**Comment by troop** [comment]
dont know what @defcomk added already.

**Comment by praticks** [comment]
Yes, he tried to fixed , but not working at all, even raw capturing is also not working, i think raw capturing is not supported by my device but manual focus is supported , i tried a different cam app and manual focus is working in that app, freedcam app is my favorite , i just want manual focus thats all thanks.
