### ISSUE TITLE
Support for Xiaomi Mi5s

### ISSUE THREAD

**Issue by fulger06** [troop/FreeDcam#162]
Hello,

At the last update 4.1alha18 manual control can not be activated.
I chose at CustomMatrix my sensor IMX378 but when I close the application tis value is reset to  off.
At API, I have only camera1 and playmemories.

Preview photos work very slow or not

**Comment by troop** [comment]
You reseted the appsettings? Raw capture dont works with manuals. Hal is messed up on that device. 
Dont understand what you mean with preview capture

**Comment by fulger06** [comment]
Hello,

I will not open another post and write here.
* I tray a new version Alha19 and in this version (As well as the previous Alpha18) I can not be transposed into manual mode when I swipe from down in up.
* I dont have camera 2, JPEG quality, NightOverlay, Camera control:SCENE_MODE, Digital imagi stabilisation, Tonemap, Pixel Corection
*I have CostomMatrix IMX378

In version 3.3.147- release everything I wrote above is present less CostomMatrix IMX378 and manual mode work fine. 
*Here I have a problem when I set custom white balance manual because the screen make flickering yellow or  change in tone yellow. It is very hard to make correct WB. Possibly because this application is not ready for IMX378. 
*Manual shutter speed maxim is 1/3s but in stock camera I have 32s

I hope can you solved this bugs
Thankyou
Best regards

**Comment by troop** [comment]
> I tray a new version Alha19 and in this version (As well as the previous Alpha18) I can not be transposed into manual mode when I swipe from down in up.

need log, no more have a camera1 qcom based device

> I dont have camera 2, JPEG quality, NightOverlay, Camera control:SCENE_MODE, Digital imagi stabilisation, Tonemap, Pixel Corection

works on my nexus5 and p9, as written already more times. oems have their reasons why they did not enable camera2 for such devices. most problems are that such devices cant handel more streams with different format and size.

> Calculation distance focus: Wrong, display infinitely for the three values
> *I have CostomMatrix IMX378

its up if the focusdistance is calibrated. if not it shows random values returned by the cam.

> *Here I have a problem when I set custom white balance manual because the screen make flickering yellow or change in tone yellow. It is very hard to make correct WB. Possibly because this application is not ready for IMX378.

looks like its the next messed up thing by your device
