### ISSUE TITLE
Multiples crashes and missing funcitions Moto g 3 

### ISSUE THREAD

**Issue by bestgustavo30** [troop/FreeDcam#163]
I have tried the app en a Moto g 3 and all fine only a bug with the timestamp of all the photos
now in a moto g 3 turbo, the app of the play store simply dont run and no generate the log file or config file
I downloaded the 4.1_alpha18 and the app run with multiple crashes and missing features

The log file
[log.txt](https://github.com/troop/FreeDcam/files/918059/log.txt)

Config
[MotoG3-TE_CameraParameters.txt](https://github.com/troop/FreeDcam/files/918064/MotoG3-TE_CameraParameters.txt)

.dng Parameters
[dngprofiles.txt](https://github.com/troop/FreeDcam/files/918092/dngprofiles.txt)

Images (maybe broken)
.jpg
![img_2017_04_12_17_42_55](https://cloud.githubusercontent.com/assets/3170940/24982727/9d948d08-1fa8-11e7-864f-a430298d946c.jpg)
.bayer
https://drive.google.com/file/d/0B4_fvjAie--1a0p1bno5VHR1Yk0/view?usp=sharing
.dng
(empty)
https://drive.google.com/file/d/0B4_fvjAie--1MUt4VXotYWtDMkk/view?usp=sharing

**Comment by troop** [comment]
How freedcam acts is correct from the parameters returned from cam. Moto g3 has that parameters hidden. On 3.3.137 stuff was hardcoded. 
And about timestamp. On jpeg its added to exif from cam. Some oems change the timestamp after a capture in their app. 
Dont know when i find the time and motivation to readd that messed up device
