### ISSUE TITLE
Meizu M2 Magenta tint (dng, bayer, color table)

### ISSUE THREAD

**Issue by ankolt** [troop/FreeDcam#165]
Meizu M2 (not m2 note) magenta tint. I try to use other matrixes (default Nexus6, shooting was I add in this issues I take with this matrix) but temperature and tint is incorrect. in rawtodng color pattern is grbg, other patterns are incorrect. please, fix this little problem. I take photo with color table. 
files on dropbox: https://www.dropbox.com/sh/xflyitybz8hvd97/AAARpErHswgvpPLvts9PNMMda?dl=0

**Comment by troop** [comment]
you have the ability now to change and save the dng profile inside raw to dng. or change the the dng_profiles.xml inside DCIM/FreeDcam/config
there you can also change the used matrix

**Comment by ankolt** [comment]
Meizu M2 based on MTK, not Qualcomm. 
I know about dng_profiles.xml, but all matrixes are magenta tint (now I can set matrix to imx_298_qualcomm. colors are green tint)
On macbook i don't have software for create custom matrix. I have DNGProfile editor and photoshop with camera raw, but I don't read metadata after color correction. (All soft in App Store what I try are didn't read metadata)
Files (bayer, dng, jpg) with imx298 matrix (color table and photo with sky and clouds): https://www.dropbox.com/sh/0utbqdqv8joqiac/AADwzmJDyWzewa4JPGnbfOIha?dl=0
![s70420-174454](https://cloud.githubusercontent.com/assets/16436708/25238761/e96313d6-25f6-11e7-99aa-ca216f5772f4.jpg)
![s70420-180238](https://cloud.githubusercontent.com/assets/16436708/25238759/e8f3b414-25f6-11e7-97a7-bb872fdf9e2c.jpg)
![s70420-180254](https://cloud.githubusercontent.com/assets/16436708/25238760/e8f89754-25f6-11e7-8f4a-4086c445b7eb.jpg)

**Comment by ankolt** [comment]
Update!
Temperature is correct when I use imx298 matrix, but tint set default to -95 (more green), correct tint -60 on meizu m2. are you create new matrix with this fix.

**Comment by troop** [comment]
with that colorchart taken from a monitor its not possible to create a good matrix.
DNG profile editor is all you need to create the matrix. for meta reading i use exiftool.
