### ISSUE TITLE
Focus lock (for Galaxy S5)

### ISSUE THREAD

**Issue by raduprv** [troop/FreeDcam#167]
First, thanks for this great app, it's the only free one that can turn the denoise off on my S5, which is usually the reason why I shoot RAW when I can. With denoise off, the JPGs are great, so no need for RAW.

Anyway, I was wondering if you can implement a "Focus lock" option. It would be very useful for time lapse photos. Open Camera supports this, so I guess it is technically possible. It would help a lot on phones without manual focus support, since you can select the right distance by focusing on objects at known distances, then lock the focus.

**Comment by troop** [comment]
Choose as focusmode auto or macro. 
Then touch to focus. After that the focus is locked until you touch again or close the app

**Comment by raduprv** [comment]
Oh, it works, but only when the flash is off (or on Auto and not starting). This is why I thought it wasn't working, because I needed the flash always on.

**Comment by troop** [comment]
set flash to torch and it should work

**Comment by raduprv** [comment]
Thank you very much, it works fine now :)
Maybe in future releases you could add a focus lock button near the AE lock, it would make things more intuitive for people new to the application.
