### ISSUE TITLE
Support for LeTv x900

### ISSUE THREAD

**Issue by shri1** [troop/FreeDcam#170]
Great application, a lot of functions that not supported by custom camera, thanks author for job.
From Q&A I found answer for my Q: Why can't i open raw/bayer files?
In [https://mega.nz/#!81cHmQqA!l2mlZKbjJrFyJQVoOrt4Br1MXG08FRff15w4YXAIhHg](url) i attach bayer file, my phone camera [http://www.devicespecifications.com/en/model/2c1933a0](url)
[X900+_CameraParameters.txt](https://github.com/troop/FreeDcam/files/990374/X900._CameraParameters.txt)

**Comment by troop** [comment]
next build will have dng capture

**Comment by shri1** [comment]
sounds greate

**Comment by shri1** [comment]
Last ver. 4.1 alfa Not support byaer image- saved file may could be corrupted (in Photo mate or FreeDcam viewer), the previous ver. file saved, but with wrong coulor

**Comment by troop** [comment]
Open dcim/freedcam look for log.txt delete it. 
Clear app data from freedcam (phonesettings/apps/freedcam). Start freedcam attach log here

**Comment by shri1** [comment]
Thanks a lot, it's working!!!! The color not wrong 
 I choosed before on left menu (last icon) bayer, but I  have to enable RDI!!!
By the way, after reopen it's disabled.
I will test other functions and report about it
