### ISSUE TITLE
Xiaomi MI4 - Magenta tint 

### ISSUE THREAD

**Issue by chinhvinh11** [troop/FreeDcam#171]
When I capture dng is tinted with purple color
Phone: Mi4W with a Samsung S5k3M2 sensor.
bayerfile: [https://drive.google.com/open?id=0B3qtlQfDyPsJaW9kQy01SzZzLUk](url)
log file: [https://drive.google.com/open?id=0B3qtlQfDyPsJb0U0U2UxX1M5OFk](url)
dng file : [https://drive.google.com/open?id=0B3qtlQfDyPsJUGtmWVlEYnh0ZGs](url)
Could you please help me to fix this? Thanks

**Comment by troop** [comment]
Its a problem from mi4 itself. There it seems to be out same device with different sensor. The alphas have the ability to overwrite the colorpattern wich fix your problem. Alpha20 will crash for you

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/issues/129
