### ISSUE TITLE
Xiaomi redmiPro problem

### ISSUE THREAD

**Issue by vbf999** [troop/FreeDcam#173]
Dear, troop, hello. Im allready have writeen to you in another issue, but is no answer. 
You fix problem whith dng and thank you very much, but two things is not working....
First video, I cant record it, in any update...whith any parameters
Second is dng, is works almoust good only in alpha 17 version, but capture of dng is strange, maybe I do something wrong, on jpeg and dng files are not same picture, their different... not colour, or brightness etc, there captured in differet time...
What can I send for fix it? log file or something else.
Sorry for english

**Comment by troop** [comment]
>  Im allready have writeen to you in another issue, but is no answer.

had nothing todo with your device. so ignored...

> First video, I cant record it, in any update...whith any parameters

dont have that device. but it works on my good old o3d, evo3d, nexus5(cam1/cam2), p9(cam1/cam2) and
nexus7

> not colour, or brightness etc, there captured in differet time...

latest xiaomi devices trigger ae always and ignore manual settings. thats not a problem from freedcam but from xiaomis camera implementation

**Comment by vbf999** [comment]
First video, I cant record it, in any update...whith any parameters

dont have that device. but it works on my good old o3d, evo3d, nexus5(cam1/cam2), p9(cam1/cam2) and
nexus7
Sorry, troop, I understand, that on some divices it works, but there is  next situation on mine:
I press button to reccord video, and as result application crashed, or device hangs, and is no way to start application next time. I must delete app and install it again. Or, in another way app no crash but after press button stop record, video file is no played by device or anything else. 
Can you help whith it?

**Comment by troop** [comment]
attach the log.else i have no idea what cause it
