### ISSUE TITLE
2160@60 fps need

### ISSUE THREAD

**Issue by hjk75** [troop/FreeDcam#175]
Hello I download " FreeDCAM-debug+146v .apk " on 4PDA.ru -> Xiaomi Mi5s forum. I dont know exactly version

It is only one camera with really 1080@60 video recording on Mi5s. It is possible fix options for 2160@60 fps ? When I try start record with 2160 & Highspeed or Normal mode - camera crached 
((2160+timelaps is work

Thanks!

**Comment by troop** [comment]
Hello.
4k with 60fps is not possible due hardware limit. possible are max 30fps.
without log no idea whats crashing it. could be that the bitrate is to much.

**Comment by hjk75** [comment]
[MI 5s_2017-05-25_09.21.15.txt](https://github.com/troop/FreeDcam/files/1028030/MI.5s_2017-05-25_09.21.15.txt)

**Comment by hjk75** [comment]
I try differet bitrate and small and big - any way craching

**Comment by troop** [comment]
java.lang.IllegalArgumentException: Surface size 3840x2160 is not part of the high speed supported size list [480x360, 1280x720, 1920x1080, 176x144, 640x480, 720x480, 640x360, 320x240, 1280x960, 480x320, 800x480, 864x480, 352x288]

highspeed capture on camera2 only allows/support it up to 1280x720.

timelapse record always! without audio. also timelapse is not made for high framerates > 30fps.
when it works with it its good, but it shouldnt. also that movie is not recorded with 60fps. meta says its 60 but mpc says its 30fps.
![unbenannt-1](https://cloud.githubusercontent.com/assets/377693/26439256/a85f48d6-4127-11e7-96ba-d4e66ae23454.jpg)

at current state there is no device out wich can record 4k@60fps

**Comment by hjk75** [comment]
ok, thank you. It means - is no smartphone on the market with 2160@60 support? (and new on 835 Snap too? HTC U11?

**Comment by troop** [comment]
Dont know if htc u11 support it. I dont have that phone. 

Its not a problem from android. More a problem from the hardware, driver and sdcard write speed. 

Thats up to the oem. With recording at fullsize frames must get smallered or cropped wich takes more ressources and can end in framedrops. 
With only actvating the needed pixel that can get avoided. 
But you can try on your own. Use a tripod take one pic at fullsize. Then record some seconds, extract a frame and overlay both. Then you should see how its cropped

**Comment by hjk75** [comment]
>More a problem from the hardware, driver and sdcard write speed.

- My Mi5s have USF 2.1 RAM - it is writing ~ 130Megabyte per sec. (as SDD for PS) - in 10 times more that 2160p60 need. And CPU SnDr 821 I think is enough for 2160p60. I dont understand why OEM not realize 60 fps mode
- I checked already - standard Mi5s camera and FreeDCam use cropped for video (only center). Now I understude - its depends from OEM frimware

**Comment by defcomk** [comment]
U11 has no 4K 60 even tho both Sensor and SOC support it 
tried OC'ing Moto G5+ but when crossing 4K 40fps it starts dropping fps.

I suppose on mi5s its possible to force 4k60 by disabling all the other res configs then Overclocking the timings but defining stream as 30fps this trick seems to work on most devices getting more fps without triggering hfr mode

**Comment by hjk75** [comment]
> defcomk. I suppose on mi5s its possible to force 4k60 
- I'm user without deep knolage. How I can got 4k60? 
- And also FreeDCam on Mi5s have problem with compentation 50-60Hz of blinking of lamps (on video) - do you know how fix this?
