### ISSUE TITLE
Xiaomi dng files ignore manuals

### ISSUE THREAD

**Issue by Smallchopper48** [troop/FreeDcam#178]
so, from what i read, new xiaomi phone manual control won't work in dng raw?

**Comment by troop** [comment]
https://github.com/troop/FreeDcam/issues/176

https://github.com/troop/FreeDcam/issues/61

thats correct

**Comment by Smallchopper48** [comment]
there's no way to fix it? because i really need that.. thank you

**Comment by troop** [comment]
there is most time a way to fix it. but it ends with playing with the camera libs and hexcode.
