### ISSUE TITLE
Bayer Raw.

### ISSUE THREAD

**Issue by Smallchopper48** [troop/FreeDcam#181]
ok, so in xiaomi, capturing in dng will ignore manual. what about bayer raw?

i ask this because i don't know much about bayer raw, sorry
what software to edit bayer raw? or atleast convert to dng

im sorry if this question is stupid

**Comment by troop** [comment]
Q Why can't i open raw/bayer files?
A Because its the pure data. the decoder cant read it because it does not know how to open it.
To tell the decoder how the data is stored, the dng container is needed.
In that case send us the raw/bayer file and it will work soon.
