### ISSUE TITLE
xiaomi mi4s recording problem

### ISSUE THREAD

**Issue by rahimbekzoda97** [troop/FreeDcam#183]
Hello troop, the app cannot recorda video on 1080 and 2k, except 720. Can you please solve this problem on next update

**Comment by troop** [comment]
i dont have such a device. recording works on all my devices. no log no problem
log is stored in dcim/freedcam/log.txt

**Comment by rahimbekzoda97** [comment]
You want me to send logs?

**Comment by troop** [comment]
Yes... As said, dont have that device.
