### ISSUE TITLE
Support for LeTv x900 #170

### ISSUE THREAD

**Issue by shri1** [troop/FreeDcam#188]
My FreeDcam crashed after 3 week using without any problem, Yesterday I shoot 4k movie, all was ok. But, then i go back to picture mode in dng format, i see, that all files had 0 byte size, I recover application from Titanium, no changing, I delete cash, date, stop app, delete it and reinstall. Now i have black screen, when running app, but can see setup without right panel. During trying app. my phone hungs for long time, i can't switch it off for 5 min, at last i can reboot it, try app againg, the same result, near my log file
[log.txt](https://github.com/troop/FreeDcam/files/1111669/log.txt)
P.S.: Before sending this message i check app, and, amazing, it's working.
In any case, please check my log, i have to be sure, if it was app bug? Very, very strange behaviour

**Comment by troop** [comment]
sounds for me that the camerademon died. log contains nothing interessting.

normaly screen stays in that case black and shows on start ERROR:code
only way to get it back working is to reboot the phone and clear freedcam appsettings bevor you launch it again. that could happen due a special set of parameters. like setting tnr with wavelet at same time

**Comment by shri1** [comment]
thank you for reply, i will test it few days and close case, really i try, seems to me, denoise setting

**Comment by shri1** [comment]
I have some questions about video: 1 from menu it's not possible to choose 4096p profile, it not fixed on first line of menu, but i can create it, it works, but 720p disapiered,   also, +/- frame per sec, not working in + scale, but changed in - scale with no effect.
Any suggestion ?
