### ISSUE TITLE
Xiaomi Redmi Note 4X - Pink/Magenta tint when shot raw

### ISSUE THREAD

**Issue by suryol** [troop/FreeDcam#190]
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
- Describe your Problem as good as possible.

Phone Model:
---------------
Xiaomi Redmi Note 4X [Snapdragon]

FreeDcam Version:
-----------------
4.1 alpha23

Problem Description:
--------------------
this phone actually have 3 sensor. sony, samsung, and -my phone sensor- omnivision. when i shot raw at camera api 1 or 2 the result have a magenta tint/pink like who the one have mi4 gave this issue. try different custom matrix not work.

[log.txt](https://github.com/troop/FreeDcam/files/1123503/log.txt)

**Comment by troop** [comment]
Freedcam identify colorpattern depending on build model and filesize of the raw.
The problem on the redmi 4 is. All devic3s has the same buildmodel and filesize but use different colorpatterns. Due that its not possible for freedcam to use the correct pattern.

Look into internalsd/dcim/freedcam/config
There should be a dngprofiles.xml.
Change there the color pattern. 
When its grbg and its pink change it to rggb. 
When its has now switched red and blue channel change it  to bggr. And so on... Great work xiaomi 😆

**Comment by suryol** [comment]
try to change the grbg-rggb-bggr the result still pink and wow wtf xiaomi

**Comment by troop** [comment]
make sure you removed freedcam from ram. press the square on your phone and remove freedcam and viewer.
appsettings loads that file only onetime when freedcam gets loaded and is not in memory.
an alternativ is to use the viewer and rawtodng. there you see direct the changes and can save the dngprofile, but you must capture bevor and bayer file.

**Comment by troop** [comment]
<filesize size= "16510976">
            <blacklvl>64</blacklvl>
            <width>4208</width>
            <height>3136</height>
            <rawtype>0</rawtype>
            <colorpattern>grbg</colorpattern>
            <rowsize>0</rowsize>
            <matrixset>Nexus6</matrixset>
        </filesize>
thats the profile that works for me

**Comment by suryol** [comment]
try it, but the problem still. i try to take bayer shot but the freedviewer can't show it, just blank, rawtodng give me forceclose with that file. 

i tried another cam app that shot dng like lightroom and l camera, but the output dng always purple-ish. maybe the omnivision sensor is the culprit.

**Comment by troop** [comment]
best is to upload that bayer to gdrive or send it per mail. then i can look into it.

**Comment by suryol** [comment]
https://drive.google.com/file/d/0B0Vyxj8c_BRmUWcxa0dncGRlODQ/view?usp=sharing

rn4x- ov - bayer file

**Comment by troop** [comment]
```
<filesize size= "16560128"> <!-- redmin note4x omnivision -->
            <blacklvl>64</blacklvl>
            <width>4224</width>
            <height>3136</height>
            <rawtype>0</rawtype>
            <colorpattern>rggb</colorpattern>
            <rowsize>0</rowsize>
            <matrixset>Nexus6</matrixset>
        </filesize>
```

that works for me. rawtype 0 is mipi10bit in the editor

**Comment by suryol** [comment]
after change the xml then in freeddcam menu 'use freedcam dng converter' change to on right? if yes then the freedcam always force close when taking the dng

**Comment by troop** [comment]
that profile is for cam1. 

on cam2 when activate "use freedcam converter" its use the 16bit raw and drop first 6 emtpy bits to reduce filesize. and also you can use a different matrix with. but the raw width,height,colorpattern, etc... gets returned from the cameras metadata.
when it crash on cam2 with on or off, means that something wrong with the pure 16bit stream returned or with the metadata.
in that case i need the log to see what goes wrong

**Comment by q8** [comment]
Hello, 

If you want I can make a new thread but I have the same phone and a similar issue.
I have a redmi note 4(x) with the only sensor that's not in the "xiaomi_redmi_note_4" device name : the samsung S5K3L8 sensor. I'm using the latest alpha build of freedcam.
I tried using the S5K3L8_qualcomm profile (same sensor apparently) but it doesn't change anything, neither does Rggb or Bggr color settings in the xml config file. 

Freedcam viewer displays much worse results than google drive DNG viewer, or lightroom. But colors are still really washed off. Is it normal or not ?

Pictures are here (jpg VS dng) : https://drive.google.com/drive/folders/0B4ntSFpm11NNV01iaU84SW1TVU0?usp=sharing

I tried also to use freedcam converter in the app but it crashes. So i've included my log file in the google drive.

Tell me if you need more info, 
Thanks !

**Comment by suryol** [comment]
my camera 1 just can take jpeg and bayer, while using the config u gave, the bayer file give blank pic. in camera 2 use converter or no with the configs,the dng still bit purple. here the log.
[log (1).txt](https://github.com/troop/FreeDcam/files/1129879/log.1.txt)

not a pink guy but pink pict,lel
![edbfd958-9490-4038-9d43-dbd8759e44ec](https://user-images.githubusercontent.com/26336376/27941669-f6b8a32e-62fb-11e7-8b9d-02f4bd1f635b.jpg)

**Comment by troop** [comment]
@q8 
> I have a redmi note 4(x) with the only sensor that's not in the "xiaomi_redmi_note_4" device name : the samsung S5K3L8 sensor. I'm using the latest alpha build of freedcam.

i wrote:
> Freedcam identify colorpattern depending on build model and filesize of the raw.
> The problem on the redmi 4 is. All devic3s has the same buildmodel and filesize but use different colorpatterns. Due that its not possible for freedcam to use the correct pattern.

the color channels are switched. red is blue, blue is red. change the pattern.

@suryol 
on cam2 xiaomi forgot to set black lvl to 64. thats why the raw has a red cast.
as already said more times. oems have their reasons why they dont activate cam2.
but that can fixed too with the freedcam converter.
you need to know the filesize in bytes. wich is in your case  26492928 bytes.
then you have to adjust the rest. raw type for cam2 is plain = 2;

**Comment by suryol** [comment]
@troop, force close while shot using the turned on freedcam dng converter, else while, the dng pink again.
[log (2).txt](https://github.com/troop/FreeDcam/files/1130453/log.2.txt)

**Comment by q8** [comment]
@troop 

Yes, i know that the device name is the same for every sensor, but I think my matrix is wrong.
My dngprofiles.xml file tells me my <matrixset> is "IMX135_Z5S_JB" , but I have a "samsung S5K3L8" sensor, not a "Sony IMX135" sensor. So changing the blue/red channels won't help since it's not the right <matrixset>, right ?

**Comment by troop** [comment]
@q8 
freedviewer use a linear matrix, its not gamma2.2 boosted like psx or other apps use.
so raw images shown in freedviewer will always look darker/less contrast then in other apps.
in same folder as dngprofiles.xml is the matrixes.xml
the matrix set contains S5K3L8_Qualcomm, use that.


@suryol 
set correct width and height. plain raw have same size as max jpeg
```
<filesize size= "26492928"> <!-- redmi note4x omnivision cam2-->
            <blacklvl>64</blacklvl>
            <width>4160</width>
            <height>3120</height>
            <rawtype>2</rawtype>
            <colorpattern>rggb</colorpattern>
            <rowsize>0</rowsize>
            <matrixset>Nexus6</matrixset>
        </filesize>
```

**Comment by suryol** [comment]
the problem still, did i do it wrong? its very confusing.
[log (3).txt](https://github.com/troop/FreeDcam/files/1130922/log.3.txt)

**Comment by q8** [comment]
@troop okay thanks i'll look into it !

**Comment by suryol** [comment]
@troop, aaaah stupid me, i got the right color when convert it manual using raw2dng tool in freedcam viewer. btw, the converted dng file is 300++MB? is that normal?

**Comment by troop** [comment]
300mb? Well that will crash it for sure with outofmemory and it wont be viewable. For a 15mp sensor raw size is around 30mb with 16bit.

**Comment by suryol** [comment]
@troop, eventually ma phone can see it via freedcam viewer or snapseed editor. but, when export the edited photo the snapseed crash, cant handle 300mb+ i think

**Comment by troop** [comment]
snapseed says always unsupported file when opening it from freedviewer.
snapseed seems only to like it when it gets attached as shared.
dont know how you acchieved a 300mb dng, but it contains for sure data trash.

**Comment by suryol** [comment]
@troop, can it be fixed?
