### ISSUE TITLE
Huawei P9 can not run

### ISSUE THREAD

**Issue by toutoumu** [troop/FreeDcam#192]
Phone Model:

Huawei P9

FreeDcam Version:

4.1alpha23

Problem Description:

Huawei P9 can not run

Log

D:04.00.19:ActivityAbstract:initOnCreate()
D:04.00.19:AppSettingsManager:Version/Build:4.1alpha23/125 Last Version: 125
D:04.00.19:AppSettingsManager:Lookup ConfigFile
D:04.00.19:XmlParserWriter:Found 124 Devices in Xml
D:04.00.20:ActivityFreeDcamMain:LoadFreeDcamDCIMDirsFiles()
D:04.00.20:ActivityFreeDcamMain:onResume()
D:04.00.20:ActivityFreeDcamMain:onResumeTasks()
D:04.00.20:ActivityFreeDcamMain:cameraPermission Granted:true
D:04.00.20:ActivityFreeDcamMain:loading cameraWrapper
D:04.00.20:ActivityFreeDcamMain:loaded cameraWrapper
D:04.00.20:Camera1Fragment:FrameWork:0 openlegacy:true
D:04.00.20:Camera1Fragment:create Legacy camera
D:04.00.20:Camera1Fragment:initModules
D:04.00.20:cam.ModuleHandler:load default picmodule
D:04.00.20:cam.ModuleHandler:load default videomodule
D:04.00.20:cam.ModuleHandler:load hdr module
D:04.00.20:Camera1Fragment:Check Focuspeak
D:04.00.20:FocusPeakProcessorAp1:Ctor
D:04.00.20:FocusPeakProcessorAp1:Preview cleared from:Ctor
D:04.00.20:Camera1Fragment:Ctor done
D:04.00.20:SettingsMenuFragment:SetCameraUiWrapper
D:04.00.20:CameraUiFragment:####################ONCREATEDVIEW####################
D:04.00.20:ShutterButton:Set cameraUiWrapper to ShutterButton
D:04.00.20:GuideHandler:setCameraUiWrapper SetViewG()
D:04.00.20:RotatingSeekbar:setprogres3
D:04.00.20:SettingsMenuFragment:SetCameraUiWrapper
D:04.00.20:Camera1Fragment:surface created
D:04.00.20:CameraHolderLegacy:open camera legacy
D:04.00.20:ScreenSlideFragment:notifyDataHasChanged
E:04.00.20:CameraHolderLegacy:Failed to open Legacy
D:04.00.20:FocusPeakProcessorAp1:SurfaceSizeAvail
D:04.00.20:FocusPeakProcessorAp1:Allocout null or not USAGE_IO_OUTPUT
D:04.00.20:FocusPeakProcessorAp1:reset allocs to :1920x1080
E:04.00.20:CameraHolder:Attempt to invoke virtual method 'void android.hardware.Camera.setPreviewCallbackWithBuffer(android.hardware.Camera$PreviewCallback)' on a null object reference
D:04.00.20:FocusPeakProcessorAp1:script done enabled: false
D:04.00.20:FocusPeakProcessorAp1:Preview cleared from:onSurfaceTextureAvailable
D:04.00.21:FocusPeakProcessorAp1:SurfaceSizeChanged
D:04.00.21:ParametersHandler:Manufactur:HUAWEI
D:04.00.21:ParametersHandler:Model:EVA-AL00
D:04.00.21:ParametersHandler:Product:EVA-AL00
D:04.00.21:ParametersHandler:OS:4.1.18-gf6402d0
D:04.00.21:ParametersHandler:preview-size=1920x1080
D:04.00.21:ParametersHandler:video-size=1920x1080
D:04.00.21:ParametersHandler:preferred-preview-size-for-video=1920x1080
D:04.00.21:ParametersHandler:preview-size-values=1920x1080,1440x1080,1536x864,1280x960,1280x720,960x720,720x720,640x480,736x414,544x408,400x400,352x288,320x240,208x144,176x144
D:04.00.21:ParametersHandler:video-size-values=1920x1080,1440x1080,1536x864,1280x960,1280x720,960x720,720x720,640x480,736x414,544x408,400x400,352x288,320x240,208x144,176x144
D:04.00.21:ParametersHandler:preview-format=yuv420sp
D:04.00.21:ParametersHandler:preview-format-values=yuv420p,yuv420sp
D:04.00.21:ParametersHandler:preview-frame-rate=30
D:04.00.21:ParametersHandler:preview-fps-range=14000,30000
D:04.00.21:ParametersHandler:preview-fps-range-values=(14000,30000),(30000,30000),(14000,20000),(20000,20000),(14000,25000),(25000,25000),(12000,15000),(15000,15000)
D:04.00.21:ParametersHandler:preview-frame-rate-values=30,20,25,15
D:04.00.21:ParametersHandler:picture-size=320x240
D:04.00.21:ParametersHandler:picture-size-values=320x240,640x480,1280x720,1920x1080,3264x1840,3264x2448,3968x2976,2048x1536,2976x2976,3968x2240
D:04.00.21:ParametersHandler:picture-format=jpeg
D:04.00.21:ParametersHandler:picture-format-values=jpeg
D:04.00.21:ParametersHandler:jpeg-thumbnail-width=512
D:04.00.21:ParametersHandler:jpeg-thumbnail-height=384
D:04.00.21:ParametersHandler:jpeg-thumbnail-size-values=0x0,208x208,512x288,480x320,512x384,512x512
D:04.00.21:ParametersHandler:jpeg-thumbnail-quality=70
D:04.00.21:ParametersHandler:jpeg-quality=90
D:04.00.21:ParametersHandler:rotation=0
D:04.00.21:ParametersHandler:whitebalance=auto
D:04.00.21:ParametersHandler:whitebalance-values=auto,incandescent,fluorescent,daylight,cloudy-daylight
D:04.00.21:ParametersHandler:effect=none
D:04.00.21:ParametersHandler:effect-values=none
D:04.00.21:ParametersHandler:antibanding=auto
D:04.00.21:ParametersHandler:antibanding-values=auto,50hz,60hz
D:04.00.21:ParametersHandler:scene-mode=auto
D:04.00.21:ParametersHandler:flash-mode=off
D:04.00.21:ParametersHandler:flash-mode-values=off,auto,on,torch
D:04.00.21:ParametersHandler:focus-mode=auto
D:04.00.21:ParametersHandler:focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture
D:04.00.21:ParametersHandler:max-num-focus-areas=1
D:04.00.21:ParametersHandler:focus-areas=(0,0,0,0,0)
D:04.00.21:ParametersHandler:focal-length=4.5
D:04.00.21:ParametersHandler:horizontal-view-angle=54.1442
D:04.00.21:ParametersHandler:vertical-view-angle=41.3909
D:04.00.21:ParametersHandler:exposure-compensation=0
D:04.00.21:ParametersHandler:max-exposure-compensation=4
D:04.00.21:ParametersHandler:min-exposure-compensation=-4
D:04.00.21:ParametersHandler:exposure-compensation-step=0.5
D:04.00.21:ParametersHandler:auto-exposure-lock=false
D:04.00.21:ParametersHandler:auto-exposure-lock-supported=true
D:04.00.21:ParametersHandler:auto-whitebalance-lock=false
D:04.00.21:ParametersHandler:auto-whitebalance-lock-supported=true
D:04.00.21:ParametersHandler:max-num-metering-areas=1
D:04.00.21:ParametersHandler:metering-areas=(0,0,0,0,0)
D:04.00.21:ParametersHandler:zoom=0
D:04.00.21:ParametersHandler:max-zoom=99
D:04.00.21:ParametersHandler:zoom-ratios=100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,148,151,154,157,160,163,166,169,172,175,178,181,184,187,190,193,196,199,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,303,306,309,312,315,318,321,324,327,330,333,336,339,342,345,348,351,354,357,360,363,366,369,372,375,378,381,384,387,390,393,396,399
D:04.00.21:ParametersHandler:zoom-supported=true
D:04.00.21:ParametersHandler:smooth-zoom-supported=false
D:04.00.21:ParametersHandler:focus-distances=Infinity,Infinity,Infinity
D:04.00.21:ParametersHandler:max-num-detected-faces-hw=10
D:04.00.21:ParametersHandler:max-num-detected-faces-sw=0
D:04.00.21:ParametersHandler:video-frame-format=android-opaque
D:04.00.21:ParametersHandler:recording-hint=false
D:04.00.21:ParametersHandler:video-snapshot-supported=false
D:04.00.21:ParametersHandler:video-stabilization=false
D:04.00.21:ParametersHandler:video-stabilization-supported=true
D:04.00.21:ParametersHandler:iso-mode-values=auto,100,200,400,800,1600
D:04.00.21:ParametersHandler:contrast-values=0,50,100,150,200
D:04.00.21:ParametersHandler:saturation-values=0,50,100,150,200
D:04.00.21:ParametersHandler:brightness-values=0,25,50,75,100
D:04.00.21:ParametersHandler:sharpness-values=auto,+1,+2,+3,+4,+5
D:04.00.21:ParametersHandler:metering-mode-values=average,center-weighted,spot,matrix
D:04.00.21:ParametersHandler:hw-k3-burst-supported=true
D:04.00.21:ParametersHandler:hw_beauty_mode_support=true
D:04.00.21:ParametersHandler:hw-video-beauty-supported=true
D:04.00.21:ParametersHandler:zsl-mode-supported=true
D:04.00.21:ParametersHandler:hw-best-photo=true
D:04.00.21:ParametersHandler:hw-refocus-supported=true
D:04.00.21:ParametersHandler:lcd-compensate-supported-values=off,auto
D:04.00.21:ParametersHandler:hw-magnifier-supported=true
D:04.00.21:ParametersHandler:hw-manual-focus-supported=true
D:04.00.21:ParametersHandler:hw-vcm-start-value=0
D:04.00.21:ParametersHandler:hw-vcm-end-value=1023
D:04.00.21:ParametersHandler:hw-burst-support-count=100
D:04.00.21:ParametersHandler:hw-burst-jpeg-quality=80
D:04.00.21:ParametersHandler:hw-dual-primary-supported=primary,secondary,dual
D:04.00.21:ParametersHandler:scene-mode-values=auto,action,portrait,landscape,night,night-portrait,theatre,beach,snow,fireworks,candlelight,hwauto,hdr,
D:04.00.21:ParametersHandler:hw-smile-face-shotmode-supported=true
D:04.00.21:ParametersHandler:hw-scope-supported=true
D:04.00.21:ParametersHandler:hw-min-beauty-level=0
D:04.00.21:ParametersHandler:hw-max-beauty-level=10
D:04.00.21:ParametersHandler:hw-post-process-supported=true
D:04.00.21:ParametersHandler:hw-image-denoise-supported=true
D:04.00.21:ParametersHandler:target-tracking-supported=true
D:04.00.21:ParametersHandler:hw-big-aperture-supported=true
D:04.00.21:ParametersHandler:hw-supported-aperture-value=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
D:04.00.21:ParametersHandler:hw-mmi-test-feature-supported=AFC DEPTH,AFC PDAF,AFC OIS
D:04.00.21:ParametersHandler:hw-effect-supported=none,zy-fugu,zy-valencia,zy-lianghong,zy-earlybird,zy-xpro2,zy-myfair,mph-huawei_moriyama,mph-huawei_graylevels
D:04.00.21:ParametersHandler:video-callback-supported=true
D:04.00.21:ParametersHandler:high-video-callback-threshold-supported=60
D:04.00.21:ParametersHandler:hw-exposure-mode-values=default,super-night,car,light,water,star
D:04.00.21:ParametersHandler:hw-relayout-mode-values=none,snapshot2preview
D:04.00.21:ParametersHandler:hw-min-exposure-time=1
D:04.00.21:ParametersHandler:hw-max-exposure-time=60
D:04.00.21:ParametersHandler:hw-exposure-compensation-support=true
D:04.00.21:ParametersHandler:hw-exposure-compensation-step=0.100000
D:04.00.21:ParametersHandler:key-supernight-supported-iso=auto,100,200,400,800,1600
D:04.00.21:ParametersHandler:key-supernight-supported-exposure=auto,1/4,1/2,1,2,4,8,12,16,20,24,28,32
D:04.00.21:ParametersHandler:hw-af-mmi-control-supported=true
D:04.00.21:ParametersHandler:hw-af-mmi-far-threashold=6000
D:04.00.21:ParametersHandler:hw-af-mmi-near-threashold=1
D:04.00.21:ParametersHandler:hw-video-fps-supported=120,60
D:04.00.21:ParametersHandler:hw-professional-mode-supported=true
D:04.00.21:ParametersHandler:hw-sensor-exposure-time-range=1/4000,30
D:04.00.21:ParametersHandler:hw-sensor-wb-range=2800,7000
D:04.00.21:ParametersHandler:hw-sensor-iso-range=50,3200
D:04.00.21:ParametersHandler:hw-color-effect-range=(1,32)
D:04.00.21:ParametersHandler:hw-exposure-hint-supported=true
D:04.00.21:ParametersHandler:hw-dynamic-iso-range-supported=true
D:04.00.21:ParametersHandler:hw_video_smooth_af_supported=true
D:04.00.21:ParametersHandler:hw-focus-assist-flash-mode-supported=default,auto,on,off
D:04.00.21:ParametersHandler:hw-supported-color-modes=normal,bright,soft
D:04.00.21:ParametersHandler:hw-dm-watermark-supported=true
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v4.util.LongSparseArray.size()' on a null object reference
	at freed.cam.apis.camera1.parameters.modes.PictureFormatHandler.<init>(PictureFormatHandler.java:53)
	at freed.cam.apis.camera1.parameters.ParametersHandler.initParameters(ParametersHandler.java:163)
	at freed.cam.apis.camera1.parameters.ParametersHandler.LoadParametersFromCamera(ParametersHandler.java:136)
	at freed.cam.apis.camera1.Camera1Fragment.onCameraOpen(Camera1Fragment.java:242)
	at freed.cam.apis.camera1.cameraholder.CameraHolderLegacy.OpenCamera(CameraHolderLegacy.java:62)
	at freed.cam.apis.camera1.Camera1Fragment$2.run(Camera1Fragment.java:158)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by troop** [comment]
cant reproduce the problem on my eva09. try to reset the appsettings and it should work

**Comment by toutoumu** [comment]
问题已经解决 , 清除app数据, 或者重新安装

**Comment by toutoumu** [comment]
Camera1 API can not run
