### ISSUE TITLE
Xiaomi Redmi Note 4 (Snapdragon)

### ISSUE THREAD

**Issue by dobrovolsky** [troop/FreeDcam#193]
Xiaomi Redmi Note 4 (Snapdragon)
---------------
4.1_alpha23
---------------
The smartphone doesn't support raw. In "Picture Format Mode" I don't see raw option.
[Log file](https://gist.github.com/dobrovolsky/db3e0f0d7146fde50888a3f8e6404236)
[Parameters](https://gist.github.com/dobrovolsky/acfe616ae57b1c48056ba330c0e59c23)
[dngprofiles.xml](https://gist.github.com/dobrovolsky/1eb8cbc94c34d341724f69df0ce503b5)

**Comment by troop** [comment]
check alpha 24, on the g3 i had yesterday its working
