### ISSUE TITLE
Median stack doesn't seem to be working

### ISSUE THREAD

**Issue by gigiboeru** [troop/FreeDcam#198]
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
- Describe your Problem as good as possible.

Phone Model:
---------------

Moto G5+

FreeDcam Version:
-----------------

3.3.140

Problem Description:
--------------------

Hi,

Thank you for this great app, I'm not sure if what I'm experiencing is really a bug.

I've been using it just for a few days mainly for the stack functionality but it seems that the median stack barley has an effect on the image. The average 3x3 mode is better, but far from what I've expected - just go give a comparison, with Photoshop if you stack a few images you get a noise free result. If you have about 30 images the result is amazing. I'm unable to have this result in FreeDcam. I know that this median stacking is a very intensive operation but it goes quite fast on my phone so it may be some kind of bug. I can provide you with images if needed. 

Regards, 
G

**Comment by troop** [comment]
hi
yes algos could be better for all stacking modes. but the phone are very limited with the ram usage.
ps itself holds all images in ram wich we cant do. so each image gets read one by one.
for average its like:

(lastPixeld + currentPixel)/2 = newpixel
on other avarage modes the near pixels gets merged too.

median creates normaly an an array for all values and take that one from the middle.
that work progess cant get used on a phone. 
i store only the min/max values from a pixel. and when all images are read the avarage math gets applied.

but it seems that the part wich build image from the min/max pixel somehow missing^^

**Comment by gigiboeru** [comment]
Can it be something like pixel by pixel instead of storing & reading the whole image? 
Like read pixel 1x1 from all images and store all values and then take the median value or do the arithmetic average (for other stack modes); afterwards proceed to pixel 1x2 and so on until the full image is complete. It may be slower but it looks memory friendly and as long as it doesn't crash the app then it's fine.

**Comment by troop** [comment]
i dont think thats is a way to go.
foreach pixel in one image happen then:
-read jpegfile. 
-decompress jpeg to bitmap
-read one pixel

depending on image size and count this is a awesome traffic.
lets say we have a 4208x3120 image and that 10x
4208x3120 = 13.128.960 x10 = 131.289.600
