### ISSUE TITLE
Oneplus3T OIS value shows "off"

### ISSUE THREAD

**Issue by YasiruWickramarathna** [troop/FreeDcam#199]
[log.txt](https://github.com/troop/FreeDcam/files/1182238/log.txt)
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
- Describe your Problem as good as possible.

Phone Model:
---------------
Onelus3T -  OOS 4.1.6

FreeDcam Version:
-----------------
4.1_alpha25

Problem Description:
--------------------

The optical stabilization mode shows only off value. As far as I know OP3T have OIS.

**Comment by troop** [comment]
It could be that it has ois. But it returns only off. The problem is not on freedcam side
