### ISSUE TITLE
Xiaomi MI4C can't save Raw pictures in .dng format

### ISSUE THREAD

**Issue by Doctor-Felix** [troop/FreeDcam#200]
Notes:  
In some Forums people are able to save usefull Raw pictures in dng format using FreeDCam and their Mi4C. I am running the newest teamsuperluminal.org LINEAGEOS 14.1 Rom for my Mi4C, but still can't save them as .dng. The come out as so called "Bayer-files" one can't use... at least I don't know how.

Phone Model: 
MI4C
---------------

FreeDcam Version: 
newest, 4.1_alpha25
-----------------

Problem Description:
 I am running the newest teamsuperluminal.org LINEAGEOS 14.1 Rom for my Mi4C, but still can't save them as .dng. The come out as so called "Bayer-files" one can't use... at least I don't know how.
--------------------

**Comment by Doctor-Felix** [comment]
sorry might be my mistake.... i does work now. is it only available for certain bayer variants?

**Comment by troop** [comment]
from Q&A:

Q Why can't i open raw/bayer files?
A Because its the pure data. the decoder cant read it because it does not know how to open it.
To tell the decoder how the data is stored, the dng container is needed.

normaly only for mipi. qcom bayer produce corrupt raws on some devices.
