### ISSUE TITLE
App crash at startup on MTK device

### ISSUE THREAD

**Issue by MasterPIC** [troop/FreeDcam#24]
Trying to execute 3.3.123 release on my smartphone (powered by MTK6582) the app crashes on startup.
Please let me know how to help to detect what is wrong.

Thanks
Armando

**Comment by defcomk** [comment]
which device ? could you post a crash log 
Create folder named DEBUG inside freedcam dir in DCIM when crash happens it log in a text file

**Comment by MasterPIC** [comment]
Unfortunately there are no debug messages at all...
I think the crash is not related to MTK stuff (I tried by disabling MTK related code...): probably an exception occurs but it's not catched.

**Comment by troop** [comment]
logs gets saved in /sdcard/DCIM/FreeDCam folder. when the DEBUG folder is created inside that folder.

**Comment by MasterPIC** [comment]
I had already given a look at the code and created the required folder to find log messages...
I see no files at all inside the DEBUG folder...

**Comment by troop** [comment]
its outside that folder^^ sorry for confusion. the debug folder is only needed to start logging.
the logs are stored at /sdcard/DCIM/FreeDCam.
also i could be that you must enable devloper settings and choose freedcam as debugging app

**Comment by MasterPIC** [comment]
Also with app-debug.apk I've no debug logging.
As for developer settings are you referring to the developer mode enabled by several clicks on smartphone info panel?

**Comment by troop** [comment]
yep that menu

**Comment by MasterPIC** [comment]
On another smartphone I found an error at startup about "version" or something similar... I don't remember the reported line and I can't check again. :(
Anyway on my smartphone I read no errors at all (so I think it's a different bug) and unfortunately the app simply crashes as soon as executed...

**Comment by defcomk** [comment]
get catlog from playstore run it then press home key run freedcam then open catlog save the current log and upload the resulting .txt file

**Comment by MasterPIC** [comment]
Maybe this line is useful:
12-04 16:37:10.583 W/System.err(20938): java.io.FileNotFoundException: /storage/sdcard0/DCIM/FreeDcam/Forward_Art_2015-12-04 04:37:10.txt: open failed: EINVAL (Invalid argument)

**Comment by MasterPIC** [comment]
Could be related to ':' char inside the filename?

**Comment by MasterPIC** [comment]
Ok, by fixing the invalid char in debug filename I got the expected debug file...
[Forward_Art_2015-12-05 01.21.36.txt](https://github.com/troop/FreeDcam/files/52660/Forward_Art_2015-12-05.01.21.36.txt)

**Comment by MasterPIC** [comment]
If IsLegacy() method catches "simple" exceptions in place of CameraAccessException, InterruptedException, IllegalArgumentException and VerifyError ones then no crash occurs at startup.

**Comment by troop** [comment]
not all exceptions extends Exception. so when only catching Exception some will crash also.
as sample look here https://github.com/troop/FreeDcam/blob/master/camera1/src/main/java/com/troop/freedcam/camera/BaseCameraHolder.java#L81

**Comment by MasterPIC** [comment]
But I see the crash occurs because of the use of exceptions that extend Exception...
I'm not a Java developer. So I'm not able to properly fix the issue.
[Forward_Art_2015-12-05 02.05.04.txt](https://github.com/troop/FreeDcam/files/52846/Forward_Art_2015-12-05.02.05.04.txt)

**Comment by troop** [comment]
VFY: unable to resolve exception class 135 (Landroid/hardware/camera2/CameraAccessException
That seems the problem maybe removing it fix it

**Comment by troop** [comment]
I hope latest commit fix it

**Comment by MasterPIC** [comment]
The issue is fixed.
I also think that catching CameraAccessException in IsLegacy method should be restored. I see it causes no issues...
