### ISSUE TITLE
Rework HDR Function[Feature]

### ISSUE THREAD

**Issue by defcomk** [troop/FreeDcam#41]
Add menu Function
to use scene hdr and auto hdr
display hdr on off auto

**Comment by Ar4erR07** [comment]
Need think. I have this feature in AEB options and it works with morpho-hdr. But how it realese on other devices...

**Comment by defcomk** [comment]
For other devices they use scene mode hdr

so if we abstract on of 

for xiaomi on activate morpho-hdr

for other devices that have scene mode it auto switch to that scene mode

and devices with auto-hdr as auto
