### ISSUE TITLE
Setting not saved, reset each time exit

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#42]
Setting mode to Auto or continuous picture gets reset each time I exit app, needing to redo it everytime.
Also, from camera appears for back and back for front.
Sony z3 compact Open Source camera

**Comment by Ar4erR07** [comment]
xiaomi mi3, can not confirm.

**Comment by defcomk** [comment]
zte nubia z5s
samsung s5 settings stick.

camera switch indicates the cam you switching to

**Comment by troop** [comment]
Need two things.
First a full log from freedcam. Use normal logging tools or create in /DCIM/FreeDCam/DEBUG folder then on next start logs gets saved there.

And i need the cam parameters.

When that happen a parameter fails to load or rrad

**Comment by rancidfrog** [comment]
I see. Camera switch correct then, sorry.


http://hastebin.com/zirebayisa.coffee
For debug, app only started debugging when DEBUG folder created in main storage, even though storage set to external.

Once I exited app when debugging, I was not able to reopen app - black screen. Needed a restart, probably due to camera hanging as Sony OS Camera still in development.

**Comment by troop** [comment]
ah ok thx, i understand the problem. you are on camera2 api. yes its a know bug. but i did not care about yet because when i use cam2 i use always mf^^ will fix it soon.

**Comment by rancidfrog** [comment]
Mf is the button under take picture?
When I click it nothing happens: http://hastebin.com/petipehona.coffee

**Comment by troop** [comment]
update pushed. problems should be fixed
