### ISSUE TITLE
Pictures always saved as landscape

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#45]
When taking pictures the photos are always saved as landscape. All photos taken not landscape needs to be rotated 90 degrees right. App does not take orientation into consideration.

Latest release working much better with z3compact open source drivers.
The button above the take picture button is always off, though.

**Comment by troop** [comment]
Thats correct. Also gps data gets not set. Both is not added yet. And focus peak does not call the event. Its on my todo list

**Comment by rancidfrog** [comment]
Yes,
Was going to mention, camera button takes picture when you release, but focus (half-press camera button) does not.

Great work.

**Comment by troop** [comment]
Yes thats not working because freedcam supports only two auto focus types and never trigger bevor a capture.
But thats on both apis the same behavior.
When i shot moving objects i use cont focus. That makes sure it always refocus and keep the object sharp till the capture happens. 
Touch to focus locks the focus to that point until you touch again.
Thats made this way because on some devices the focus finding is awesome slow and fail often.

**Comment by rancidfrog** [comment]
3.3.131 does not have location selection for saving pictures.
Using M, it worked in 5.1.1 but with M ROM setting does not appear.
And, pictures do not appear to be saving as a result, ( location was external previously, so maybe it does not detect external sdcard)

**Comment by troop** [comment]
that could be. with M the added a new file api thats why its no more acessible with freedcam.
its works also no more with root and that sdfix. with reseting appsettings sdcard gets set back to internal

**Comment by rancidfrog** [comment]
Uninstalled and reinstalled, so now it saves pictures.
But, the maximum picture size can only be set to 1280x960, back camera should be 20.7 MP

**Comment by troop** [comment]
hm thats strange. freedcam returns picsize direct from hal. so when it shows only 1280x960 thats the max size returned. what i can say nexus5 and g4 returns correct sizes,

**Comment by rancidfrog** [comment]
There is only one setting picture size, shouldn't there be two? One for back camera and one for front camera?
It might be just checking front camera?
Strange, because previous version worked

**Comment by troop** [comment]
front and back cam have different settings.
nexus5 back:
![screenshot_20160307-121458](https://cloud.githubusercontent.com/assets/377693/13567900/4da8bdb8-e45e-11e5-8979-39d028ceedbd.png)
nexus5 front
![screenshot_20160307-121714](https://cloud.githubusercontent.com/assets/377693/13567948/947b9bb6-e45e-11e5-9efe-023c6e230a00.png)
:
g4 back
![screenshot_2016-03-07-12-10-23](https://cloud.githubusercontent.com/assets/377693/13567809/cd4fb4b4-e45d-11e5-8359-1ca42c1d78a0.png)

but latest source on master have problems when switching cam.
there the settings gets not updated in ui. they only change it background.
also the screenslide does not show new pics when open inside freedcam.
but on 3.3.132 it should show it normal.

**Comment by troop** [comment]
orientation is now applied
