### ISSUE TITLE
Flash settings, misspelled single

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#49]
Instead of single, as in single flash and not singel, why not just use "on"?
Options would be flash "off", " on", "torch".
 ![http://s12.postimg.org/oggofgmm5/20160324_041812.jpg](http://s12.postimg.org/oggofgmm5/20160324_041812.jpg)

**Comment by troop** [comment]
well its less confusing that way. ae itself contains on_auto_flash. on_always_flash. that is the real part wich enable disable flash.

**Comment by rancidfrog** [comment]
True for single, but when torch selected it is immediately on regardless of AE, even when ae off, is that intended?

**Comment by troop** [comment]
Thats correct. Tourch mode works always. Its the flash api. You can use it outside from a camera app to have bulb/flashlight. But turning it off ae cant use it. That stuff is implemented as camera2 use it. 
Normaly the app should handel that and set it depending on it. 
So flash turned off, ae should get set to auto flash  and flasmode to off

Flash auto then ae auto and flash on. 
Flash off ae auto off. Flashmode off
And so on. I was yet to lazy to handel it.
