### ISSUE TITLE
APK version number wrong?

### ISSUE THREAD

**Issue by IzzySoft** [troop/FreeDcam#51]
Recently, all your `.apk` files have the same internal version:

    package: name='troop.com.freedcam' versionCode='69' versionName='3.3.132'

Could you please take care to have that fixed? Package manager is having issues with that :) Thanks!

**Comment by troop** [comment]
Yes and no. Only that apks with alpha behind has same version. There is one reason. That force people to uninstall and clean install it. Currently its important that cache dir gets cleaned.
When its rdy to get pushed to playstore it gets updated

**Comment by IzzySoft** [comment]
Thanks for the fast response! OK, I wasn't aware it's done on purpose :) So in other terms, one better skips the "pre-releases" unless participating in beta testing?

**Comment by troop** [comment]
normaly it should get stabler with each version. but sometimes it need some rework and then stuff gets broken. normal jpeg capture and raw capture should work as always at current version. only some problems with the viewer are left

**Comment by IzzySoft** [comment]
Understood (incl. the background). So for the "standard user" it's better sto stick with the "green releases" and ignore the "red ones" (pre-releases) unless the changelog suggests one of them solves an issue one has. And the next "green one" will have the version number fine again, right? Thanks!
