### ISSUE TITLE
On Mi4c focusing just does not work properly

### ISSUE THREAD

**Issue by Sinaaaa** [troop/FreeDcam#52]
Hi!

When focusing first the target area sharpens up, but before the focusing process is over it overshoots & blurs it out. (it can go either direction, sometimes if it starts focusing at infinity it will just blur out my far away scene too)

On a side note, a raw+jpeg mode would be nice. Just to have a letterbox sized jpeg that I can check on my phone before editing the raw.

**Comment by troop** [comment]
hi
do you have that on other apps too? on some devices the af routine is not realy good
try to set focus to macro. for me that mode works better then auto.

jpeg+raw is a small problem on qcom socs with camera1. we must take two images. first the dng and then the jpeg.
its no big deal when you shoot landscapes with fast shutter. but when you have moving objects the scene will have changed on second shot. 
a different solution would be to create a jpeg from that raw direct. but that will only waste space.
and the viewer shows it as linear.

**Comment by Sinaaaa** [comment]
It's perfect on other apps, focusing that is.

**Comment by troop** [comment]
fixed with that [commit](https://github.com/troop/FreeDcam/commit/bae85cff7cf4c783667fd81700e4e97c115f2a17)
