### ISSUE TITLE
HDR Exposures Option Bug

### ISSUE THREAD

**Issue by christantoan** [troop/FreeDcam#53]
I'm using OnePlus One. Currently when I'm changing value of HDR Exposures, the number doesn't updated after I press +/- button. A restart is necessary to update it. 
Also sometimes all exposures value is shown as the same value or even HDR exposures are empty needing restart app to fix it. 
BTW, is there any toggle to enable/disable HDR? Because it's not there in my scene mode

Video HDR option is also resetted after every app start

Thanks

**Comment by troop** [comment]
The HDR exposures are wrong called. it must get renamed to bracket Exposures.
in bracket module it takes then 3 pics with different exposure but does not merge them.
the hdr option is only visible with jpeg because its postprocessing and not compatible with raw/dng.

that the +/- values gets reseted confuse me abit. works on my g3/g4 on camera1

**Comment by christantoan** [comment]
Sorry, if I'm not clear enough and wrongly called some settings.

Here is screenshot of bracket exposures doesn't get loaded:
![screenshot_20160419-150352](https://cloud.githubusercontent.com/assets/7300310/14632096/f3e7a9ec-0640-11e6-9b67-9263e0e55673.png)

Here's the screencast of  bracket exposures doesn't get updated in real time:
https://drive.google.com/file/d/0B8rNWAORE6dsVkRIOEk0TmhxZ1k/view?usp=sharing

Here's the screencast of Video HDR option resetted on every app restart:
https://drive.google.com/file/d/0B8rNWAORE6dsY0RwLXNpdzllaUk/view?usp=sharing

Thanks

**Comment by troop** [comment]
crazy stuff with bracket . does timelapse +/- have the same behavior?

video hdr gets turned off in pic module. normaly is should switch to on when you enter the video module and it was set to on. but it must turned of in pic modul else it cause problems

**Comment by christantoan** [comment]
Nope. Timelapse +/- behave normally

**Comment by troop** [comment]
[3.3.133alpha15](https://github.com/troop/FreeDcam/releases/tag/3.3.133alpha15)
pls try that

**Comment by christantoan** [comment]
It doesn't even open my camera properly (front and back). It just showing black viewfinder with all option on the left hand side gone

**Comment by troop** [comment]
check if camera permission is granted. normaly it should ask on appstart

**Comment by christantoan** [comment]
Yes. It's granted

**Comment by troop** [comment]
does other camera apps start?^^ if not the camera demon died and you must restart the phone. 
if other starts pls attach a logcat no idea whats now wrong^^ g3/g4 starts normal

**Comment by christantoan** [comment]
Seems like the camera demon(?) died. Restarting now

**Comment by christantoan** [comment]
After restart, other camera apps work. FreeDcam, however, not
How to get logcat?

**Comment by troop** [comment]
Create on internalsd in /DCIM/FreeDcam/ a DEBUG folder. so path is then /DCIM/FreeDcam/DEBUG/
there then the logs gets saved

**Comment by christantoan** [comment]
Here's the logcat:
[A0001_2016-04-19_09.39.24.txt](https://github.com/troop/FreeDcam/files/226104/A0001_2016-04-19_09.39.24.txt)
