### ISSUE TITLE
Viewer Delete Bug

### ISSUE THREAD

**Issue by christantoan** [troop/FreeDcam#54]
When in reverse landscape mode, the delete confirmation dialog is still displayed in normal reverse

**Comment by troop** [comment]
confirmed, only the camerauifragment gets rotated.  the activity where the dialog is attached to does not rotate. that rotation is more a hacky way. if i would use the defaul orientation by android on each change the camera would get restarted. 
that was added due a user broke his screen and left screen side was nomore touchable.
