### ISSUE TITLE
fc alpha16, Nexus5, Android 6.0.1_r24

### ISSUE THREAD

**Issue by claenn** [troop/FreeDcam#55]
04-23 09:36:53.957 I/art     (815): Background partial concurrent mark sweep GC freed 104018(7MB) AllocSpace objects, 8(2MB) LOS objects, 30% free, 36MB/52MB, paused 1.803ms total 141.608ms
04-23 09:36:57.442 I/art     (815): Background partial concurrent mark sweep GC freed 21487(1373KB) AllocSpace objects, 8(184KB) LOS objects, 30% free, 35MB/51MB, paused 1.731ms total 162.443ms
04-23 09:37:05.449 I/ActivityManager(815): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=troop.com.freedcam/com.troop.freedcam.MainActivity bnds=[378,314][630,425]} from uid 10078 on display 0
04-23 09:37:05.512 I/ActivityManager(815): Start proc 20516:troop.com.freedcam/u0a267 for activity troop.com.freedcam/com.troop.freedcam.MainActivity
04-23 09:37:06.030 D/FileHolder(20516): InternalSDPath:/storage/emulated/0/DCIM/FreeDcam
04-23 09:37:06.109 D/freedcam.LifeCycle(20516): Activity onResume
04-23 09:37:06.132 D/freedcam.MainActivity(20516): loading cameraWrapper
04-23 09:37:06.163 D/freedcam.MainActivity(20516): loaded cameraWrapper
04-23 09:37:06.448 D/freedcam.CameraUiWrapperApi2(20516): Constructor done
04-23 09:37:06.449 D/freedcam.MainActivity(20516): add events
04-23 09:37:06.675 D/freedcam.ParameterHandlerApi2(20516): Set Orientation to:90
04-23 09:37:06.681 W/System.err(20516): 	at com.troop.freedcam.camera2.parameters.ParameterHandlerApi2.SetPictureOrientation(ParameterHandlerApi2.java:181)
04-23 09:37:06.681 W/System.err(20516): 	at com.troop.freedcam.MainActivity.OrientationChanged(MainActivity.java:282)
04-23 09:37:06.681 W/System.err(20516): 	at com.troop.freedcam.ui.menu.OrientationHandler$1.onOrientationChanged(OrientationHandler.java:34)
04-23 09:37:07.424 D/FileHolder(20516): InternalSDPath:/storage/emulated/0/DCIM/FreeDcam
04-23 09:37:07.602 W/WindowManager(815): Force clearing freeze: AppWindowToken{4751404 token=Token{6ec3817 ActivityRecord{9c5e496 u0 troop.com.freedcam/com.troop.freedcam.MainActivity t9895}}}
04-23 09:37:08.443 E/AndroidRuntime(20516): Process: troop.com.freedcam, PID: 20516
04-23 09:37:08.445 W/ActivityManager(815):   Force finishing activity troop.com.freedcam/com.troop.freedcam.MainActivity
04-23 09:37:08.467 I/WindowManager(815): Screen frozen for +2s890ms due to Window{8e80206 u0 troop.com.freedcam/com.troop.freedcam.MainActivity}
04-23 09:37:08.757 I/WindowManager(815): Screenshot max retries 4 of Token{6ec3817 ActivityRecord{9c5e496 u0 troop.com.freedcam/com.troop.freedcam.MainActivity t9895 f}} appWin=Window{8e80206 u0 troop.com.freedcam/com.troop.freedcam.MainActivity} drawState=1
04-23 09:37:09.258 W/ActivityManager(815): Activity pause timeout for ActivityRecord{9c5e496 u0 troop.com.freedcam/com.troop.freedcam.MainActivity t9895 f}
04-23 09:37:09.352 I/art     (20157): Background partial concurrent mark sweep GC freed 45547(3MB) AllocSpace objects, 16(13MB) LOS objects, 26% free, 44MB/60MB, paused 1.377ms total 118.488ms
04-23 09:37:11.877 I/WindowState(815): WIN DEATH: Window{8e80206 u0 troop.com.freedcam/com.troop.freedcam.MainActivity}
04-23 09:37:11.957 I/ActivityManager(815): Process troop.com.freedcam (pid 20516) has died
04-23 09:37:12.926 I/art     (815): Explicit concurrent mark sweep GC freed 59794(4MB) AllocSpace objects, 4(80KB) LOS objects, 30% free, 35MB/51MB, paused 1.469ms total 149.811ms

--
Edit: alpha15 works in landscape. issue starts with alpha16.

**Comment by troop** [comment]
hm thats realy crazy. dont remember that i change stuff on it. nexus5 dont have that problem and g4 also not.

**Comment by claenn** [comment]
What's really weird on this hammerhead ResurrectionRemix v5.6.7

A) deinstalling alpha15 -> clean install alpha 16 -> starting app -> instantaneous crash (as in catlog above)
B) dirty install of alpha16 over alpha15 -> it works 😳. The only difference: after closing the app via the exit button, there's a system popup about a FreeDcam fc.

http://pastebin.ca/3582482

**Comment by troop** [comment]
i changed the loading behavior now. for me that sounds like that there is a problem with emtpy settings.
pls try [alpha17](https://github.com/troop/FreeDcam/releases/tag/3.3.133alpha17)

**Comment by claenn** [comment]
Okay. Alpha18 did it.
Closing issue.
