### ISSUE TITLE
3.3.133alpha16 FC as soon app launched

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#57]
Latest alpha FCs as soon as it is launched, after allowing Permissions.

Also, on the past few alphas on first launch there is a long wait, blackscreen, before permissions toast appear.

**Comment by troop** [comment]
same as https://github.com/troop/FreeDcam/issues/55

**Comment by rancidfrog** [comment]
Permissions toast loaded faster on 17, but still FC

**Comment by rancidfrog** [comment]
http://hastebin.com/ihasetihid.avrasm

**Comment by troop** [comment]
i see, i forgot the case that there could be a empty folder lol

**Comment by troop** [comment]
[alpha18](https://github.com/troop/FreeDcam/releases/tag/3.3.133alpha17)

**Comment by rancidfrog** [comment]
Alpha18 fixes issue
