### ISSUE TITLE
No EXIF written for DNG on OnePlus One (SonyIMX) 

### ISSUE THREAD

**Issue by ColCh** [troop/FreeDcam#58]
```
Interoperability Index          : Unknown (N)
Interoperability Version        :  <...>
Strip Offsets                   : 0
Strip Byte Counts               : 0
Exposure Time                   : 0
F Number                        : 0
ISO                             : 0
Aperture Value                  : 1.0
Flash                           : No Flash
Focal Length                    : 3.8 mm
CFA Pattern                     : [Red,Green][Green,Blue]
GPS Latitude                    :  <...>
GPS Longitude                   :  <...>
GPS Position                    : <...>
Image Size                      : 4212x3120
Megapixels                      : 13.1
Shutter Speed                   : 0
Focal Length                    : 3.8 mm
```

A can prodive any other info (just tell me how)

**Comment by troop** [comment]
thats correct
when you tell me how to get iso/shutter from hal without root or as a second shot as jpeg from camera1 i will add it. but for now it looks bad.
opo has this params inside

- estimate-snap-exp-time=450847
- estimate-snap-iso=0

newer qcom devices(2015end/2016 have it inside the parameters.

- cur-exposure-time=50.000902
- cur-focus-diopter=0
- cur-focus-scale=100
- cur-iso=497

for mtk socs its possible to grab it direct from jpeg exif

**Comment by ColCh** [comment]
damn. that's why COS captures both jpg + raw - it just copies exif from jpg to raw? (I don't know, it just thoughts)

**Comment by troop** [comment]
opo has the callback to return both dng + jpeg, but that stuff is not added. there was something about that it cuts off dngs.
how cos that handels i dont know. think more they use that.
