### ISSUE TITLE
Exposure time on Redmi Note 3 (Snapdragon version)

### ISSUE THREAD

**Issue by jeromeof** [troop/FreeDcam#61]
Hi,
  I appreciate the effort to expose extract camera option on the Redmi Note 3 Pro / Snapdragon version but while the exposure time manual setting is visible in the UI it does not have any affect on my phone. I am using the AOSP build on the Redmi and in general the camera app works in that it takes valid pictures but this specific tweak does not seem to do anything. Is there any way I can assist you? Debug logs etc.

Thanks

**Comment by troop** [comment]
Hi.
Qcom changed the hal. And non of us have one. All stuff added yet is based on thoughts. 
Latest alpha On left side in cameraui you should see an option ae priority. When off expotime and iso are grayed out. When iso priority iso gets avail. Expo priority expo get avail. User setting should give full control. 
Log would be great.

**Comment by jeromeof** [comment]
OK, I can get you logs (and install a debug version if required). Is there specific logs and or diagnostic details that you need? Will I just use adb logcat?

**Comment by troop** [comment]
adb logcat is perfect. then i see what native happens too.

**Comment by jeromeof** [comment]
OK, here is my logcat when I run freedcam on an AOSP 5.1 build on a Redmi Note 3 Pro (Snapdragon):

[freedcam.txt](https://github.com/troop/FreeDcam/files/254012/freedcam.txt)

**Comment by marabujo** [comment]
In fact, in my device (Redmi note 3 snapdragon), when I scroll down the exposure time and I reach "0.8" the app force close. The above exposures times are possible to be selected (I don't know if they have impact on the photo like you are discussing), I tried one by one. From 0.8 to below the app close.

**Comment by troop** [comment]
hm good to know. need log from the fc

**Comment by marabujo** [comment]
[Redmi.txt](https://github.com/troop/FreeDcam/files/289185/Redmi.txt)

Here it is. Thank you.

**Comment by Evg33** [comment]
troop:
```
D/ShutterManual_ExposureTime_Micro(21245): StringUtils.FormatShutterStringToDouble:0.8
D/ShutterManual_ExposureTime_Micro(21245):  StringUtils.getMicroSec800.0
D/CamParametersHandler(21245): SetParametersToCam
I/QCameraParameters(  436): Requested preview size 720 x 480
I/QCameraParameters(  436): Requested picture size 4608 x 3456
I/QCameraParameters(  436): int32_t qcamera::QCameraParameters::setZslMode(const qcamera::QCameraParameters&): enabled: 0
E/QCameraParameters(  436): int32_t qcamera::QCameraParameters::setMorphoHDR(const qcamera::QCameraParameters&), ++
E/QCameraParameters(  436): int32_t qcamera::QCameraParameters::setMorphoHHT(const qcamera::QCameraParameters&), ++
E/QCameraParameters(  436): Invalid exposure time, value: 800.0
D/QCameraParameters(  436): int32_t qcamera::QCameraParameters::setReFocus(const qcamera::QCameraParameters&): AF Bracketing is not supported
D/AndroidRuntime(21245): Shutting down VM
E/AndroidRuntime(21245): FATAL EXCEPTION: main
E/AndroidRuntime(21245): Process: troop.com.freedcam, PID: 21245
E/AndroidRuntime(21245): java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(21245): 	at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime(21245): 	at android.hardware.Camera.setParameters(Camera.java:1979)
E/AndroidRuntime(21245): 	at com.freedcam.apis.camera1.camera.CameraHolderApi1.SetCameraParameters(CameraHolderApi1.java:357)
E/AndroidRuntime(21245): 	at com.freedcam.apis.camera1.camera.parameters.CamParametersHandler.SetParametersToCamera(CamParametersHandler.java:83)
E/AndroidRuntime(21245): 	at com.freedcam.apis.camera1.camera.parameters.manual.ShutterManual_ExposureTime_Micro.SetValue(ShutterManual_ExposureTime_Micro.java:108)
E/AndroidRuntime(21245): 	at com.freedcam.ui.themesample.views.ManualButton.setparameter(ManualButton.java:303)
E/AndroidRuntime(21245): 	at com.freedcam.ui.themesample.views.ManualButton.access$700(ManualButton.java:27)
E/AndroidRuntime(21245): 	at com.freedcam.ui.themesample.views.ManualButton$6.run(ManualButton.java:279)
E/AndroidRuntime(21245): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(21245): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(21245): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(21245): 	at android.app.ActivityThread.main(ActivityThread.java:5276)
E/AndroidRuntime(21245): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21245): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(21245): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
E/AndroidRuntime(21245): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
W/ActivityManager( 1356):   Force finishing activity 1 troop.com.freedcam/com.freedcam.MainActivity


```

**Comment by troop** [comment]
i changed stuff for shutter time in latest beta. now the supported shuttertimes should show correct values

**Comment by marabujo** [comment]
Now the app crashes when the selector passes through 1/100 000 but I can select another value if I scroll down very quickly. 1/2 is the most long exposure I can select. Does it mean that my phone cannot do longer than that?

In beta 12, DNG crashes again.

**Comment by troop** [comment]
yes its supports only 0,6 sec max exposure. and about dng crash yes it crash on beta12. but its already fixed

**Comment by panandreas** [comment]
Redmi note 3 pro snapdragon. 
The app crashes when exposure 1/100000 is selected. If any other value is selected it works fine. 
I hope you could make exposure and ISO work on dng too

**Comment by troop** [comment]
> I hope you could make exposure and ISO work on dng too
you mean the metadata? 
or have the taken dng(the image itself) not the expected values?
like at night when a car drives by it produce a light trail with0,6sec

**Comment by panandreas** [comment]
There is no metadata but I can live with that. I always select iso 100 to have as less noise as possible and then I play with the exposure time but the photos are exactly the same no matter what I select in ISO or in exposure time. When I play with iso and exposure in jpeg mode everything works as expected.

 I mean exactly what you say. Selecting 0,6 at night has no effect on moving objects and it's the same photo with selecting 1/1000 exposure

**Comment by marabujo** [comment]
@panandreas Have you rebooted the phone? when I installed a new beta the app worked strange. After reboot works fine. I have also a RMN3 SD and beta16 running MIUI global stable 7.1.8.0.

**Comment by troop** [comment]
you see on left side in cameraUI the [ae_priotrity](https://github.com/troop/FreeDcam/blob/PUBLIC/app/src/main/res/drawable-hdpi/ae_priority.png). if yes try to set it to user-setting. normaly that stuff should affect raws too when jpegs have motion trails

**Comment by panandreas** [comment]
Only when I set AE to spot-metering-adv,  exposure time works perfectly which is fine (the options are frame average, center weighted, spot metering, center weighted advice, spot metering adv) 

Selecting different ISO from the left menu has no effect. And the ISO selection on the bottom menu don't show anything when I click it. It always has value zero. I have also read for manual focus with redmi note 3 snapdragon but there is no option. But Maybe I am wrong. 

Once again. Great gift from all developers. I bought a smartphone and now I have a great DSLR

**Comment by panandreas** [comment]
I am sorry I was wrong. Spot metering just fooled me cause it was metering on a dark spot so the photo came out bright with 0,6 setting. I changed exposure to 1/5000  and the photo is the same. 
If I shoot jpeg with 1/5000 exposure the photo is almost black

**Comment by panandreas** [comment]
I build your latest commits with android studio and now ISO and manual exposure is gone from bottom menu. Still there is no AE priority on the left nor a manual focus on bottom (Redmi Note 3 Snapdragon)

**Comment by troop** [comment]
yes i know, mtk should have same problem^^
currently im cleaning heavy the source. and that problem is caused because the Aehandlernewqcom set stuff get overwritten. i want to create a basic class that get used for all 4 aehandlers in source.
so its currently not worth of fixing it because it gets changed soon

**Comment by troop** [comment]
Ae priority will not get visible. As i understood it now, it shows only the supported modes. So when using exposuretime and iso is set to auto ,ae handels iso (iso priority?). 
Expotime auto and iso manual is then exposure priority.
And both manual is user-setting

**Comment by panandreas** [comment]
I know you are changing a lot off things in the last days, I am just posting some notes in case you missed something.
I have seen you put ISO and exposure settings on the bottom menu. When I change this ISO setting the app crashes (DNG and JPG). If I change the ISO from the left menu it works fine. Finally both ISO and exposure has no effect on DNG.

**Comment by troop** [comment]
i dont know why manual iso and exposuretime not get applied to dngs and on jpegs it works. 
i dont think its a problem from freedcam. on other devices same parameters gets applied to dng too.

https://github.com/troop/FreeDcam/blob/master/app/src/main/java/com/freedcam/apis/camera1/parameters/device/Xiaomi_Redmi_Note3_QC_MTK.java#L79
that line defines the manual iso.
change there the continous-iso to iso and look if it works^^

**Comment by muntesco** [comment]
On Sony Z5 zoom works live but saved image is without zoom. Also is there
any possibility to enable dng or at least lossless jpg or tiff?
Il 14 giu 2016 1:23 PM, "Ingo" <notifications@github.com> ha scritto:

**Comment by panandreas** [comment]
I changed it but it crashes again.

**Comment by troop** [comment]
yep there was a copy paste fail^^ try latest commit

**Comment by panandreas** [comment]
Its working now!!! Still manual settings has no effect on dng

**Comment by troop** [comment]
Dngs looks in the viewer always darker. Its because it get shown with linearcurve.
Pls look for a light wich move with constant speed.
Take from that two pics, one jpeg and one raw and diff the produced light trail.
If the raw has a shorter or non trail xiaomi messed something up on the rd3sd.

**Comment by panandreas** [comment]
I am sure Xiaomi messed something up on rn3sd camera not only dng. If I shoot on a sunny day with iso100 and 0.6 exposure I get an almost white photo on jpeg. On dng I get a normal photo. I can also see from your animations that the shutter instantly open and close  on dng but on jpeg it stays open for a long time (1/2 sec) 
I hope Xiaomi will fix it

**Comment by Sinaaaa** [comment]
at iso 100 & 0.6 exposure time it should be white. Dng not being white means that it's not at 0.6sec on a sunny day.

**Comment by troop** [comment]
dont know if its total white with 0,6sec, but it should be noticable overexposured
on the mi5, xiaomi messed up raw capture total ^^
be happy you have that. seems not a glory year for them.
