### ISSUE TITLE
External SD doesn't work in marshmalleh

### ISSUE THREAD

**Issue by orangpelupa** [troop/FreeDcam#62]
Marshmallow have new external sd method, done by selecting the correct external SD from android system itself. FreeDcam has not support it, so cant save to external SD in marshmalleo

**Comment by troop** [comment]
you must choose the root of the sd. then pics gets saved /DCIM/FreeDcam

**Comment by troop** [comment]
but im talking about the alphas here. thet version in playstore does not support it

**Comment by orangpelupa** [comment]
thanks! yes sd card works in alpha :D thanks, issue closed.
