### ISSUE TITLE
Missing guide for making "Theme"

### ISSUE THREAD

**Issue by orangpelupa** [troop/FreeDcam#63]
the description is here https://github.com/troop/FreeDcam/wiki/MenuSettings

but its missing the guide for making or adding theme

**Comment by troop** [comment]
with "Theme" is a complete new ui meaned. in theory the sampletheme module can get easy extended and the icons changed aslong you dont want to change the behavior

for that its only needed to create a new module and extend all fragments wich are inside and replace there the the xml wich gets loaded.
like here with the [cameraui.xml](https://github.com/troop/FreeDcam/blob/PUBLIC/themesample/src/main/res/layout/cameraui.xml) and the fragment code part [CameraUiFragment.java](https://github.com/troop/FreeDcam/blob/PUBLIC/themesample/src/main/java/troop/com/themesample/subfragments/CameraUiFragment.java#L150) line 150 it gets loaded.

you have to create a new xml inside that new module/project and the new icons.
and extend the CamerUiFragment.java on overwrite only that line 150

you must extend then [SampleThemeFragment](https://github.com/troop/FreeDcam/blob/PUBLIC/themesample/src/main/java/troop/com/themesample too. its the base fragment where everything gets loaded and replace the Camerui Framgent by your new /SampleThemeFragment.java)
thats my small tut^^

**Comment by orangpelupa** [comment]
thanks the quick guide troop. 
i guess i gotta learn much more. im totally confused haha. 

gonna get back to this again after im a bit smarter.
