### ISSUE TITLE
Can you add an option to use "VOL - while DOWN/PRESSED" as "take a picture" button? Currently its "VOL - when UP/RELEASED".

### ISSUE THREAD

**Issue by orangpelupa** [troop/FreeDcam#64]
This could result in better picture due to better hand stability when holding down the button. Instead of taking picture when releasing the button.

when releasing the button, human will unconsciously add additional sway. Thus adding more blur.

thank you.

**Comment by troop** [comment]
that shake is not noticeable in daylight. 
also you have the option to enable DigitalImageStabilisation or OpticalImageStabilisation(when supported). 
when you take long exposures you can plug a headset and use that as remote shutter. 
in Settings you can asigne on wich harware key from the headset it triggers. 
mine has buttons vol+, vol- and hook(the one where you can accept calls):

**Comment by orangpelupa** [comment]
Yeah, sorry it was unclear. I mean the behavior of the hardware button itself. 

It will be better to reduce shake if it can be set to take a photo when the button was held down. Instead of when the button ws released. 

Like normal shutter button on cameras or those hardware shutter button on sony, LG, and maybe other brands too.
