### ISSUE TITLE
Optical image stabilization is missing in LG g pro 2 and camera parameters text 

### ISSUE THREAD

**Issue by orangpelupa** [troop/FreeDcam#65]
Hello again troop, and Pardon my English. 

The camera parameters text  http://pastebin.com/LfYrjnp5

Isn't it's supposed to say something like this instead of nothing? 

Opticalimagestabilization = true 
Or
Opticalimagestabilization = false

LG g pro 2 does have optical image stabilization. But the option is missing in FreeDcam. Only digital stabilization shown. 

Thank you.

**Comment by troop** [comment]
that optical imagestab is a hidden parameter. not sure if its the same  as for g3 and g4. we took that stuff from the libs.

**Comment by orangpelupa** [comment]
Any idea how do we check it's working or not?

**Comment by troop** [comment]
when it works and you turn it off the preview reacts faster. or when you mount it on a tripod and shake it a bit you see that the shake gets compensated depending how strong you shaked it when turned on

**Comment by orangpelupa** [comment]
sorry, i can't find the button to turn it on/off :(

**Comment by troop** [comment]
open settings in right tab under digitalimagestab it should be as Optical Image Stabilisation

**Comment by orangpelupa** [comment]
Thanks! I see it in the latest beta. This is closed for now. Will test the OIS later after I got back from hospital.
