### ISSUE TITLE
Manual Focus Mode is Missing

### ISSUE THREAD

**Issue by Szainvi** [troop/FreeDcam#69]
Manual Focus mode does not show on the bottom and doesn't work on smartphones having Snapdragon chipset .. please fix it.. But it fully works on Smartphones having Mediatek Chipset.. Please fix it for Snapdragon users thanks. 
![screenshot_20160526_165456](https://cloud.githubusercontent.com/assets/19589594/15573179/b8afdc7a-2362-11e6-8650-705780e93065.png)

**Comment by troop** [comment]
About what devices you are talking? The big problem are the oems bruting their own custom shit. There are only a few devices wich are based on qcom. Sony started to mod mtk too and add their own stuff.

**Comment by Szainvi** [comment]
I have oppo f1 plus ,manual focus Distance fully work on it.. But i try on smartphones having a Snapdragon 625 , 615 like Oppo r7 lite, vivo v3 max..  This feature is missing ,manual focus distance doesn't show.
