### ISSUE TITLE
Please add latest apk to releases

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#7]
It would be great to have the latest APK, 3.3.94,  available on [Releases](https://github.com/troop/FreeDcam/releases) section

Thank you

**Comment by troop** [comment]
pls join the g+ group there you can register to alpha and get the latest apk. i changed alot stuff with with raw converting and added a dng viewer and slowly getting response whats not working
https://plus.google.com/u/0/communities/112880644833309033743
