### ISSUE TITLE
Manual controls / settings / UI on MTK devices

### ISSUE THREAD

**Issue by TaoistHUN** [troop/FreeDcam#70]
Hello again :)
I have a Xiaomi Redmi Note 2 [HERMES]
 (MTK Helio X10 CPU - **S5K3M2** Camera module . _Same in Redmi Note 3 [Hennessy]_ )

In the FreeDCamera there are some unuseable ISO / Shutter speed steps.

The correct parameters in this device:
ISO: 100-1600 in 100"s steps
Shutter speed : 
1/4000s - 1/2000s - 1/1000s - 1/500s - 1/250s -  1/125s - 1/60s - 1/30s - 1/15s - 1/8s - 1/4s - 1/2s - 1s- 2s

Can you apply the correct parameters in the next release?

And on my redmi , the left menu is not full, some switches is missing, like the HDR mode, Night mode:
<a href="https://picload.org/view/rgigdocd/sc.png.html" target="_blank"><img src="https://picload.org/thumbnail/rgigdocd/sc.jpg" /></a>
Any solution?

:question: 

Thanks.

**Comment by milancheee** [comment]
Same here! 

Manual focus works perfectly on beta9, iso/shutter don't.

**Comment by TaoistHUN** [comment]
Xiaomi Redmi Note 2 [Codename:Hermes ] Beta 12 Report:
Correct ISO steps, correct shutter steps, BUT...
... the DNG option is missing from the mode menu, it can take only JPGs, and bayers, and the bayer freezes the viewer, and the FreeDcam app, just like the DNG's in eatlyer builds. 
JPGs fine...
Beta 10 works good, but with wrong  ISO, and shutter parameters...

**Comment by defcomk** [comment]
Wrong as in its set but snapshot value does not match set value .

try this keep the device on on a static scene like a white wall switch to jpeg take an image while still holding the scene go to menu save camera parameters post jpeg exif as well as cap-ss and cap-sr-g these should show how they format these values

**Comment by troop** [comment]
beta 16 should fix it
