### ISSUE TITLE
Redmi Note 3 (MTK) - Magenta tint

### ISSUE THREAD

**Issue by TheSpixxyQ** [troop/FreeDcam#71]
On my XRN3-MTK when I capture dng, it is tinted with magenta color and it's like there are not any other colors. Where can be problem? I tried 3.3.132, 3.3.133b6 and now 3.3.133b7 and still same. In my phone is Samsung S5K3M2 sensor.
![img_2016_05_30_16_15_10](https://cloud.githubusercontent.com/assets/13891066/15652153/7211793e-2684-11e6-92f3-7f004025fe3f.jpg)
DNG file if you need:
[IMG_2016_05_30_16_15_10.zip](https://github.com/troop/FreeDcam/files/289725/IMG_2016_05_30_16_15_10.zip)

Btw. it also FC's when I have raw image in FreeDcam folder, like said in another issue topic.

**Comment by troop** [comment]
well must truly say xiaomi give me there a task. can you please attach the camera parameters.
so there are out a redmi note 3 mtk and snap and same for pro version?

**Comment by TheSpixxyQ** [comment]
You mean these?
RMN3 has MTK version and new Snap version called Pro, both of them have 2/16GB and 3/32GB (RAM/storage) versions.
[Redmi Note 3_CameraParameters.txt](https://github.com/troop/FreeDcam/files/290000/Redmi.Note.3_CameraParameters.txt)

**Comment by Evg33** [comment]
Xiaomi Redmi Note 3 - 13 MP, f/2.2 | cam Samsung S5K3M2 (sunny)  / OmniVision(O-film) | (cpu MTK)

Xiaomi Redmi Note 3 pro - 16 MP, f/2.0 | cam Samsung S5K3P3 | (cpu snapdragon 650)

**Comment by TaoistHUN** [comment]
**Evg33**.... And the Redmi Note 2 has a same Sensor, and CPU as the  Redmi Note 3 MTK version...
Beta 9 Woks perfectly. 
Which  matrix do you use? Default? 

Good Job MR.Troop.

**Comment by troop** [comment]
we have yet seen same sensors with different colorpatterns and also different raw sizes. everything is possible ^^ redmi2 use GBRG. normaly when the colors are shifted that way its BGGR or RGGB.
@TheSpixxyQ pls upload a .bayer too. 
The real worse thing is that both devices are called Redmi Note 3. 
that means for now mtk redmi3 see same manual stuff as pro and it will not work.

**Comment by TheSpixxyQ** [comment]
They also have one forum for both of these versions, so somebody can easily download bad ROM, set something wrong etc.
Here:
[rmn3bayer.zip](https://github.com/troop/FreeDcam/files/290367/rmn3bayer.zip)

**Comment by troop** [comment]
beta10 should produce now correct colors

**Comment by TheSpixxyQ** [comment]
Thanks, but still same. Imo there is problem with right identification, because I'm still getting Note 3 Pro camera parameters, not that new MTK.

**Comment by troop** [comment]
clear the cache from freedcam. freedcam stores thumbs for all images and use them to faster show pics. when the cache not gets cleared the old thumbs gets used and you have tint inside.

to clear cache open phone settings, go to app, select there freedcam and clear cache
![screenshot_2016-06-01-06-12-34](https://cloud.githubusercontent.com/assets/377693/15697978/ebbeb94a-27bf-11e6-841a-49b2af3e345c.png)

**Comment by TheSpixxyQ** [comment]
That's weird, I tried reinstall and delete data files of app and still have that tint, also on newly taken photos.. It also appears when I open it with Photoshop express
![screenshot_2016-06-01-06-48-55_troop com freedcam](https://cloud.githubusercontent.com/assets/13891066/15698554/03102dd0-27c6-11e6-9ff2-aa79a0d79035.png)

**Comment by troop** [comment]
Try pls something. Open freedviewer click on rawtodng select a bayer/raw click again on rawtodng. Then the dngconverter opens and should show gbrg as colorpattern.
That code works on all dng supported devices the same. If not xiaomi fucked up enums and switch cases.

**Comment by troop** [comment]
I see the problem. I forgot to remove redmi note 3 enum.

**Comment by TheSpixxyQ** [comment]
Well, I opened that rawtodng and it showed RGGB. Then I tried to convert that bayer to GBRG and I finally got right colors. So now only fix identification and it will work perfectly

**Comment by troop** [comment]
latest beta should produce now correct colors.

bracket will not work with dngs and mtk. that 3mb bayers are jpeg. just replace bayer with jpg and you can open them.

i dont think that mtk socs are able to record 120fps(the parameters dont contains such stuff). you created the 120fps profile on your own or it get showed from freedcam?

**Comment by TheSpixxyQ** [comment]
Okay, thanks. Latest beta crashes for me again when I have any dng in folder and when I delete config I get blank screen.
![screenshot_2016-06-02-06-42-51_troop com freedcam](https://cloud.githubusercontent.com/assets/13891066/15734215/8f025a44-288d-11e6-8aa6-ca9afebd60ac.png)
[Redmi Note 3_2016_06_02_06_45_54.txt](https://github.com/troop/FreeDcam/files/294824/Redmi.Note.3_2016_06_02_06_45_54.txt)

My phone can record 120FPS in stock camera, I created it by my own

**Comment by troop** [comment]
Fully uninstall it. Then try again.

**Comment by TheSpixxyQ** [comment]
I tried, nothing.
It also crashes when I want to exit app
![screenshot_2016-06-02-07-10-19_com miui bugreport](https://cloud.githubusercontent.com/assets/13891066/15734542/44b7ea22-2891-11e6-9ab0-25ab73a5a452.png)

**Comment by panandreas** [comment]
I have Xiaomi Redmi Note 3 Pro (snapdragon 650, Samsung S5K3P3 sensor)

I don't know how to compile the beta versions from here so I am using the latest stable from playstore and I can only save as RAW or JPEG. I can't preview the RAW files neither from smartphone nor from desktop. I am attaching camera parameters and a sample RAW file

[Redmi Note 3_CameraParameters.txt](https://github.com/troop/FreeDcam/files/295131/Redmi.Note.3_CameraParameters.txt)

**Comment by TheSpixxyQ** [comment]
Just download apk from https://github.com/troop/FreeDcam/releases. Playstore version is pretty old and not updated I think

**Comment by troop** [comment]
new try

**Comment by TheSpixxyQ** [comment]
Now crash after capture
![screenshot_2016-06-02-19-29-09_com miui bugreport](https://cloud.githubusercontent.com/assets/13891066/15754529/d3ce9c44-28f8-11e6-8f27-48b62117cc9b.png)
Debug:
[Redmi Note 3_2016_06_02_07_28_51.txt](https://github.com/troop/FreeDcam/files/296169/Redmi.Note.3_2016_06_02_07_28_51.txt)

**Comment by troop** [comment]
new try. now everything should work. at least i hope^^

about iso, i was told mtk use max iso1600. 
i dont have such a device so i have to trust what users tell me

**Comment by TheSpixxyQ** [comment]
Crash while selecting format, also crashed when I had dng in folder
![screenshot_2016-06-03-06-27-25_com miui bugreport](https://cloud.githubusercontent.com/assets/13891066/15768822/e1c0fe76-2954-11e6-81c2-667d2be7e33c.png)
[Redmi Note 3_2016_06_03_06_28_44.txt](https://github.com/troop/FreeDcam/files/296923/Redmi.Note.3_2016_06_03_06_28_44.txt)

I don't know, it just works for me. If you want to try some functions on this device let me know, I can help you

**Comment by troop** [comment]
let first get the basic capture stuff working. then we continoue with the manuals
new try with beta14

**Comment by TheSpixxyQ** [comment]
Yes, okay. Beta14 - available only jpeg and that works fine. Dng and bayer are missing 
[Redmi Note 3_2016_06_03_01_13_34.txt](https://github.com/troop/FreeDcam/files/297449/Redmi.Note.3_2016_06_03_01_13_34.txt)

**Comment by troop** [comment]
beta15 up. i hope that the matrixchooser now not crash and if it crash it should not break howle device detection so raw dng gets shown again

**Comment by TheSpixxyQ** [comment]
Well, that now works fine. Now it crashes again when raw is in FreeDcam folder. But that taken dng can be viewed with PS
[Redmi Note 3_2016_06_03_01_49_40.txt](https://github.com/troop/FreeDcam/files/297495/Redmi.Note.3_2016_06_03_01_49_40.txt)

**Comment by troop** [comment]
hm looks like its native. the part where it crash is missing.
look if crash folder contains something pls.

**Comment by troop** [comment]
> Now it crashes again when raw is in FreeDcam folde.rBut that taken dng can be viewed with PS

does it crash when its a .bayer/raw or when a dng is added?

**Comment by panandreas** [comment]
Redmi Note 3 SnapDragon
Crashes on both and if I delete them it works.
[Redmi Note 3_CameraParameters.txt](https://github.com/troop/FreeDcam/files/297528/Redmi.Note.3_CameraParameters.txt)
[Redmi Note 3_2016_06_03_03_09_38.txt](https://github.com/troop/FreeDcam/files/297530/Redmi.Note.3_2016_06_03_03_09_38.txt)

**Comment by troop** [comment]
i see the problem. stupid git submodule replaced old libraw with new.

**Comment by troop** [comment]
beta16 with oldlibraw is up

**Comment by bebolint98** [comment]
With beta16 the dng works didn't stop after taking photo. But I faced that sometimes the app is reset itself so I need to set the resolution, focus mode, etc...

**Comment by troop** [comment]
that happens only when freedcam did crash bevor the settings got saved.

**Comment by troop** [comment]
pls close issue when its fixed now

**Comment by TheSpixxyQ** [comment]
It's working now, thank you very much! :)
My really last question, can you please tell me cases when I have to turn off Zero Shutter Lag and when I can have it on? Thanks
This app is the best

**Comment by troop** [comment]
i dont know if zsl affect mtk devices. itself takes the current captured frames instead of creating a new  highquality capture. on qcom devices it must get disabled to capture raw.
