### ISSUE TITLE
Redmi Note 3 Pro (Snapdragon) Shutter speed and dng crash

### ISSUE THREAD

**Issue by bebolint98** [troop/FreeDcam#72]
In beta11 if want to set manual shutter speed the app close itself. And if I take a picture in dng after the freedcam didn't start till I move or delete the picture from freedcam folder.

**Comment by TaoistHUN** [comment]
Redmi Note2 , similar issue...

**Comment by defcomk** [comment]
I would setup android studio then build based on newest commits also it easier debug

**Comment by troop** [comment]
so shutter speed works now with beta16?

**Comment by bebolint98** [comment]
No, the app close itself.

**Comment by troop** [comment]
crash log would be good

**Comment by Evg33** [comment]
beta16 XRN3Pro kenzo (Snapdragon)
```
I/QCameraParameters(  426): Requested preview size 720 x 480
I/QCameraParameters(  426): Requested picture size 160 x 120
I/QCameraParameters(  426): int32_t qcamera::QCameraParameters::setZslMode(const qcamera::QCameraParameters&): enabled: 0
E/QCameraParameters(  426): int32_t qcamera::QCameraParameters::setMorphoHDR(const qcamera::QCameraParameters&), ++
E/QCameraParameters(  426): int32_t qcamera::QCameraParameters::setMorphoHHT(const qcamera::QCameraParameters&), ++
E/QCameraParameters(  426): Invalid exposure time, value: 0.01
D/QCameraParameters(  426): int32_t qcamera::QCameraParameters::setReFocus(const qcamera::QCameraParameters&): AF Bracketing is not supported
D/AndroidRuntime(26782): Shutting down VM
E/AndroidRuntime(26782): FATAL EXCEPTION: main
E/AndroidRuntime(26782): Process: troop.com.freedcam, PID: 26782
E/AndroidRuntime(26782): java.lang.RuntimeException: setParameters failed
E/AndroidRuntime(26782): 	at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime(26782): 	at android.hardware.Camera.setParameters(Camera.java)
E/AndroidRuntime(26782): 	at com.freedcam.apis.camera1.camera.CameraHolderApi1.SetCameraParameters(CameraHolderApi1.java:363)
E/AndroidRuntime(26782): 	at com.freedcam.apis.camera1.camera.parameters.CamParametersHandler.SetParametersToCamera(CamParametersHandler.java:82)
E/AndroidRuntime(26782): 	at com.freedcam.apis.camera1.camera.parameters.manual.ShutterManual_ExposureTime_Micro.SetValue(ShutterManual_ExposureTime_Micro.java:108)
E/AndroidRuntime(26782): 	at com.freedcam.ui.themesample.views.ManualButton.setparameter(ManualButton.java:303)
E/AndroidRuntime(26782): 	at com.freedcam.ui.themesample.views.ManualButton.access$700(ManualButton.java:27)
E/AndroidRuntime(26782): 	at com.freedcam.ui.themesample.views.ManualButton$6.run(ManualButton.java:279)
E/AndroidRuntime(26782): 	at android.os.Handler.handleCallback(Handler.java)
E/AndroidRuntime(26782): 	at android.os.Handler.dispatchMessage(Handler.java)
E/AndroidRuntime(26782): 	at android.os.Looper.loop(Looper.java)
E/AndroidRuntime(26782): 	at android.app.ActivityThread.main(ActivityThread.java)
E/AndroidRuntime(26782): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26782): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26782): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/AndroidRuntime(26782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
I/WtEventController( 4006): Receive am_crash event for pid: 26782

```

**Comment by bebolint98** [comment]
Here is the log:

java.lang.RuntimeException: setParameters failed
	at android.hardware.Camera.native_setParameters(Native Method)
	at android.hardware.Camera.setParameters(Camera.java:1979)
	at com.freedcam.apis.camera1.camera.CameraHolderApi1.SetCameraParameters(CameraHolderApi1.java:363)
	at com.freedcam.apis.camera1.camera.parameters.CamParametersHandler.SetParametersToCamera(CamParametersHandler.java:82)
	at com.freedcam.apis.camera1.camera.parameters.manual.ShutterManual_ExposureTime_Micro.SetValue(ShutterManual_ExposureTime_Micro.java:108)
	at com.freedcam.ui.themesample.views.ManualButton.setparameter(ManualButton.java:303)
	at com.freedcam.ui.themesample.views.ManualButton.access$700(ManualButton.java:27)
	at com.freedcam.ui.themesample.views.ManualButton$6.run(ManualButton.java:279)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5273)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by Evg33** [comment]
issue #61

**Comment by troop** [comment]
hm the question is what is a valid exposure time and how have it to look like
