### ISSUE TITLE
No JPEGs are created in DNG mode

### ISSUE THREAD

**Issue by papersplease** [troop/FreeDcam#74]
Starting with 3.3.133 betas, JPEG isn't created anymore along with matching DNGs. Is this intentional? Now DNGs are much less usable with no metadata. I'm using Xiaomi Redmi Note 2 (hermes) with Mediatek Helio X10 chipset. The logcat is [here](https://gist.github.com/papersplease/d08cdf2831990f8c239fadb21a62418c).

**Comment by troop** [comment]
Log is incomplete. It stopped bevor it get interessting. 
Realy dngs without meta are useless?
Is new to me that meta affect post processing dngs.
From code itself i dont see why jpegs not get saved

**Comment by papersplease** [comment]
Ah sorry, here's [another one](https://gist.github.com/papersplease/2c3239ca0444ccec919ba74d03765cf8), hopefully more complete but I don't see anything related to the problem in this log either.

Not useless of course, but I'm finding myself merging 2-3 exposures sometimes, shutter speed and iso is needed for that. (and certainly needed for the bracketing feature to be truly useful, if it's going to be implemented for mediatek chipsets). Also, GPS data is nice to have, although it never worked for me in freedcam for some reason anyway.

**Comment by troop** [comment]
hm funny stuff. log is good.


> 06-05 11:17:48.295 1833-1833/troop.com.freedcam D/PictureModuleMTK: Take Picture CallBack
> 06-05 11:17:48.297 1833-2131/troop.com.freedcam D/PictureModuleMTK: HolderFilePath:/storage/emulated/0/DCIM/FreeDcam/**IMG_2016_06_05_11_17_48.dng**
> 06-05 11:17:48.297 1833-2131/troop.com.freedcam D/AbstractModule: Start Saving Bytes
> 06-05 11:17:48.303 1833-2131/troop.com.freedcam D/AbstractModule: End Saving Bytes
> 06-05 11:17:48.421 1833-2131/troop.com.freedcam D/PictureModuleMTK: Filesize: 26023936 File:/storage/emulated/0/DCIM/FreeDcam/mtk1465114666944pure__4192x3104_10_1.bayer

the jpeg gets first saved with dng file ending. then the same file gets rewritten as dng.

**Comment by papersplease** [comment]
The issue seems to be fixed in beta17, thank you.
