### ISSUE TITLE
Clipping indication broken

### ISSUE THREAD

**Issue by papersplease** [troop/FreeDcam#75]
Over/underexposure highlighting doesn't seem to work properly for me in the latest beta. Here's two screenshots to illustrate this.
![screenshot_2016-06-07-12-06-16](https://cloud.githubusercontent.com/assets/791891/15852080/83d07204-2ca8-11e6-860b-16795ddceab0.png)
![screenshot_2016-06-07-11-59-08](https://cloud.githubusercontent.com/assets/791891/15851945/db47f54e-2ca7-11e6-9e41-20b4045c09f8.png)

As you can see, clipping is only shown at some borders between the normal and clipped areas. Here's [the log](https://gist.github.com/papersplease/d5f66a6c540b8b82a8ca9ac9e9fea8bd) of the focus peaking feature being activated.

**Comment by troop** [comment]
Works as it should. The problem is the scene you have. Clipping works that way:
If a color is close to white rgb (255 255 255) -2
It gets detected as over exposured.
If color is close to black rgb(0 0 0) +2 its underexposured.
You can try it with a lamp or sun.
All values between gets not detected.
Cant attach a screen shot from phone

**Comment by papersplease** [comment]
Well the sky in that scene looks to be clipped to me, and in Photoshop I can see blown highlights very clearly (obviously a bit less since it's raw in photoshop vs processed in the preview).

Here's how same scene looks on one of the older versions of freedcam:

![screenshot_2016-06-07-12-39-11](https://cloud.githubusercontent.com/assets/791891/15853542/34db826e-2cae-11e6-8b30-188d5049c327.jpg)
![screenshot_2016-06-07-12-39-56](https://cloud.githubusercontent.com/assets/791891/15853559/46ee0454-2cae-11e6-94b2-3643665dcab8.jpg)
![screenshot_2016-06-07-12-40-04](https://cloud.githubusercontent.com/assets/791891/15853562/49ff1214-2cae-11e6-83cb-73e4ef42f6ed.jpg)

Clipping warning is much more prominent and actually useful on these screenshots.

Here's how the bright lamp looked in older versions:

![screenshot_2016-06-07-12-42-00](https://cloud.githubusercontent.com/assets/791891/15853592/714f6c56-2cae-11e6-9436-25e6d2c68ca1.jpg)

Here' how the same lamp looks in beta17:

![screenshot_2016-06-07-12-43-40](https://cloud.githubusercontent.com/assets/791891/15853698/d91808ca-2cae-11e6-93aa-a7c95212b35b.jpg)

**Comment by papersplease** [comment]
I discovered that the problem might be in the preview I guess. The blown out highlights on that lamp are (218, 218, 218) for some reason, and not (255, 255, 255) as it should be, that's possibly why detection doesn't work. They are (255, 255, 255) in older versions. The dark frame with the lens covered shows (4, 3, 3) in the preview instead of (0, 0, 0).

**Comment by troop** [comment]
hm thats crazy. when the preview format got changed focuspeak and clipping would crash.
so preview format is not the problem.

for me it works normal on all my phones. i have no idea what it cause
![screenshot_2016-06-07-11-27-37](https://cloud.githubusercontent.com/assets/377693/15882605/8b6bf43c-2d40-11e6-9e5b-479b88a8c050.png)

**Comment by papersplease** [comment]
What I found so far:
- it stopped working in beta14; beta13 and all versions before work fine.
- it works fine in jpeg mode, and only breaks on switching to dng or bayer.
- it doesn't restore back when switching from dng to bayer, but if I select the jpeg and relaunch the app in that mode, it works fine again.

Since the preview is the subject to white balance correction and other postprocessing, could it be some postprocessing parameters set wrong in dng?

**Comment by papersplease** [comment]
Looks like I've found the problem: contrast, brightness and saturation are set to low when switching from dng to jpeg. And they affect the preview in such way that highlights never hit 253, and shadows never hit 2. Setting everything to medium restores clipping detection. Looks like those settings are set to low in RAW modes.

**Comment by troop** [comment]
yes that can cause the problem. normaly freedcam takes on start the default values set by the cam.
when you switch to dng saturation etc gets set back to default. 
switch to jpeg loads the last set values.

**Comment by papersplease** [comment]
Maybe some option to NOT hide processing controls like contrast etc in DNG mode would be better?

I mean, leave it to the user, since raw clipping/histogram is impossible to get in realtime anyway, every device have different processing, and clipping detection heavily depends on it. Users then can tweak the preview to match real raw clipping more closely for their devices. The same with digital zoom, leave it accessible to the user even in DNG mode. The frame will be taken raw anyway, but focusing with 4x digital zoom and focus peaking can be easier and more precise.

**Comment by papersplease** [comment]
Thanks for leaving all the controls in DNG mode on. Hovewer, the clipping indication is still broken in 3.3.134alpha1 in a different way: turning it on makes the screen completely black until it's turned off. [Here's the log](https://gist.github.com/papersplease/18f6c9bb5cb5ca0911b23b83ccd8c28d) for that.

**Comment by papersplease** [comment]
Works for me in alpha2. Thanks for the greap app!

**Comment by papersplease** [comment]
It works fine, but there's a [crash](https://gist.github.com/papersplease/a59ca1d83442bf9ca3ab1105b02a5892) on exit with focus peaking activated.
