### ISSUE TITLE
Redmi Note2 [Helio X10]  High noise at low ISO

### ISSUE THREAD

**Issue by TaoistHUN** [troop/FreeDcam#76]
I tried take a picture with long shutter speed and low ISO, (ISO100 , 2S) but the result is quite noisy, it's like not be 100 ISO.
Same result DNGs and JPGs as well.
It is possible that a slow shutter speed causes warming on the sensor, and this will cause noise ont the pictures,or its a bug,or issue?

Edit
PLS somebody post a pic, with ISO100/2s to compare
Redmi Note2, or Redmi Note 3 MTK

**Comment by papersplease** [comment]
First, RN2 has 2 seconds exposure limitation and this is not nearly enough for mobile cameras on ISO100 at low light conditions, so you will have most of your picture underexposed heavily. You need longer exposures or higher ISO.

Second, most cheap sensors (all the mobile ones specificially) have bias drift that heavily depends on the temperature. Use the calibration techniques from astrophotography: dark and bias frames. The former usually deals well with vertical stripes or another readout pattern you can see at iso 100 on underexposed detail (especially in stacks), the latter can help reduce the random thermal noise (but also can introduce some when applied without understanding).

Third, slow shutter speeds doesn't warm up CMOS sensors, only the readout does slightly (and the frame processing/writing warms up the CPU much more)

**tl'dr:** Not a freedcam issue but a fundamental problem of long exposure digital imaging.

**Comment by TaoistHUN** [comment]
Thank You for this answer.
I thought ,its technical problem... 


Issue closed.

**Comment by TaoistHUN** [comment]
I've noticed now...
If i use the longest exposure time (2s) I cant change the ISO, If i set the sensitivity to ISO 1600, the photo will not be brighter. The exif says Its ISO 1600, but the brightness, noise same as ISO 100.

**Comment by papersplease** [comment]
@TaoistHUN That's the device/camera libs limitation, 2 second exposure is only available with ISO100 on RN2. ISO1600 and higher do limit the exposure to 1/10 no matter what you set, so this device is not great for doing long exposures. AFAIK only xiaomi can fix that, either themselves or by releasing the source code (and they will likely do neither one). Many vendors do the same, for different reasons.

**Comment by TaoistHUN** [comment]
Ok, its a hardware problem/ limitation again... Good to know.
Thanks again. :+1:

**Comment by troop** [comment]
normaly there is a lib wich holds the exposuretable(on qcom i know it for sure). there are the iso modes defined and wich shutter values are possible at that iso mode for ae.
manual modes should be able to overwrite it.

in the manuals fragment in freedcam try first to set manual iso, after that change the manual shutter and look if something happens. normaly that way the ae gets turned off.
when you first change shutter and keep manual iso at auto it can fail to set ae off.
