### ISSUE TITLE
Raw capture xperia z5 possible?

### ISSUE THREAD

**Issue by muntesco** [troop/FreeDcam#77]
great app...but how to get a DNG or other loosless format to work on sony cameras (xperia z5)? Is it any beta version supporting this format on sony phones?

**Comment by troop** [comment]
You are able to capture a raw/bayer file?
Stock sony android cant capture it as far i know.
Only roms based on free xperia with os hal.

**Comment by troop** [comment]
on the ui item where jpeg is you should see raw_sensor or raw10.
both creates a dng. if you dont see it well then its not supported

**Comment by muntesco** [comment]
no way at this moment for RAW. Just waiting for a new sony firmware with the hope they will add this capability. However switching off noise reduction in FreeDcam is a great thing.....

**Comment by troop** [comment]
I dont think sony will make it avail.
Free xperia based roms should support it.
