### ISSUE TITLE
4kuhd crash camera(Redmi Note 3 SD)

### ISSUE THREAD

**Issue by marabujo** [troop/FreeDcam#78]
The app allows to select video mode but when hit the screen to focus (autofocus) it force closes
[Redmi Note 3_2016-06-11_10.37.40.txt](https://github.com/troop/FreeDcam/files/310519/Redmi.Note.3_2016-06-11_10.37.40.txt)
.

**Comment by troop** [comment]
only with 4kuhd or all video modes?

**Comment by marabujo** [comment]
Only 4kuhd.

**Comment by troop** [comment]
the problem seems that the wrong size gets applied to the preview.
