### ISSUE TITLE
Missing auto shutter speed

### ISSUE THREAD

**Issue by bebolint98** [troop/FreeDcam#83]
On the latest alpha1 the auto shutter speed option is missing in Xiaomi Redmi Note 3 Pro (Snapdragon).
![screenshot_2016-06-20-16-55-09_troop com freedcam](https://cloud.githubusercontent.com/assets/10884664/16198863/c6bee104-3707-11e6-8721-a776a7634f94.png)

**Comment by troop** [comment]
hm yes thats a failure
