### ISSUE TITLE
Focus Issue

### ISSUE THREAD

**Issue by DeastinY** [troop/FreeDcam#84]
Oneplus One : Sultans Rom based on CM13.

When using the App I can not focus manually beyond the first focus. I can still set to infinity/macro via the setting. It's pretty strange and I don't know what information I can really add, just wanted to let you know it's there.
Phone is ready, App is open - If you need any additional information I'm glad to help

**Comment by troop** [comment]
Pls attach the camera parameters.
In freedcam open settings, on leftpanel on bottom is save camparameters. It gets saved to internalSD/DCIM/FreeDcam.

**Comment by DeastinY** [comment]
[A0001_CameraParameters.txt](https://github.com/troop/FreeDcam/files/329589/A0001_CameraParameters.txt)

**Comment by troop** [comment]
on wich version are you? that from playstore ore one of the alphas/betas here?

**Comment by DeastinY** [comment]
Playstore, should I try to upgrade ?

**Comment by DeastinY** [comment]
I tried the alpha, same issue, less stable - then everything died, I killed the router, blew up my linux and my phone melted...
Now I'm on Oxygen and can't test anything anymore. //WorstExcuseEver
But I'll give some feedback regarding performance on OxyOS if needed :grin:
