### ISSUE TITLE
Optimization for Xiaomi Mi5

### ISSUE THREAD

**Issue by AlexVain** [troop/FreeDcam#85]
Hello, I've downloaded 3.3.134alpha3 (GP version doesn't start at all), but have many bugs. Cuttently I'm only able to shot in JPG with auto focus. When I'm trying to choose RAW or edit any settings in camera view app crashes. Plz help! Thx.

**Comment by AlexVain** [comment]
UPD. I've played with settings a bit, now I'm able to shoot in RAW, but I couldn't open it with Freedcam app, Photo Mate or Snapseed (file is corrupted). This is Settings I've used.
[MI 5_CameraParameters.txt](https://github.com/troop/FreeDcam/files/331403/MI.5_CameraParameters.txt)

**Comment by defcomk** [comment]
in picture format menu choose Bayer then upload that file

**Comment by AlexVain** [comment]
Yep, I've choose Bayer. But couldn't open it with several apps like I was able to open .dng

**Comment by defcomk** [comment]
yes Bayer needs to be encoded/packed into a dng/tiff container the .Bayer file you shot upload that sample file so the that dng can be added

**Comment by AlexVain** [comment]
yep. And I couldn't encode them (see the screen I guess that .bayer files shouldn't be empty)
![screenshot_2016-06-24-16-47-03_troop com freedcam](https://cloud.githubusercontent.com/assets/20123326/16339483/9249b76a-3a2b-11e6-8444-be090429899b.png)

**Comment by defcomk** [comment]
what's the file size hit me up on telegram @defcomk

**Comment by AlexVain** [comment]
3.7Mb. Sadly haven't got telegram

**Comment by troop** [comment]
when the file size is not added to libraw its cant decoded and it stays that way.
with 3.7mb it looks more like a jpeg. try to rename the file ending to .jpg
i would say xiaomi messed up rawcapture

**Comment by defcomk** [comment]
try enable camera 2 and switch to cam 2 api have a look at this thread http://forum.xda-developers.com/mi-5/how-to/enabling-camera2-api-t3423719/page1
