### ISSUE TITLE
Small annoyance on first launch

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#86]
When you launch app after install, the app asks for permissions, when done it exits, instead of going to launch screen which can be seen in the background when enabling permissions.

**Comment by troop** [comment]
Then you did not grant all permissions it ask for.

**Comment by rancidfrog** [comment]
I usually grant all but location.
App asks for 4 permissions: Camera, storage, microphone, location

**Comment by troop** [comment]
Its planned that permission gets asked when they are needed. So when activating video module it ask for microphone. When activating location its ask then for location. At current state freedcam exit when one is missing
