### ISSUE TITLE
Mtk not all dngs gets saved

### ISSUE THREAD

**Issue by TheSpixxyQ** [troop/FreeDcam#87]
I have this issue since alpha3, it looks like only every second dng is saved, jpgs are all there. I think you're gonna need logcat, what is the best app for viewing only logs from your app?
![screenshot_2016-07-04-21-02-18-243_com estrongs android pop](https://cloud.githubusercontent.com/assets/13891066/16568581/617d616e-422c-11e6-9092-c1d6e87c94d5.png)

**Comment by troop** [comment]
Dont know that should happen on all mtk devices.
But you are the first who tell me about.

**Comment by troop** [comment]
to get logs you can create a DEBUG folder insided internalSD/DCIM/FreeDcam
then the logs gets saved on each start of the app.

**Comment by troop** [comment]
have talked to some mtk users they dont have that problem

**Comment by TheSpixxyQ** [comment]
Well , I thought debug is only for alpha / beta
[Redmi Note 3_2016_07_08_10_18_41.txt](https://github.com/troop/FreeDcam/files/355053/Redmi.Note.3_2016_07_08_10_18_41.txt)

Sometimes it triggers shutter stop capture
