### ISSUE TITLE
Unfortunately, FreeDCam has stopped

### ISSUE THREAD

**Issue by NOT-a-BUG-but-a-FEATURE** [troop/FreeDcam#89]
Hello, thanks for your excellent program.
But I've tried to run release 3.3.135 on the Xiaomi Mi-4c with firmware MoKee (release 160705, Android 6.0.1) and got an error: "Unfortunately, FreeDCam has stopped."
Earlier in the same device with firmware MIUI 7.5 (Android 5.1.1) it works fine.
[logcat.txt](https://github.com/troop/FreeDcam/files/355740/logcat.txt)

**Comment by troop** [comment]
```
07-10 00:03:46.068 12983 13007 E AndroidRuntime: android.renderscript.RSRuntimeException: Loading of ScriptC script failed.
07-10 00:03:46.068 12983 13007 E AndroidRuntime: 	at android.renderscript.ScriptC.<init>(ScriptC.java:63)
07-10 00:03:46.068 12983 13007 E AndroidRuntime: 	at freed.utils.ScriptC_focus_peak.<init>(ScriptC_focus_peak.java:42)
07-10 00:03:46.068 12983 13007 E AndroidRuntime: 	at freed.utils.ScriptC_focus_peak.<init>(ScriptC_focus_peak.java:34)
07-10 00:03:46.068 12983 13007 E AndroidRuntime: 	at freed.utils.RenderScriptHandler$1.run(RenderScriptHandler.java:67)
07-10 00:03:46.068 12983 13007 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

07-10 01:16:09.404 19203 19220 E RenderScript: Unable to open shared library (/data/user/0/troop.com.freedcam/code_cache/com.android.renderscript.cache/librs.focus_peak.so): (null)
```
hi. 
try first to uninstall freedcam when you come from one of the alphas.
for me it looks like that the app cache is locked from an older installation.
due that it fails to read the renderscript libs. could also happen due a dirty flash.

but it could also be that the rom u use have outdated libs. there was a problem some time ago with the adreno driver. in that case there is nothing i can do and only solution is to disable complete renderscript stuff. 
pls check if the rs scripts are in the path **"/data/user/0/troop.com.freedcam/code_cache/com.android.renderscript.cache/librs.focus_peak.so"**
on my devices the path starts with **/data/data/troop.com.freedcam/**

**Comment by NOT-a-BUG-but-a-FEATURE** [comment]
Before flashing new ROM I wiped everything. And at first install release version. After also tried alpha version and release again. And everytime I removed previous ones.

There is only file **focus_peak.bc** (1.83KB, -rw-------) in the path **/data/data/troop.com.freedcam/code_cache/com.android.renderscript.cache/**.
