### ISSUE TITLE
Support for Mlais M52 Red Note

### ISSUE THREAD

**Issue by ximairon** [troop/FreeDcam#90]
Hello **troop**
Thank you for a wonderful app.
I've been looking for an application that will store images in RAW format. And to use the camera to the maximum. Your application has appeared closest to, but not everything works correctly.
What files do I send to improve compatibility?

**Comment by defcomk** [comment]
Describe the issue your having what is not working as well as attaching the camera parameters from device in the menu scroll down to save Camera Parameters.

**Comment by ximairon** [comment]
[Log files](https://www.dropbox.com/s/vhdlu66wejwpdbq/Log.rar?dl=0)
The main problem is the preservation of Pure Raw with pink shades.
The Engineer Mode I choose Processed Raw, then the color is not distorted.
![screenshot_2016-07-13-14-49-27](https://cloud.githubusercontent.com/assets/20425725/16798575/900c6bf4-490e-11e6-802d-ee914fdb2fe5.png)
But in any case, to work with received Raw images, it is necessary first to convert them using "raw2dng".
If possible, I would like to once FreeDcam remained normal DNG that immediately can be opened in Photoshop.
The same problem with the ISO and Exposure Time settings.
If you select any value other than Auto, the picture turns black.
![screenshot_2016-07-13-14-47-01](https://cloud.githubusercontent.com/assets/20425725/16798604/afc5f5fa-490e-11e6-8e95-0c899d95413c.png)
![screenshot_2016-07-13-14-47-53](https://cloud.githubusercontent.com/assets/20425725/16798603/afc28690-490e-11e6-82ba-1ff6b5b66c62.png)

**Comment by defcomk** [comment]
Attach a raw sample also does setting manual shutter work in eng mode

**Comment by ximairon** [comment]
[manual shutter](https://www.dropbox.com/s/luz5it591098eik/manual%20shutter.rar?dl=0)

**Comment by troop** [comment]
question: how should i identfy colors when you uploaded  black images?
![img_2016_07_13_16_45_23](https://cloud.githubusercontent.com/assets/377693/16836782/98ed0916-49bf-11e6-8d01-193404ec2a75.jpg)

**Comment by ximairon** [comment]
black images are obtained due to the fact that I used a manual shutter.
this is what I wrote above, and asked me to put them.
More over there is an archive with color images https://www.dropbox.com/s/vhdlu66wejwpdbq/Log.rar?dl=0

**Comment by troop** [comment]
3.3.137 contains the changes

**Comment by ximairon** [comment]
all the same as before. + crash
[M52_Red_Note_2016-07-14_09.04.42.txt](https://github.com/troop/FreeDcam/files/364084/M52_Red_Note_2016-07-14_09.04.42.txt)

**Comment by ximairon** [comment]
[M52_Red_Note_log_3.3.137.rar](https://www.dropbox.com/s/zsv2nfr43a9pegf/M52_Red_Note_log_3.3.137.rar?dl=0)
auto settings
IMG_2016_07_14_21_33_45.jpg
mtk1468510423668pure__3264x2448_10_0.bayer

manual shutter settings
IMG_2016_07_14_21_34_14.jpg
mtk1468510452628pure__3264x2448_10_0.bayer

**Comment by troop** [comment]
i dont know what you are doing. the crash log is from camera2.
the other log loads camera1 but stops bevor it get interessting.

does shutter and iso work with the engineer tool?

**Comment by ximairon** [comment]
when I take pictures through an engineering mode / camera and select eg ISO 100, shutter regulated depending on the light. 2,4s in total darkness, to ~ 1/5000 the sun. choose the file format Processed Raw, because after the convertation through raw2dng http://e2500.narod.ru/raw2dng.хтм natural colors are obtained.
This is a cheap Chinese smartphone with crude system. So you can not make even be support for DNG?

**Comment by troop** [comment]
Hm not sure. In theory it should work. That code is used for all devices. And i can convert that raw without problems on my phones. Maybe it runs out of memory. When its rooted pls get logcat extreme and log freedcam with it.

**Comment by ximairon** [comment]
please explain clearer what I need to do. I badly know English and use the Google translator.

**Comment by troop** [comment]
i will try^^
is your phone rooted?
yes:
go to playstore and download there logcat extreme.
grant super user access to it and log everything.
open freedcam and do the stuff wich force close it.
when done, save the log and attach it here.

**Comment by ximairon** [comment]
[Log_2016-07-15_12-28-19.txt](https://github.com/troop/FreeDcam/files/367140/Log_2016-07-15_12-28-19.txt)
[Log_2016-07-15_12-28-19_Part2.txt](https://github.com/troop/FreeDcam/files/367142/Log_2016-07-15_12-28-19_Part2.txt)
[Log_2016-07-15_12-28-19_Part3.txt](https://github.com/troop/FreeDcam/files/367141/Log_2016-07-15_12-28-19_Part3.txt)

**Comment by ximairon** [comment]
https://www.dropbox.com/s/vhdlu66wejwpdbq/Log.rar?dl=0

**Comment by ximairon** [comment]
there are changes?

**Comment by troop** [comment]
no, because i dont understand why the dng converting not trigger for you

**Comment by ximairon** [comment]
is there any hope that you can handle that?

**Comment by ximairon** [comment]
Maybe for proper operation of the FreeDcam lacks any system files or apps? I have removed many system applications.

**Comment by troop** [comment]
aslong the egineer tools works you did not remove needed systemlibs.
i think more it takes to long to write the raw to sd. and the timeoutlimit is set to low 
it waits 2000ms wich was yet enough time

**Comment by ximairon** [comment]
you can save the processed Bauer? instead of pure?

**Comment by troop** [comment]
In theory yes. But its not added

**Comment by ximairon** [comment]
if not difficult, do it yourself.
I still do a photo via the engineering menu, and then converts it himself.
for owners mlais no other way=(

**Comment by troop** [comment]
i dont have a mtk device. the engineer mode is needed. its the only way to dump raws on mtk socs.
i dont understand why the dng converter is not working for you.
that processed raw should be a jpeg just without postprocessing.

**Comment by ximairon** [comment]
hi, you can add the setting in freedcam viewer please
main imx 219
![screenshot_2016-11-25-02-15-28](https://cloud.githubusercontent.com/assets/20425725/20608515/49cae920-b2b5-11e6-8b6a-fe298d471818.png)
sub ov5648
![screenshot_2016-11-25-02-18-33](https://cloud.githubusercontent.com/assets/20425725/20608524/4f24de62-b2b5-11e6-9329-3151fffbced5.png)

**Comment by troop** [comment]
for front i need to know the size from a bayer file in bytes

**Comment by ximairon** [comment]
main imx219 - 15980544 bytes
sub ov5648 - 9830400 bytes

**Comment by troop** [comment]
Its normal. It gets converted to a true 10bit dng.
Mtk stores 10bit values in 16bit. In bits it looks like
 
0000 0011 1111 1111
The first 6 empty bits gets droped to reduce filesize

**Comment by ximairon** [comment]
there are a few problems:
problem with video recording. I try different settings.
![screenshot_2016-11-30-17-47-44](https://cloud.githubusercontent.com/assets/20425725/20749716/1c7f08dc-b726-11e6-8a8c-2bc37afd692b.png)

It does not start with the lockscreen.
black viewfinder when minimized.

**Comment by ximairon** [comment]
Hello, help to create a custom matrix. I got to this point, and then do not understand how to use exiftools. Now the saved file: https://drive.google.com/open?id=0Bz6szBzz9fKFU1B5MDZ5STcxS2M

**Comment by troop** [comment]
normaly you just have to drag/drop the dng on exiftools.

but here are the matrixes from the dng you uploaded

```
As Shot Neutral                 : 0.5391 1 0.6641
Color Matrix 1                  : 1.1407 -0.4022 -0.234 -0.4314 1.404 0.0146 -0.0439 0.2047 0.5704
Color Matrix 2                  : 0.7228 -0.0893 -0.0975 -0.4792 1.3481 0.1381 -0.1137 0.268 0.5604
Forward Matrix 1                : 0.6328 0.0469 0.2813 0.1641 0.7578 0.0781 -0.0469 -0.6406 1.5078
Forward Matrix 2                : 0.7578 0.0859 0.1172 0.2734 0.8281 -0.1016 0.0156 -0.2813 1.0859
Noise Profile                   : 0.00051471478 0 0.00051471478 0 0.00051471478 0
```

**Comment by ximairon** [comment]
Thanx

**Comment by ximairon** [comment]
after the addition of a matrix when you start raw to dng crashes.

**Comment by troop** [comment]
use it that way:
```
1.1407,-0.4022,-0.234,-0.4314,1.404,0.0146,-0.0439,0.2047,0.5704
0.7228,-0.0893,-0.0975,-0.4792,1.3481,0.1381,-0.1137,0.268,0.5604
0.5391,1,0.6641
0.6328,0.0469,0.2813,0.1641,0.7578 0.0781,-0.0469,-0.6406,1.5078
0.7578,0.0859,0.1172,0.2734,0.8281,-0.1016,0.0156,-0.2813,1.0859
NULL
NULL
0.00051471478,0,0.00051471478,0,0.00051471478,0
```

**Comment by ximairon** [comment]
does not work=(
[matrix.txt](https://github.com/troop/FreeDcam/files/642335/matrix.txt)

**Comment by troop** [comment]
yes there is a whitespace left that needed to replaced with `,`
i fixed my above post

**Comment by ximairon** [comment]
Thank you troop.
Matrix works, although I have not noticed a difference.
in 3.3.147beta8 setting for freedcamviewer also works fine.
In general, this is the best camera app for my cheap Chinese friend.

**Comment by ximairon** [comment]
You can make bayer files have the same name as the jpeg?

**Comment by ximairon** [comment]
Hey. perhaps this question has been asked. is there a converter to raw to dng for windows?

**Comment by troop** [comment]
i patched some time ago rawtherapee that it works with bayer files. but that got dropped due problems with same filesize from raws, but different colorpattern. in theory the rawtodng part can get ported to windows. but thats nothing i will do.

**Comment by ximairon** [comment]
Hey. please take a look at these mistakes.
[2017-01-26_200805_logcat.txt](https://github.com/troop/FreeDcam/files/732341/2017-01-26_200805_logcat.txt)
[screenrecord_26.01.2017_20.06.53.mp4](https://yadi.sk/i/2lzJdEdi3B3T4k)

**Comment by ximairon** [comment]
Hello!
4.1_alpha5
1. does not work FocusPeak / ZebraPattern
2. The need to change the settings rawtodng:
![screenshot_2017-03-06-22-09-36](https://cloud.githubusercontent.com/assets/20425725/23616082/2198b6de-02bb-11e7-9d15-200b078cc599.png)

**Comment by troop** [comment]
1. yep somethings wrong
2. what exactly mean, you want that settings applied to your device?

**Comment by ximairon** [comment]
at this point the black level is set automatically to 16 and 65 need.

**Comment by ximairon** [comment]
I liked the idea of a delay in real time. informative. but it is better to move the setting to the top panel.

**Comment by ximairon** [comment]
4.1_alpha8
Crash on startup

**Comment by ximairon** [comment]
Dng works, it's great!
Starting with some version, the orientation correction is not working correctly.
The launch of the camera from the Lockscreen is still not working.
[log.txt](https://github.com/troop/FreeDcam/files/1073865/log.txt)
![screenshot_2017-06-14-14-48-46](https://user-images.githubusercontent.com/20425725/27121313-fb406c9e-5110-11e7-8313-fde4ef22ad68.png)
