### ISSUE TITLE
request to add mimax pro (SD652)

### ISSUE THREAD

**Issue by scurrvy2020** [troop/FreeDcam#91]
I beleive the xiaomi mimax 652 should behave the same as the Redmi Note 3 Pro (SD652) 

If you need me to provide logs or bayer files I can help to do that.

**Comment by troop** [comment]
someone send me stuff about mi max, will look in the afternoon into it when  it not gets so warm today...^^

**Comment by scurrvy2020** [comment]
Hi troop,  Thanks for your reply.  I sent an email to freedcam@email.de with the bayer and parameter file.  Let me know if you didn't receive it and I'll resend it.

**Comment by troop** [comment]
that should support it now
https://github.com/troop/FreeDcam/releases/tag/3.3.139beta

**Comment by scurrvy2020** [comment]
Thanks!  works great!
