### ISSUE TITLE
Xiaomi Redmi 3

### ISSUE THREAD

**Issue by ma3axaka007** [troop/FreeDcam#92]
I think the Xiaomi Redmi 3 should behave the same as Xiaomi Redmi Note 3. But i can't get DNG option in Picture Format. There are only 'bayer' and 'jpeg'.
I can provide bayer files, configs, logs, etc.

**Comment by troop** [comment]
i need the bayer and the cameraparameters. pls upload both somewhere or send it per mail

**Comment by ma3axaka007** [comment]
I sent an email to freedcam@email.de with camera parameters and bayer files

**Comment by ma3axaka007** [comment]
Well, now I get DNG option, but my .dng file is 0 bytes size. Is it an issue_

**Comment by troop** [comment]
yes because i forgot to add the dng size. im sorry

**Comment by Neminator** [comment]
I have redmi 3 also, i still see only bayer and jpeg, i will post files later on your email

**Comment by ma3axaka007** [comment]
@Neminator , What MIUI version are you using?
P.S. I'm on China Developer rom version 6.7.28 (MIUI 8)

**Comment by Neminator** [comment]
China stable 7.5.2.0 Miui 7

**Comment by troop** [comment]
updated to 140

**Comment by Neminator** [comment]
it crashes on shutter speed and exposure, but raw works like a charm

**Comment by troop** [comment]
looks like redmi3 doesnt support manual shutter and iso. i disable it

**Comment by ma3axaka007** [comment]
@troop Can you add Xiaomi Redmi 3 to README.md file?
