### ISSUE TITLE
DNG for UMI Rome X

### ISSUE THREAD

**Issue by vzhilov** [troop/FreeDcam#93]
Hi, UMI Rome X is a popular cheap phone with a good 13 Mp camera Sony IMX179. Can DNG converter be added, I get only .bayder files. I just sent example of such a file to your email.

**Comment by troop** [comment]
yes can get added. i recieved the mail

**Comment by troop** [comment]
the cameraparameters are missing, pls attach them

**Comment by vzhilov** [comment]
Is it this one?

[CustomMediaProfiles[1].txt](https://github.com/troop/FreeDcam/files/389650/CustomMediaProfiles.1.txt)

**Comment by troop** [comment]
no sorry. open freedcam and go to settings. on left tap scroll to bottom and click on save cameraparameters.
it gets then saved to dcim/freedcam/

**Comment by vzhilov** [comment]
Thank you, I found it.

[ROME_X_CameraParameters[1].txt](https://github.com/troop/FreeDcam/files/390393/ROME_X_CameraParameters.1.txt)
