### ISSUE TITLE
No DNG option for Meizu MX4 Pro

### ISSUE THREAD

**Issue by vzhilov** [troop/FreeDcam#95]
Hello! Thank you for working on such a good app! The description says it supports DNG for Meizu MX4 Pro, however I don't have that option, on my other phone (UMI Rome X) I can choose jpg or bayer, here on Meizu I get only jpg. When I choose Camera2 API I het garbled picture but maybe I don't need camera2 api, but it would be good to have DNG. There is no shatter speed in manual mode as well.

I'm attaching my cameraparamets file in case it is needed.
[MX4_Pro_CameraParameters[1].txt](https://github.com/troop/FreeDcam/files/390405/MX4_Pro_CameraParameters.1.txt)

**Comment by troop** [comment]
hi
that meizu mx4/5 are mtk socs.
your mx4 pro looks not like it is. and no idea what soc it user.
raw/dng capture looks bad.
Shutter and mf are theoretical possible to implement

**Comment by vzhilov** [comment]
Thank you. I checked in AIDA64, the soc is Samsung Exynos 5 Octa 5430 (same as in Samsung Galaxy Alfa, A8 and Note 4) which I belive should have DNG support.

**Comment by troop** [comment]
i googled about that devices and non of them support raw/dng.
only s7/s6 and devices with camera2 from samsung support it.

**Comment by vzhilov** [comment]
So, no RAW, I get it. It is good I have another phone UMI Rome X which you said can be added. Thank you.
