### ISSUE TITLE
When you click the home button, then turn on the camera can not take pictures

### ISSUE THREAD

**Issue by toutoumu** [troop/FreeDcam#99]
08-01 12:40:15.798 5963-5963/troop.com.freedcam D/PictureModule: DoWork:isWorking:false
08-01 12:40:15.798 5963-5963/troop.com.freedcam D/PictureModule: DoWork:picformat:jpeg
08-01 12:40:15.809 5963-5963/troop.com.freedcam D/PictureModule: TakePicture
08-01 12:40:16.523 5963-5963/troop.com.freedcam D/PictureModule: onPictureTaken():1083290
08-01 12:40:16.531 5963-19758/troop.com.freedcam D/PictureModule: saveImage:IMG_2016_08_01_12_40_16.jpg Filesize: 1083290
08-01 12:40:31.095 5963-5963/troop.com.freedcam D/PictureModule: InitModule
08-01 12:40:42.183 5963-5963/troop.com.freedcam D/PictureModule: DoWork:isWorking:false
08-01 12:40:42.183 5963-5963/troop.com.freedcam D/PictureModule: DoWork:picformat:jpeg
08-01 12:40:42.194 5963-5963/troop.com.freedcam D/PictureModule: TakePicture
08-01 12:40:42.970 5963-5963/troop.com.freedcam D/PictureModule: onPictureTaken():1524770
08-01 12:40:42.978 5963-20357/troop.com.freedcam D/PictureModule: saveImage:IMG_2016_08_01_12_40_42.jpg Filesize: 1524770
08-01 12:40:46.981 5963-5963/troop.com.freedcam D/PictureModule: DoWork:isWorking:false
08-01 12:40:46.981 5963-5963/troop.com.freedcam D/PictureModule: DoWork:picformat:jpeg
08-01 12:40:46.991 5963-5963/troop.com.freedcam D/PictureModule: TakePicture
08-01 12:40:48.696 5963-5963/troop.com.freedcam D/PictureModule: InitModule
08-01 12:40:48.696 5963-5963/troop.com.freedcam D/PictureModule: DoWork:isWorking:true
08-01 12:40:58.667 5953-5963/troop.com.freedcam D/PictureModule: DoWork:isWorking:true

**Comment by troop** [comment]
Cant reproduce the problem. It works on all my devices.

**Comment by toutoumu** [comment]
我把重现方式写在了下面的代码注释里(Reproducible way to write in the following code comments in...)

PictureModule.java  DoWork();
````
public boolean DoWork()
    {
        Logger.d(this.TAG, "DoWork:isWorking:"+ isWorking);
        if (!isWorking)
        {
            isWorking = true;
            String picformat = cameraUiWrapper.GetParameterHandler().PictureFormat.GetValue();
            Logger.d(this.TAG,"DoWork:picformat:" + picformat);
            if (picformat.equals(KEYS.DNG) ||picformat.equals(KEYS.BAYER))
            {
                if (cameraUiWrapper.GetParameterHandler().ZSL != null && cameraUiWrapper.GetParameterHandler().ZSL.IsSupported()
                        && cameraUiWrapper.GetParameterHandler().ZSL.GetValue().equals("on") && ((CameraHolder) cameraUiWrapper.GetCameraHolder()).DeviceFrameWork != CameraHolder.Frameworks.MTK)
                {
                    Logger.d(this.TAG,"ZSL is on turning it off");
                    cameraUiWrapper.GetParameterHandler().ZSL.SetValue("off", true);
                    Logger.d(this.TAG,"ZSL state after turning it off:" + cameraUiWrapper.GetParameterHandler().ZSL.GetValue());
                }
            }
            changeCaptureState(CaptureStates.image_capture_start);
            waitForPicture = true;
            burstcount = 0;          
            try {
                Thread.sleep(1000*3);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
// 在这个时候按下home键, Camera.onPictureTaken()方法没有被调用
// At this time pressing the home key, Camera.onPictureTaken () method has not been called
            cameraHolder.TakePicture(this);
            Logger.d(this.TAG,"TakePicture");
        }
        return true;

    }
````

**Comment by troop** [comment]
Hm thx i see the problem. Normal user would not pause the app while a capture is in progress.
Solution is to block the app from pause until the capture has finished.
